### PR TITLE
More resilient broadcast handling (fixes #1907)

### LINKED ISSUE #1907: Server stops receiving local announcements from other devices
Setup:
- syncthing v0.11.7
- 2 devices ('server' and 'desktop') sharing one directory
- only local discovery (UPnP, global discovery are disabled)
- 2 Android ST devices in the same network, but no sharing with the other 2 devices

Problem: after some time, the 'server' device stops receiving local announcements from the 'desktop' device

How to reproduce:
- Start ST on both devices, synchronizing works between them
- Switch off 'desktop' device, wait some time
- Switch on 'desktop', start ST => no contact to 'server' device could be established

https://forum.syncthing.net/t/server-stops-receiving-local-announcements-from-other-devices/2896

Log file from 'server' device:
```
[start] 2015/05/31 17:54:07.028529 verbose.go:42: VERBOSE: Starting up (/srv/home/kodi/.config/syncthing)
[TOXD7] 2015/05/31 17:54:08.089541 main.go:466: INFO: syncthing v0.11.7 (go1.4.2 linux-amd64 default) builduser@jara 2015-05-31 07:37:02 UTC
[TOXD7] 2015/05/31 17:54:08.089724 main.go:467: INFO: My ID: TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:08.109021 main.go:738: INFO: Database block cache capacity 29304 KiB
[TOXD7] 2015/05/31 17:54:08.210199 main.go:793: INFO: Starting web GUI on http://127.0.0.1:8384/
[TOXD7] 2015/05/31 17:54:09.223959 main.go:868: INFO: Starting local discovery announcements
[TOXD7] 2015/05/31 17:54:09.224687 verbose.go:42: VERBOSE: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS sent an index update for "tst" with 0 items
[TOXD7] 2015/05/31 17:54:09.224766 main.go:646: OK: Ready to synchronize tst (read-write)
[TOXD7] 2015/05/31 17:54:09.225172 main.go:662: INFO: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS is "kallisto" at [dynamic]
[TOXD7] 2015/05/31 17:54:09.225525 main.go:662: INFO: Device TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY is "europa" at [dynamic]
[TOXD7] 2015/05/31 17:54:09.226125 connections.go:206: DEBUG: listening on 0.0.0.0:22000
[TOXD7] 2015/05/31 17:54:09.227392 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:54:09.227567 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:54:09.227615 verbose.go:42: VERBOSE: Startup complete
[TOXD7] 2015/05/31 17:54:09.227668 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 17:54:09.227778 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:54:09.227823 rwfolder.go:282: INFO: Completed initial scan (rw) of folder tst
[TOXD7] 2015/05/31 17:54:09.227921 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:54:09.227978 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:09.228389 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:09.381785 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 17:54:09.382308 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 17:54:09.382766 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{192.168.1.102:22000 2015-05-31 17:54:09.382389809 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:09.383046 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:09.383139 verbose.go:42: VERBOSE: Discovered device JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 at [192.168.1.102:22000]
[TOXD7] 2015/05/31 17:54:09.383502 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 17:54:09.383914 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{192.168.1.102:22000 2015-05-31 17:54:09.382389809 +0200 CEST} {[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 17:54:09.383558286 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:09.384099 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:54:09.384185 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:09.384252 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:54:09.384312 verbose.go:42: VERBOSE: Discovered device JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 at [192.168.1.102:22000 [fe80::fae0:79ff:fe79:55a%enp3s0]:22000]
[TOXD7] 2015/05/31 17:54:09.384645 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:09.384728 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:54:09.385067 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:54:09.385179 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:54:09.385234 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:54:09.385582 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:09.385636 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.137938 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 17:54:23.138343 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.138711 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.138405386 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.138829 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.139145 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.139466 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.138405386 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.139195999 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.139844 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:54:23.139970 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:54:23.140384 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.140445 verbose.go:42: VERBOSE: Discovered device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [192.168.1.3:22000]
[TOXD7] 2015/05/31 17:54:23.140507 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:54:23.140690 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 17:54:23.140837 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 17:54:23.140991 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.141350 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.142489 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:23.142974 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.143440 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.143046978 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.139195999 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.143897 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.144352 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.143969037 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.139195999 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.144781 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.145300 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.143969037 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.144877789 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.145805 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.146275 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.143969037 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.145879107 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.146342 verbose.go:42: VERBOSE: Discovered device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [192.168.1.3:22000 [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000]
[TOXD7] 2015/05/31 17:54:23.146418 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:54:23.146505 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.146563 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:54:23.146617 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:54:23.147138 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:23.323969 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 17:54:23.324438 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 17:54:23.324884 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{192.168.1.102:22000 2015-05-31 17:54:23.324492667 +0200 CEST} {[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 17:54:09.383558286 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.324972 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 17:54:23.325050 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.325468 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.325818 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.325546401 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.145879107 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.326161 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.326574 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.325546401 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.326251538 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.328029 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.328564 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 17:54:23.329393 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{192.168.1.102:22000 2015-05-31 17:54:23.324492667 +0200 CEST} {[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 17:54:23.328647183 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.329516 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:23.329752 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 17:54:23.330093 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.330471 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.325546401 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.330164617 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:23.330774 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:23.331091 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.330826747 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:23.330164617 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:24.139851 connections.go:226: DEBUG: connect from [fe80::7a24:afff:fe8a:ca08%enp3s0]:52147
[TOXD7] 2015/05/31 17:54:24.227743 connections.go:282: DEBUG: dial IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS 192.168.1.3:22000
[TOXD7] 2015/05/31 17:54:24.287876 connections.go:176: INFO: Established secure connection to IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [fe80::d250:99ff:fe31:5af0%enp3s0]:22000-[fe80::7a24:afff:fe8a:ca08%enp3s0]:52147
[TOXD7] 2015/05/31 17:54:24.287968 connections.go:178: DEBUG: cipher suite: C02F in lan: false
[TOXD7] 2015/05/31 17:54:24.288755 verbose.go:42: VERBOSE: Connected to device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [fe80::7a24:afff:fe8a:ca08%enp3s0]:52147
[TOXD7] 2015/05/31 17:54:24.329398 model.go:606: INFO: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS client is "syncthing v0.11.7"
[TOXD7] 2015/05/31 17:54:24.329701 model.go:611: INFO: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS name is "kallisto"
[TOXD7] 2015/05/31 17:54:24.329777 verbose.go:42: VERBOSE: Connected to device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [fe80::7a24:afff:fe8a:ca08%enp3s0]:52147
[TOXD7] 2015/05/31 17:54:24.359684 connections.go:306: INFO: TLS handshake: read tcp 192.168.1.3:22000: connection reset by peer
[TOXD7] 2015/05/31 17:54:24.360070 connections.go:282: DEBUG: dial IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000
[TOXD7] 2015/05/31 17:54:24.369587 verbose.go:42: VERBOSE: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS sent an index update for "tst" with 1 items
[TOXD7] 2015/05/31 17:54:24.493322 connections.go:306: INFO: TLS handshake: read tcp [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000: connection reset by peer
[TOXD7] 2015/05/31 17:54:29.374247 verbose.go:42: VERBOSE: Folder "tst" is now syncing
[TOXD7] 2015/05/31 17:54:29.375083 verbose.go:42: VERBOSE: Started syncing "tst" / "hello.txt" (update file)
[TOXD7] 2015/05/31 17:54:29.395871 verbose.go:42: VERBOSE: Finished syncing "tst" / "hello.txt" (update file): Success
[TOXD7] 2015/05/31 17:54:29.398745 verbose.go:42: VERBOSE: Updated index for folder "tst" with 1 items
[TOXD7] 2015/05/31 17:54:29.401985 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:54:29.409277 verbose.go:42: VERBOSE: Summary for folder "tst" is map[state:idle globalDeleted:0 localFiles:1 localBytes:25 version:24 needFiles:0 needBytes:0 inSyncFiles:1 inSyncBytes:25 globalFiles:1 globalBytes:25 localDeleted:0]
[TOXD7] 2015/05/31 17:54:29.412370 verbose.go:42: VERBOSE: Completion for folder "tst" on device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS is 100%
[TOXD7] 2015/05/31 17:54:39.225179 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:54:39.225454 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:54:39.225910 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:54:39.226074 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:39.226277 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:54:48.703562 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 17:54:48.703963 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 17:54:48.704463 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{192.168.1.102:22000 2015-05-31 17:54:48.704020406 +0200 CEST} {[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 17:54:23.328647183 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:48.705884 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:48.706578 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 17:54:48.707153 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{192.168.1.102:22000 2015-05-31 17:54:48.704020406 +0200 CEST} {[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 17:54:48.706641913 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:53.138356 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:54:53.138801 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:53.139194 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:23.330826747 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:53.138866821 +0200 CEST}]
[TOXD7] 2015/05/31 17:54:53.139316 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 17:54:53.139766 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:54:53.140114 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:53.13982602 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:54:53.138866821 +0200 CEST}]
[TOXD7] 2015/05/31 17:55:09.225093 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:55:09.225340 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:55:09.225486 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:55:09.225563 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:55:09.225931 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:55:14.004593 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 17:55:14.005475 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:55:23.138205 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 17:55:23.138598 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 17:55:23.139070 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 17:54:53.13982602 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 17:55:23.138658976 +0200 CEST}]
[TOXD7] 2015/05/31 17:55:39.225121 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:55:39.225302 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:55:39.225567 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:55:39.225675 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:55:39.226014 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:56:09.225465 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:56:09.225663 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:56:09.226039 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:56:09.226121 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:56:09.226465 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:56:12.459087 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 17:56:12.459692 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:56:39.225153 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:56:39.225402 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:56:39.225866 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:56:39.225938 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:56:39.226098 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:57:09.225137 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:57:09.225430 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:57:09.225556 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:57:09.225646 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:57:09.225976 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:57:16.860938 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 17:57:16.861663 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:57:24.339269 verbose.go:42: VERBOSE: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS sent an index update for "tst" with 1 items
[TOXD7] 2015/05/31 17:57:29.342267 verbose.go:42: VERBOSE: Folder "tst" is now syncing
[TOXD7] 2015/05/31 17:57:29.342557 verbose.go:42: VERBOSE: Started syncing "tst" / "hello.txt" (update file)
[TOXD7] 2015/05/31 17:57:29.344715 verbose.go:42: VERBOSE: Finished syncing "tst" / "hello.txt" (update file): Success
[TOXD7] 2015/05/31 17:57:29.348170 verbose.go:42: VERBOSE: Updated index for folder "tst" with 1 items
[TOXD7] 2015/05/31 17:57:29.351257 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:57:29.361660 verbose.go:42: VERBOSE: Summary for folder "tst" is map[needFiles:0 needBytes:0 inSyncFiles:1 inSyncBytes:21 localDeleted:0 version:27 globalDeleted:0 state:idle globalBytes:21 localFiles:1 localBytes:21 globalFiles:1]
[TOXD7] 2015/05/31 17:57:29.361762 verbose.go:42: VERBOSE: Completion for folder "tst" on device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS is 100%
[TOXD7] 2015/05/31 17:57:39.225151 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:57:39.225383 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:57:39.225887 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:57:39.225980 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:57:39.226113 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:58:09.225486 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:58:09.225681 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:58:09.226056 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:58:09.226139 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:58:09.226540 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:58:25.387752 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 17:58:25.388451 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:58:39.225188 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:58:39.225409 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:58:39.225642 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:58:39.225984 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:58:39.226348 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:59:09.225487 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:59:09.225681 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:59:09.225897 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:59:09.225974 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:59:09.226321 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 17:59:21.811306 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 17:59:21.814887 verbose.go:42: VERBOSE: Updated index for folder "tst" with 1 items
[TOXD7] 2015/05/31 17:59:21.815019 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:59:29.343662 verbose.go:42: VERBOSE: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS sent an index update for "tst" with 1 items
[TOXD7] 2015/05/31 17:59:34.347152 verbose.go:42: VERBOSE: Folder "tst" is now syncing
[TOXD7] 2015/05/31 17:59:34.349753 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 17:59:34.354942 verbose.go:42: VERBOSE: Summary for folder "tst" is map[globalDeleted:0 localDeleted:0 version:29 state:idle globalFiles:1 globalBytes:13 localFiles:1 localBytes:13 needFiles:0 needBytes:0 inSyncFiles:1 inSyncBytes:13]
[TOXD7] 2015/05/31 17:59:34.357683 verbose.go:42: VERBOSE: Completion for folder "tst" on device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS is 100%
[TOXD7] 2015/05/31 17:59:39.225192 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 17:59:39.225431 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 17:59:39.225655 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 17:59:39.225757 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 17:59:39.226301 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:00:09.225036 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:00:09.225421 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:00:09.225709 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:00:09.226235 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:00:09.226326 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:00:15.176888 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:00:15.177545 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:00:39.225065 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:00:39.225221 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:00:39.225398 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:00:39.225853 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:00:39.225947 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:01:09.225095 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:01:09.225289 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:01:09.225546 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:01:09.225638 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:01:09.225987 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:01:12.342415 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:01:12.343233 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:01:39.225203 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:01:39.225431 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:01:39.225691 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:01:39.225781 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:01:39.226192 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:01:39.489479 model.go:692: INFO: Connection to IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS closed: read tcp [fe80::7a24:afff:fe8a:ca08%enp3s0]:52147: connection reset by peer
[TOXD7] 2015/05/31 18:01:39.494540 verbose.go:42: VERBOSE: Disconnected from device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:01:44.356774 verbose.go:42: VERBOSE: Folder "tst" is now syncing
[TOXD7] 2015/05/31 18:01:44.359421 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:01:44.362762 verbose.go:42: VERBOSE: Summary for folder "tst" is map[needBytes:0 inSyncFiles:1 inSyncBytes:13 needFiles:0 localDeleted:0 globalFiles:1 globalBytes:13 state:idle localBytes:13 version:14 globalDeleted:0 localFiles:1]
[TOXD7] 2015/05/31 18:01:58.195834 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:01:58.196357 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:01:58.196416 discover.go:423: DEBUG: discover: Removing cached address 192.168.1.102:22000 - seen 7m9.492379138s ago
[TOXD7] 2015/05/31 18:01:58.196510 discover.go:423: DEBUG: discover: Removing cached address [fe80::fae0:79ff:fe79:55a%enp3s0]:22000 - seen 7m9.48985285s ago
[TOXD7] 2015/05/31 18:01:58.196887 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:01:58.196549207 +0200 CEST}]
[TOXD7] 2015/05/31 18:01:58.197030 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:01:58.197460 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:01:58.197867 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:01:58.196549207 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:01:58.197513482 +0200 CEST}]
[TOXD7] 2015/05/31 18:01:58.198229 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:01:58.198415 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:01:58.198514 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:01:58.199000 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:01:58.199059 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:01:58.199290 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:01:58.199347 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:01:58.199448 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:01:58.199499 verbose.go:42: VERBOSE: Discovered device JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 at [[fe80::fae0:79ff:fe79:55a%enp3s0]:22000]
[TOXD7] 2015/05/31 18:01:58.199558 verbose.go:42: VERBOSE: Discovered device JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 at [[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 192.168.1.102:22000]
[TOXD7] 2015/05/31 18:01:58.199626 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:01:58.199926 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:01:58.206388 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:01:58.206704 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:01:58.207016 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:01:58.196549207 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:01:58.206749494 +0200 CEST}]
[TOXD7] 2015/05/31 18:01:58.207956 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:01:58.208294 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:01:58.208611 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:01:58.208340114 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:01:58.206749494 +0200 CEST}]
[TOXD7] 2015/05/31 18:02:09.225083 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:02:09.225254 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:02:09.225350 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:02:09.225735 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:02:09.225787 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:02:12.499351 discover.go:423: DEBUG: discover: Removing cached address 192.168.1.3:22000 - seen 7m19.359436497s ago
[TOXD7] 2015/05/31 18:02:12.499428 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 6m49.360755304s ago
[TOXD7] 2015/05/31 18:02:24.912558 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:02:24.913252 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:02:39.225780 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:02:39.225958 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:02:39.226031 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:02:39.226363 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:02:39.226649 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:03:09.225268 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:03:09.225750 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:03:09.225840 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:03:09.226182 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:03:09.226244 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:03:12.499974 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 7m49.361288387s ago
[TOXD7] 2015/05/31 18:03:12.500057 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 7m49.36138531s ago
[TOXD7] 2015/05/31 18:03:18.207184 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:03:18.207880 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:03:39.225145 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:03:39.225363 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:03:39.225424 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:03:39.225786 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:03:39.225837 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:09.225142 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:04:09.225354 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:04:09.225416 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:04:09.225753 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:04:09.225818 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:12.500629 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 8m49.361880369s ago
[TOXD7] 2015/05/31 18:04:12.500704 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 8m49.362032492s ago
[TOXD7] 2015/05/31 18:04:17.601919 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:04:17.602665 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:04:39.225105 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:04:39.225279 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:04:39.225384 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:04:39.225752 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:04:39.225805 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.504571 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 18:04:40.504677 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.505036 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.505103 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 9m17.366429384s ago
[TOXD7] 2015/05/31 18:04:40.505149 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 9m17.366477275s ago
[TOXD7] 2015/05/31 18:04:40.505573 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.505191571 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.505990 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.506387 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.505191571 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.506040719 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.506508 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:04:40.506624 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:04:40.506670 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.506825 verbose.go:42: VERBOSE: Discovered device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [192.168.1.3:22000]
[TOXD7] 2015/05/31 18:04:40.506978 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:04:40.507075 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 18:04:40.507116 verbose.go:42: VERBOSE: Discovered device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [192.168.1.3:22000 [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000]
[TOXD7] 2015/05/31 18:04:40.507419 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:04:40.507708 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.508033 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.507763098 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.506040719 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.508101 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.508436 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.508511 broadcast.go:50: WARNING: Broadcast: interface addresses: netlink rib: invalid argument
[TOXD7] 2015/05/31 18:04:40.508617 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.509005 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.507763098 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.508497971 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.509300 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.509624 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.507763098 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.509355543 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.509718 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 18:04:40.510047 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.510356 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.510092816 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.509355543 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.595047 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.595758 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:04:40.596107 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:04:40.59582912 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:01:58.206749494 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.596180 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:04:40.596256 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 18:04:40.596556 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:04:40.596874 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:04:40.59582912 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:04:40.596604336 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.597152 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.597453 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.597195067 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.509355543 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.597507 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 18:04:40.597797 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.598100 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.597839509 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.509355543 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.598183 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.598578 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.598931 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.597839509 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.598659101 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:40.599005 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 18:04:40.599345 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:04:40.599659 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.597839509 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:04:40.599390746 +0200 CEST}]
[TOXD7] 2015/05/31 18:04:41.505666 connections.go:226: DEBUG: connect from [fe80::7a24:afff:fe8a:ca08%enp3s0]:52175
[TOXD7] 2015/05/31 18:04:41.650714 connections.go:176: INFO: Established secure connection to IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [fe80::d250:99ff:fe31:5af0%enp3s0]:22000-[fe80::7a24:afff:fe8a:ca08%enp3s0]:52175
[TOXD7] 2015/05/31 18:04:41.650792 connections.go:178: DEBUG: cipher suite: C02F in lan: false
[TOXD7] 2015/05/31 18:04:41.651169 verbose.go:42: VERBOSE: Connected to device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [fe80::7a24:afff:fe8a:ca08%enp3s0]:52175
[TOXD7] 2015/05/31 18:04:41.692772 model.go:606: INFO: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS client is "syncthing v0.11.7"
[TOXD7] 2015/05/31 18:04:41.693081 model.go:611: INFO: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS name is "kallisto"
[TOXD7] 2015/05/31 18:04:41.693141 verbose.go:42: VERBOSE: Connected to device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS at [fe80::7a24:afff:fe8a:ca08%enp3s0]:52175
[TOXD7] 2015/05/31 18:04:41.733610 verbose.go:42: VERBOSE: Device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS sent an index update for "tst" with 1 items
[TOXD7] 2015/05/31 18:04:46.736906 verbose.go:42: VERBOSE: Folder "tst" is now syncing
[TOXD7] 2015/05/31 18:04:46.737001 verbose.go:42: VERBOSE: Started syncing "tst" / "hello.txt" (update file)
[TOXD7] 2015/05/31 18:04:46.739109 verbose.go:42: VERBOSE: Finished syncing "tst" / "hello.txt" (update file): Success
[TOXD7] 2015/05/31 18:04:46.742311 verbose.go:42: VERBOSE: Updated index for folder "tst" with 1 items
[TOXD7] 2015/05/31 18:04:46.745141 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:04:46.755266 verbose.go:42: VERBOSE: Summary for folder "tst" is map[globalDeleted:0 localDeleted:0 version:32 state:idle localBytes:30 globalFiles:1 globalBytes:30 localFiles:1 inSyncFiles:1 inSyncBytes:30 needFiles:0 needBytes:0]
[TOXD7] 2015/05/31 18:04:46.755609 verbose.go:42: VERBOSE: Completion for folder "tst" on device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS is 100%
[TOXD7] 2015/05/31 18:05:08.121472 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:05:08.122194 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:05:09.225335 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[TOXD7] 2015/05/31 18:05:09.225496 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[TOXD7] 2015/05/31 18:05:09.225568 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.2:21025
[TOXD7] 2015/05/31 18:05:09.226025 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.2:21025 for TOXD7QH-J2LWOVE-MMCKJ6M-TMPEAF2-XJ2X4T6-VFO7Z6R-PC4K5ZP-ZKJNNQY
[TOXD7] 2015/05/31 18:05:10.504939 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 18:05:10.505465 discover.go:350: DEBUG: discover: Received local announcement from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026 for IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:05:10.505862 discover.go:400: DEBUG: discover: Caching IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS addresses: [{192.168.1.3:22000 2015-05-31 18:04:40.597839509 +0200 CEST} {[fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 2015-05-31 18:05:10.505514151 +0200 CEST}]
[TOXD7] 2015/05/31 18:05:12.976661 model.go:692: INFO: Connection to IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS closed: read tcp [fe80::7a24:afff:fe8a:ca08%enp3s0]:52175: connection reset by peer
[TOXD7] 2015/05/31 18:05:12.980628 verbose.go:42: VERBOSE: Disconnected from device IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS
[TOXD7] 2015/05/31 18:05:16.748922 verbose.go:42: VERBOSE: Folder "tst" is now syncing
[TOXD7] 2015/05/31 18:05:16.749327 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:05:16.754987 verbose.go:42: VERBOSE: Summary for folder "tst" is map[state:idle localBytes:30 globalFiles:1 globalBytes:30 localFiles:1 inSyncFiles:1 inSyncBytes:30 needFiles:0 needBytes:0 globalDeleted:0 localDeleted:0 version:15]
[TOXD7] 2015/05/31 18:05:58.904486 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:05:58.904987 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:05:58.905437 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:05:58.90503638 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:04:40.596604336 +0200 CEST}]
[TOXD7] 2015/05/31 18:05:58.906738 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:05:58.907275 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:05:58.907674 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:05:58.90503638 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:05:58.907326126 +0200 CEST}]
[TOXD7] 2015/05/31 18:06:09.729520 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:06:09.730172 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:06:12.501885 connections.go:282: DEBUG: dial IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS 192.168.1.3:22000
[TOXD7] 2015/05/31 18:06:30.545682 connections.go:296: DEBUG: dial tcp 192.168.1.3:22000: no route to host
[TOXD7] 2015/05/31 18:06:30.546032 connections.go:282: DEBUG: dial IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000
[TOXD7] 2015/05/31 18:07:08.251828 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:07:08.252665 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:08:20.085256 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:08:20.086207 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:08:37.882143 connections.go:296: DEBUG: dial tcp [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000: connection timed out
[TOXD7] 2015/05/31 18:09:11.633273 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:09:11.633938 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:09:37.882986 connections.go:282: DEBUG: dial IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS 192.168.1.3:22000
[TOXD7] 2015/05/31 18:09:40.892508 connections.go:296: DEBUG: dial tcp 192.168.1.3:22000: no route to host
[TOXD7] 2015/05/31 18:09:40.892866 connections.go:282: DEBUG: dial IDGFELO-L55B7IE-44XTOOT-WGZ4L62-VFCOGKS-6TZQATR-XYQAI6A-FI7Z3QS [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000
[TOXD7] 2015/05/31 18:10:12.587064 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:10:12.587706 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:11:15.639322 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:11:15.639848 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:11:18.527527 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:11:18.528016 discover.go:350: DEBUG: discover: Received local announcement from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:11:18.528076 discover.go:423: DEBUG: discover: Removing cached address [fe80::fae0:79ff:fe79:55a%enp3s0]:22000 - seen 5m19.623021587s ago
[TOXD7] 2015/05/31 18:11:18.528150 discover.go:423: DEBUG: discover: Removing cached address 192.168.1.102:22000 - seen 5m19.620810884s ago
[TOXD7] 2015/05/31 18:11:18.528520 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:11:18.528186798 +0200 CEST}]
[TOXD7] 2015/05/31 18:11:18.528905 verbose.go:42: VERBOSE: Discovered device JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 at [[fe80::fae0:79ff:fe79:55a%enp3s0]:22000]
[TOXD7] 2015/05/31 18:11:18.529434 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:11:18.529925 discover.go:350: DEBUG: discover: Received local announcement from 192.168.1.102:21025 for JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5
[TOXD7] 2015/05/31 18:11:18.530329 discover.go:400: DEBUG: discover: Caching JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 addresses: [{[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 2015-05-31 18:11:18.528186798 +0200 CEST} {192.168.1.102:22000 2015-05-31 18:11:18.529972188 +0200 CEST}]
[TOXD7] 2015/05/31 18:11:18.530635 verbose.go:42: VERBOSE: Discovered device JA6ZOTQ-DSV6UXA-VGJQQ3Z-XSRVN7D-HKQJDOO-F5OB4RI-UDB262H-ENHALA5 at [[fe80::fae0:79ff:fe79:55a%enp3s0]:22000 192.168.1.102:22000]
[TOXD7] 2015/05/31 18:11:48.175652 connections.go:296: DEBUG: dial tcp [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000: connection timed out
[TOXD7] 2015/05/31 18:12:04.867575 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:12:04.868164 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:12:48.176232 discover.go:423: DEBUG: discover: Removing cached address 192.168.1.3:22000 - seen 8m7.578365332s ago
[TOXD7] 2015/05/31 18:12:48.176325 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 7m37.670797333s ago
[TOXD7] 2015/05/31 18:13:06.724084 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:13:06.724751 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:13:48.176935 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 8m37.671319163s ago
[TOXD7] 2015/05/31 18:13:48.177023 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 8m37.671496209s ago
[TOXD7] 2015/05/31 18:14:07.561413 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:14:07.562394 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:14:48.177629 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 9m37.672087889s ago
[TOXD7] 2015/05/31 18:14:48.177723 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 9m37.67219596s ago
[TOXD7] 2015/05/31 18:14:56.586454 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:14:56.587117 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:15:44.979145 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:15:44.979805 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:15:48.178377 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 10m37.672767092s ago
[TOXD7] 2015/05/31 18:15:48.178455 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 10m37.672927411s ago
[TOXD7] 2015/05/31 18:16:30.095873 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:16:30.096558 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:16:48.179039 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 11m37.673497809s ago
[TOXD7] 2015/05/31 18:16:48.179126 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 11m37.673599244s ago
[TOXD7] 2015/05/31 18:17:15.821761 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:17:15.822762 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:17:48.179780 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 12m37.674161669s ago
[TOXD7] 2015/05/31 18:17:48.179862 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 12m37.674335079s ago
[TOXD7] 2015/05/31 18:18:17.255608 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:18:17.256193 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:18:48.180425 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 13m37.674880144s ago
[TOXD7] 2015/05/31 18:18:48.180514 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 13m37.674986703s ago
[TOXD7] 2015/05/31 18:19:19.959091 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:19:19.959760 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:19:48.181085 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 14m37.675486325s ago
[TOXD7] 2015/05/31 18:19:48.181169 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 14m37.675641627s ago
[TOXD7] 2015/05/31 18:20:24.062416 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:20:24.063091 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:20:48.181716 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 15m37.676174049s ago
[TOXD7] 2015/05/31 18:20:48.181804 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 15m37.676276888s ago
[TOXD7] 2015/05/31 18:21:21.412916 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:21:21.413581 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:21:48.182443 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 16m37.676835656s ago
[TOXD7] 2015/05/31 18:21:48.182526 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 16m37.676998926s ago
[TOXD7] 2015/05/31 18:22:02.749299 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:22:02.749563 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:22:30.460607 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:22:30.461270 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:22:48.183352 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 17m37.677810657s ago
[TOXD7] 2015/05/31 18:22:48.183446 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 17m37.677919064s ago
[TOXD7] 2015/05/31 18:23:38.491297 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:23:38.492288 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:23:48.184064 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 18m37.678464638s ago
[TOXD7] 2015/05/31 18:23:48.184146 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 18m37.678619005s ago
[TOXD7] 2015/05/31 18:24:30.441563 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:24:30.442284 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:24:48.184723 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 19m37.679176893s ago
[TOXD7] 2015/05/31 18:24:48.184811 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 19m37.679284064s ago
[TOXD7] 2015/05/31 18:25:40.054928 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:25:40.055849 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:25:48.185526 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 20m37.67991547s ago
[TOXD7] 2015/05/31 18:25:48.185608 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 20m37.680081116s ago
[TOXD7] 2015/05/31 18:26:48.186169 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 21m37.680628128s ago
[TOXD7] 2015/05/31 18:26:48.186263 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 21m37.680735658s ago
[TOXD7] 2015/05/31 18:26:54.207300 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:26:54.207972 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:27:48.186896 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 22m37.681278181s ago
[TOXD7] 2015/05/31 18:27:48.186985 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 22m37.681457615s ago
[TOXD7] 2015/05/31 18:27:48.306117 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:27:48.306767 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:28:48.187480 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 23m37.681935063s ago
[TOXD7] 2015/05/31 18:28:48.187573 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 23m37.682045918s ago
[TOXD7] 2015/05/31 18:29:00.952247 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:29:00.952936 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:29:48.188171 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 24m37.682553166s ago
[TOXD7] 2015/05/31 18:29:48.188258 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 24m37.682730632s ago
[TOXD7] 2015/05/31 18:30:02.719606 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:30:02.720242 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:30:32.917693 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:30:37.693956 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:30:48.188821 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 25m37.683279878s ago
[TOXD7] 2015/05/31 18:30:48.188909 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 25m37.683381853s ago
[TOXD7] 2015/05/31 18:30:59.708022 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:30:59.709038 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:31:47.949574 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:31:47.950111 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:31:48.189626 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 26m37.684018193s ago
[TOXD7] 2015/05/31 18:31:48.189704 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 26m37.684176843s ago
[TOXD7] 2015/05/31 18:32:39.627092 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:32:39.627757 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:32:48.190241 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 27m37.6846874s ago
[TOXD7] 2015/05/31 18:32:48.190356 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 27m37.684829311s ago
[TOXD7] 2015/05/31 18:33:26.275733 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:33:26.276392 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:33:48.190890 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 28m37.685291219s ago
[TOXD7] 2015/05/31 18:33:48.190973 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 28m37.685445622s ago
[TOXD7] 2015/05/31 18:34:18.018583 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:34:18.019204 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:34:48.191519 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 29m37.6859774s ago
[TOXD7] 2015/05/31 18:34:48.191607 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 29m37.686079591s ago
[TOXD7] 2015/05/31 18:35:09.267374 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:35:09.268227 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:35:48.192184 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 30m37.686565065s ago
[TOXD7] 2015/05/31 18:35:48.192266 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 30m37.686738536s ago
[TOXD7] 2015/05/31 18:36:13.634380 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:36:13.635047 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:36:48.192802 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 31m37.687248096s ago
[TOXD7] 2015/05/31 18:36:48.192893 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 31m37.687366103s ago
[TOXD7] 2015/05/31 18:37:10.429984 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:37:10.430647 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:37:48.193448 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 32m37.687830469s ago
[TOXD7] 2015/05/31 18:37:48.193536 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 32m37.688008691s ago
[TOXD7] 2015/05/31 18:38:24.878855 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:38:24.879404 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:38:48.194085 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 33m37.68853137s ago
[TOXD7] 2015/05/31 18:38:48.194172 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 33m37.688645393s ago
[TOXD7] 2015/05/31 18:39:11.905033 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:39:11.905842 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:39:48.194733 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 34m37.689115185s ago
[TOXD7] 2015/05/31 18:39:48.194818 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 34m37.689291199s ago
[TOXD7] 2015/05/31 18:40:25.026362 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:40:25.026998 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:40:48.195337 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 35m37.689794802s ago
[TOXD7] 2015/05/31 18:40:48.195424 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 35m37.689896801s ago
[TOXD7] 2015/05/31 18:41:30.413738 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:41:30.414464 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:41:48.195995 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 36m37.690385697s ago
[TOXD7] 2015/05/31 18:41:48.196078 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 36m37.690550515s ago
[TOXD7] 2015/05/31 18:42:04.851182 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:42:04.851442 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:42:31.367732 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:42:31.368525 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:42:48.196593 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 37m37.691049162s ago
[TOXD7] 2015/05/31 18:42:48.196687 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 37m37.691159669s ago
[TOXD7] 2015/05/31 18:43:23.816454 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:43:23.817032 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:43:48.197259 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 38m37.691654835s ago
[TOXD7] 2015/05/31 18:43:48.197341 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 38m37.69181333s ago
[TOXD7] 2015/05/31 18:44:37.558476 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:44:37.559126 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:44:48.197865 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 39m37.69231136s ago
[TOXD7] 2015/05/31 18:44:48.197958 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 39m37.692431083s ago
[TOXD7] 2015/05/31 18:45:48.198541 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 40m37.692923648s ago
[TOXD7] 2015/05/31 18:45:48.198629 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 40m37.693101594s ago
[TOXD7] 2015/05/31 18:45:49.159395 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:45:49.160049 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:46:43.489407 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:46:43.490038 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:46:48.199118 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 41m37.693576365s ago
[TOXD7] 2015/05/31 18:46:48.199200 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 41m37.693673516s ago
[TOXD7] 2015/05/31 18:47:48.199769 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 42m37.694150398s ago
[TOXD7] 2015/05/31 18:47:48.199855 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 42m37.694328536s ago
[TOXD7] 2015/05/31 18:47:48.543183 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:47:48.543823 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:48:48.200385 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 43m37.694831102s ago
[TOXD7] 2015/05/31 18:48:48.200480 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 43m37.694952649s ago
[TOXD7] 2015/05/31 18:49:03.357554 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:49:03.358239 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:49:48.201058 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 44m37.695439747s ago
[TOXD7] 2015/05/31 18:49:48.201147 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 44m37.695619661s ago
[TOXD7] 2015/05/31 18:50:10.690944 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 18:50:10.691201 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 18:50:18.292116 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:50:18.292772 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:50:48.201660 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 45m37.69610587s ago
[TOXD7] 2015/05/31 18:50:48.201782 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 45m37.696254297s ago
[TOXD7] 2015/05/31 18:51:31.405927 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:51:31.406595 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:51:48.202397 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 46m37.696788925s ago
[TOXD7] 2015/05/31 18:51:48.202481 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 46m37.69695318s ago
[TOXD7] 2015/05/31 18:52:19.665371 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:52:19.666070 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:52:48.202942 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 47m37.697396151s ago
[TOXD7] 2015/05/31 18:52:48.203030 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 47m37.697502638s ago
[TOXD7] 2015/05/31 18:53:07.675593 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:53:07.676256 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:53:48.203610 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 48m37.697992828s ago
[TOXD7] 2015/05/31 18:53:48.203697 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 48m37.698169683s ago
[TOXD7] 2015/05/31 18:53:56.399491 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:53:56.400003 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:54:48.204176 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 49m37.698622186s ago
[TOXD7] 2015/05/31 18:54:48.204273 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 49m37.698745953s ago
[TOXD7] 2015/05/31 18:55:06.402071 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:55:06.402749 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:55:48.204923 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 50m37.699304828s ago
[TOXD7] 2015/05/31 18:55:48.205048 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 50m37.699520202s ago
[TOXD7] 2015/05/31 18:56:06.782503 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:56:06.783161 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:56:48.205545 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 51m37.700003494s ago
[TOXD7] 2015/05/31 18:56:48.205638 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 51m37.700110773s ago
[TOXD7] 2015/05/31 18:57:11.791633 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:57:11.792455 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:57:48.206181 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 52m37.700563568s ago
[TOXD7] 2015/05/31 18:57:48.206269 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 52m37.700741574s ago
[TOXD7] 2015/05/31 18:58:01.095211 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:58:01.095773 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:58:48.206708 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 53m37.701166535s ago
[TOXD7] 2015/05/31 18:58:48.206801 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 53m37.701273802s ago
[TOXD7] 2015/05/31 18:58:56.402148 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:58:56.402808 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:59:43.868152 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 18:59:43.868653 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 18:59:48.207335 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 54m37.70172478s ago
[TOXD7] 2015/05/31 18:59:48.207417 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 54m37.701890319s ago
[TOXD7] 2015/05/31 19:00:46.079950 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:00:46.080625 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:00:48.207893 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 55m37.702350962s ago
[TOXD7] 2015/05/31 19:00:48.207975 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 55m37.702447933s ago
[TOXD7] 2015/05/31 19:01:48.208531 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 56m37.70291198s ago
[TOXD7] 2015/05/31 19:01:48.208620 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 56m37.703092398s ago
[TOXD7] 2015/05/31 19:01:51.644548 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:01:51.645242 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:02:39.914209 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:02:39.914878 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:02:48.209082 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 57m37.703536475s ago
[TOXD7] 2015/05/31 19:02:48.209173 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 57m37.70364601s ago
[TOXD7] 2015/05/31 19:03:31.986055 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:03:31.986724 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:03:40.947291 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 19:03:40.955004 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 19:03:48.209662 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 58m37.704051682s ago
[TOXD7] 2015/05/31 19:03:48.209745 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 58m37.704217977s ago
[TOXD7] 2015/05/31 19:04:26.691087 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:04:26.691909 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:04:48.210230 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 59m37.704688032s ago
[TOXD7] 2015/05/31 19:04:48.210345 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 59m37.704818255s ago
[TOXD7] 2015/05/31 19:05:21.550846 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:05:21.551510 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:05:48.210940 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h0m37.705329923s ago
[TOXD7] 2015/05/31 19:05:48.211024 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h0m37.705496565s ago
[TOXD7] 2015/05/31 19:06:08.914740 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:06:08.915456 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:06:48.211561 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h1m37.706015645s ago
[TOXD7] 2015/05/31 19:06:48.211684 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h1m37.706156535s ago
[TOXD7] 2015/05/31 19:06:56.519290 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:06:56.519999 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:07:48.212293 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h2m37.706675029s ago
[TOXD7] 2015/05/31 19:07:48.212380 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h2m37.706853011s ago
[TOXD7] 2015/05/31 19:07:55.502824 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:07:55.503482 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:08:48.212994 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h3m37.707438854s ago
[TOXD7] 2015/05/31 19:08:48.213087 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h3m37.707560017s ago
[TOXD7] 2015/05/31 19:09:03.538692 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:09:03.539434 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:09:48.213679 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h4m37.708059731s ago
[TOXD7] 2015/05/31 19:09:48.213768 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h4m37.708240845s ago
[TOXD7] 2015/05/31 19:10:11.668794 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:10:11.669448 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:10:48.214418 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h5m37.708876287s ago
[TOXD7] 2015/05/31 19:10:48.214511 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h5m37.708983734s ago
[TOXD7] 2015/05/31 19:11:09.805931 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:11:09.806524 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:11:48.215211 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h6m37.709591689s ago
[TOXD7] 2015/05/31 19:11:48.215301 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h6m37.709773487s ago
[TOXD7] 2015/05/31 19:12:19.367661 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:12:19.368343 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:12:48.215796 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h7m37.710241931s ago
[TOXD7] 2015/05/31 19:12:48.215912 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h7m37.710384837s ago
[TOXD7] 2015/05/31 19:13:27.702585 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 19:13:27.708750 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 19:13:29.242363 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:13:29.243017 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:13:48.216441 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h8m37.710831979s ago
[TOXD7] 2015/05/31 19:13:48.216525 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h8m37.710998154s ago
[TOXD7] 2015/05/31 19:14:27.267380 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:14:27.268047 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:14:48.217041 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h9m37.71149857s ago
[TOXD7] 2015/05/31 19:14:48.217127 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h9m37.711599597s ago
[TOXD7] 2015/05/31 19:15:18.183983 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:15:18.184644 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:15:48.217641 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h10m37.712041876s ago
[TOXD7] 2015/05/31 19:15:48.217723 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h10m37.712195847s ago
[TOXD7] 2015/05/31 19:16:28.964558 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:16:28.965278 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:16:48.218265 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h11m37.712723703s ago
[TOXD7] 2015/05/31 19:16:48.218599 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h11m37.713071652s ago
[TOXD7] 2015/05/31 19:17:40.697050 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:17:40.697715 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:17:48.219111 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h12m37.713501764s ago
[TOXD7] 2015/05/31 19:17:48.219195 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h12m37.713667698s ago
[TOXD7] 2015/05/31 19:18:29.907568 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:18:29.908570 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:18:48.219689 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h13m37.714146883s ago
[TOXD7] 2015/05/31 19:18:48.219780 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h13m37.714253046s ago
[TOXD7] 2015/05/31 19:19:14.935919 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:19:14.936490 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:19:48.220320 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h14m37.714701701s ago
[TOXD7] 2015/05/31 19:19:48.220402 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h14m37.714874715s ago
[TOXD7] 2015/05/31 19:20:27.028517 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:20:27.029113 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:20:48.220888 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h15m37.715338868s ago
[TOXD7] 2015/05/31 19:20:48.221004 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h15m37.715476807s ago
[TOXD7] 2015/05/31 19:21:37.690129 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:21:37.690771 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:21:48.221489 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h16m37.715891208s ago
[TOXD7] 2015/05/31 19:21:48.221604 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h16m37.716076366s ago
[TOXD7] 2015/05/31 19:22:47.881665 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:22:47.882275 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:22:48.222021 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h17m37.71647932s ago
[TOXD7] 2015/05/31 19:22:48.222103 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h17m37.716576327s ago
[TOXD7] 2015/05/31 19:23:41.141828 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:23:41.142493 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:23:48.222600 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h18m37.717000612s ago
[TOXD7] 2015/05/31 19:23:48.222682 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h18m37.717155147s ago
[TOXD7] 2015/05/31 19:24:36.093302 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 19:24:36.096263 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 19:24:44.949369 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:24:44.950125 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:24:48.223192 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h19m37.717637668s ago
[TOXD7] 2015/05/31 19:24:48.223275 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h19m37.717747167s ago
[TOXD7] 2015/05/31 19:25:48.223751 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h20m37.718134115s ago
[TOXD7] 2015/05/31 19:25:48.223838 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h20m37.718310886s ago
[TOXD7] 2015/05/31 19:25:56.001056 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:25:56.001741 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:26:47.544200 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:26:47.544927 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:26:48.224295 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h21m37.718750292s ago
[TOXD7] 2015/05/31 19:26:48.224379 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h21m37.718851847s ago
[TOXD7] 2015/05/31 19:27:48.224981 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h22m37.719363488s ago
[TOXD7] 2015/05/31 19:27:48.225068 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h22m37.719540606s ago
[TOXD7] 2015/05/31 19:28:00.502537 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:28:00.503120 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:28:48.225502 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h23m37.719947397s ago
[TOXD7] 2015/05/31 19:28:48.225621 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h23m37.720093399s ago
[TOXD7] 2015/05/31 19:29:05.257139 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:29:05.257804 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:29:48.226079 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h24m37.720460708s ago
[TOXD7] 2015/05/31 19:29:48.226164 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h24m37.720636327s ago
[TOXD7] 2015/05/31 19:29:54.834107 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:29:54.834747 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:30:48.226561 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h25m37.721019233s ago
[TOXD7] 2015/05/31 19:30:48.226654 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h25m37.721127064s ago
[TOXD7] 2015/05/31 19:30:50.997443 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:30:50.998461 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:31:40.195237 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:31:40.195888 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:31:48.227210 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h26m37.721601422s ago
[TOXD7] 2015/05/31 19:31:48.227296 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h26m37.721768449s ago
[TOXD7] 2015/05/31 19:32:26.052240 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:32:26.053067 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:32:48.227792 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h27m37.722246553s ago
[TOXD7] 2015/05/31 19:32:48.227886 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h27m37.722358452s ago
[TOXD7] 2015/05/31 19:33:40.023571 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:33:40.024229 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:33:48.228412 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h28m37.722803207s ago
[TOXD7] 2015/05/31 19:33:48.228497 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h28m37.722969741s ago
[TOXD7] 2015/05/31 19:34:40.655923 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:34:40.656583 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:34:48.228951 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h29m37.723396513s ago
[TOXD7] 2015/05/31 19:34:48.229041 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h29m37.723514076s ago
[TOXD7] 2015/05/31 19:35:33.745585 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:35:33.746276 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:35:48.229495 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h30m37.723886771s ago
[TOXD7] 2015/05/31 19:35:48.229583 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h30m37.724055454s ago
[TOXD7] 2015/05/31 19:36:43.928976 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:36:43.929749 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:36:48.230132 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h31m37.72458625s ago
[TOXD7] 2015/05/31 19:36:48.230243 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h31m37.724715201s ago
[TOXD7] 2015/05/31 19:37:47.974318 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:37:47.975068 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:37:48.230877 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h32m37.72527769s ago
[TOXD7] 2015/05/31 19:37:48.230953 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h32m37.725426513s ago
[TOXD7] 2015/05/31 19:38:25.054356 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 19:38:25.054488 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 19:38:47.308701 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 19:38:47.310613 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 19:38:47.310736 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.3:21025
[TOXD7] 2015/05/31 19:38:47.311354 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 19:38:47.312590 beacon.go:30: DEBUG: recv 56 bytes from [fe80::7a24:afff:fe8a:ca08%enp3s0]:21026
[TOXD7] 2015/05/31 19:38:47.317162 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.102:21025
[TOXD7] 2015/05/31 19:38:47.318927 beacon.go:30: DEBUG: recv 56 bytes from [fe80::fae0:79ff:fe79:55a%enp3s0]:21026
[TOXD7] 2015/05/31 19:38:48.231512 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h33m37.725965982s ago
[TOXD7] 2015/05/31 19:38:48.231595 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h33m37.726067933s ago
[TOXD7] 2015/05/31 19:38:50.386218 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:38:50.386888 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:39:48.232104 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h34m37.726486829s ago
[TOXD7] 2015/05/31 19:39:48.232192 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h34m37.726665399s ago
[TOXD7] 2015/05/31 19:39:48.925788 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:39:48.926437 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:40:41.609161 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:40:41.609850 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:40:48.232612 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h35m37.727069635s ago
[TOXD7] 2015/05/31 19:40:48.232702 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h35m37.727174898s ago
[TOXD7] 2015/05/31 19:41:38.663235 verbose.go:42: VERBOSE: Folder "tst" is now scanning
[TOXD7] 2015/05/31 19:41:38.663904 verbose.go:42: VERBOSE: Folder "tst" is now idle
[TOXD7] 2015/05/31 19:41:48.233323 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h36m37.727713937s ago
[TOXD7] 2015/05/31 19:41:48.233408 discover.go:423: DEBUG: discover: Removing cached address [fe80::7a24:afff:fe8a:ca08%enp3s0]:22000 - seen 1h36m37.727880879s ago
SIGQUIT: quit
PC=0x47afe1

goroutine 0 [idle]:
runtime.futex(0xdcc1d8, 0x0, 0x0, 0x0, 0x0, 0xdcb640, 0x100000000, 0x44820f, 0x44842e, 0xdcc1d8, ...)
	/usr/lib/go/src/runtime/sys_linux_amd64.s:277 +0x21
runtime.futexsleep(0xdcc1d8, 0x0, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/os_linux.c:49 +0x47
runtime.notesleep(0xdcc1d8)
	/usr/lib/go/src/runtime/lock_futex.go:145 +0xae
stopm()
	/usr/lib/go/src/runtime/proc.c:1178 +0x119
findrunnable(0xc208013200)
	/usr/lib/go/src/runtime/proc.c:1487 +0x562
schedule()
	/usr/lib/go/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc2089d6120)
	/usr/lib/go/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x46e214)
	/usr/lib/go/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [chan receive, 108 minutes]:
main.syncthingMain()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:706 +0x3175
main.main()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc

goroutine 5 [syscall, 108 minutes]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 8 [select, 108 minutes]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080e8000)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 10 [select]:
main.(*verboseSvc).Serve(0xc20802af20)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/verbose.go:38 +0x2b8
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 11 [chan receive, 108 minutes]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0xc2080c0000)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/config/wrapper.go:84 +0x75
created by github.com/syncthing/syncthing/internal/config.Wrap
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/config/wrapper.go:59 +0x28d

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc20807e0e0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 13 [select, 108 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc20811c2c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc20811c2c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 15 [select, 108 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc20811c2c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 16 [select, 108 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc20811c2c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 17 [select, 108 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc20811c2c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 18 [select, 97 minutes]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc20803af00)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:49 +0x8f2
created by github.com/syncthing/syncthing/internal/model.NewModel
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/model/model.go:132 +0xafa

goroutine 19 [IO wait, 108 minutes]:
net.(*pollDesc).Wait(0xc208390c30, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208390c30, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208390bd0, 0x0, 0x7f824955ce00, 0xc20843e090)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c040, 0xc20803a7c0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c040, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:244 +0x4c
main.(*DowngradingListener).Accept(0xc208397ca0, 0x0, 0x0, 0x0, 0x0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:99 +0x85
net/http.(*Server).Serve(0xc208394060, 0x7f8249575618, 0xc208397ca0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1728 +0x92
main.(*apiSvc).Serve(0xc208080600)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:215 +0x190a
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 20 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc208397d20, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/events/events.go:183 +0x369
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802f3b0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/events/events.go:220 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/events/events.go:214 +0x292

goroutine 21 [select, 47 minutes]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0xc2081360f0, 0x68c61714000)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:161 +0x1c9
created by github.com/syncthing/syncthing/internal/ignore.New
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0x170

goroutine 22 [IO wait, 3 minutes]:
net.(*pollDesc).Wait(0xc208010bc0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010bc0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208010b60, 0xc20831e000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f824955ce00, 0xc208480298)
	/usr/lib/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc2083d4090, 0xc20831e000, 0x10000, 0x10000, 0xc2080dc380, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc2083d4090, 0xc20831e000, 0x10000, 0x10000, 0x38, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:82 +0x12e
github.com/syncthing/syncthing/internal/beacon.genericReader(0xc2083d4090, 0xc20812a6c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24 +0xa6
created by github.com/syncthing/syncthing/internal/beacon.NewBroadcast
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:30 +0x1c2

goroutine 23 [chan receive, 97 minutes]:
github.com/syncthing/syncthing/internal/beacon.(*Broadcast).writer(0xc208128620)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:46 +0x87
created by github.com/syncthing/syncthing/internal/beacon.NewBroadcast
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:31 +0x1dc

goroutine 24 [chan send, 89 minutes]:
github.com/syncthing/syncthing/internal/discover.(*Discoverer).recvAnnouncements(0xc20807e2a0, 0x7f8249575860, 0xc208128620)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/discover/discover.go:360 +0x3d8
created by github.com/syncthing/syncthing/internal/discover.(*Discoverer).startLocalIPv4Broadcasts
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/discover/discover.go:99 +0x44f

goroutine 25 [IO wait, 3 minutes]:
net.(*pollDesc).Wait(0xc208010c30, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010c30, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208010bd0, 0xc208372000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f824955ce00, 0xc2084802e0)
	/usr/lib/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc2083d4098, 0xc208372000, 0x10000, 0x10000, 0xc2080dc400, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc2083d4098, 0xc208372000, 0x10000, 0x10000, 0x38, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:82 +0x12e
github.com/syncthing/syncthing/internal/beacon.genericReader(0xc2083d4098, 0xc20812ab40)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24 +0xa6
created by github.com/syncthing/syncthing/internal/beacon.NewMulticast
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:40 +0x2cf

goroutine 26 [syscall, 98 minutes]:
syscall.Syscall6(0x2d, 0x10, 0xc208076000, 0x1000, 0x0, 0xc2083326c0, 0xc2083326bc, 0x1000, 0x879101, 0xc208076000)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.recvfrom(0x10, 0xc208076000, 0x1000, 0x1000, 0x0, 0xc2083326c0, 0xc2083326bc, 0x11, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1906 +0x9b
syscall.Recvfrom(0x10, 0xc208076000, 0x1000, 0x1000, 0x0, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/syscall_unix.go:220 +0xbf
syscall.NetlinkRIB(0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/netlink_linux.go:71 +0x3dd
net.interfaceTable(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/interface_linux.go:17 +0x86
net.InterfaceByName(0xc20802aee2, 0x6, 0x7f824954b960, 0x0, 0x0)
	/usr/lib/go/src/net/interface.go:116 +0x87
net.zoneToInt(0xc20802aee2, 0x6, 0x10)
	/usr/lib/go/src/net/ipsock.go:313 +0x46
net.ipToSockaddr(0xa, 0xc20802aed0, 0x10, 0x10, 0x5222, 0xc20802aee2, 0x6, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/net/ipsock_posix.go:173 +0x45e
net.(*UDPAddr).sockaddr(0xc208126720, 0xa, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:45 +0xbd
net.(*UDPConn).WriteToUDP(0xc2083d4098, 0xc2080c2580, 0x38, 0x80, 0xc208126720, 0x866c80, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:123 +0x446
net.(*UDPConn).WriteTo(0xc2083d4098, 0xc2080c2580, 0x38, 0x80, 0x7f8249575830, 0xc208126720, 0x38, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:139 +0x2e0
github.com/syncthing/syncthing/internal/beacon.(*Multicast).writer(0xc2081266c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:59 +0x1b6
created by github.com/syncthing/syncthing/internal/beacon.NewMulticast
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:41 +0x2e9

goroutine 27 [chan send, 89 minutes]:
github.com/syncthing/syncthing/internal/discover.(*Discoverer).recvAnnouncements(0xc20807e2a0, 0x7f82495758e0, 0xc2081266c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/discover/discover.go:360 +0x3d8
created by github.com/syncthing/syncthing/internal/discover.(*Discoverer).startLocalIPv6Multicasts
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/discover/discover.go:128 +0x82b

goroutine 28 [chan send, 97 minutes]:
github.com/syncthing/syncthing/internal/beacon.(*Multicast).Send(0xc2081266c0, 0xc2080c2580, 0x38, 0x80)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:47 +0x60
github.com/syncthing/syncthing/internal/discover.(*Discoverer).sendLocalAnnouncements(0xc20807e2a0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/discover/discover.go:326 +0x1f0
created by github.com/syncthing/syncthing/internal/discover.(*Discoverer).StartLocal
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/discover/discover.go:85 +0x268

goroutine 29 [select, 108 minutes]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080e8180)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 30 [sleep]:
main.(*connectionSvc).connect(0xc2081363c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:316 +0x184
main.*connectionSvc.(main.connect)·fm()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:80 +0x27
main.serviceFunc.Serve(0xc20802af70)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 31 [IO wait, 98 minutes]:
net.(*pollDesc).Wait(0xc208011250, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011250, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080111f0, 0x0, 0x7f824955ce00, 0xc208447430)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2083d4138, 0x8669e0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2083d4138, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:244 +0x4c
main.(*connectionSvc).listen(0xc2081363c0, 0xc2080e21a0, 0xd)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:219 +0x4d6
main.func·001()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:84 +0x37
main.serviceFunc.Serve(0xc2081288e0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 32 [chan receive, 98 minutes]:
main.(*connectionSvc).handle(0xc2081363c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:95 +0x7e
main.*connectionSvc.(main.handle)·fm()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:88 +0x27
main.serviceFunc.Serve(0xc20802afa0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 49 [select]:
github.com/syncthing/syncthing/internal/model.(*rwFolder).Serve(0xc208074d00)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:157 +0x1e27
created by github.com/syncthing/syncthing/internal/model.(*Model).StartFolderRW
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/model/model.go:173 +0x570

goroutine 50 [sleep]:
main.standbyMonitor()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:963 +0x64
created by main.syncthingMain
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:688 +0x30a1

goroutine 52 [sleep]:
main.generatePingEvents()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:844 +0x2d
created by main.syncthingMain
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:702 +0x3139

goroutine 65 [select, 108 minutes]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080e80c0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 66 [select]:
main.(*folderSummarySvc).listenForUpdates(0xc2080da420)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:67 +0x5c6
main.*folderSummarySvc.(main.listenForUpdates)·fm()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:47 +0x27
main.serviceFunc.Serve(0xc2080e2380)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 67 [select]:
main.(*folderSummarySvc).calculateSummaries(0xc2080da420)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:115 +0x2e4
main.*folderSummarySvc.(main.calculateSummaries)·fm()
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:48 +0x27
main.serviceFunc.Serve(0xc2080e2390)
	/build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/build/syncthing/src/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 248 [sleep]:
github.com/syncthing/syncthing/internal/model.sendIndexes(0x7f8249576f80, 0xc2084474c0, 0xc2080e30c8, 0x3, 0xc2081100c0, 0xc2081360f0)
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/model/model.go:1025 +0x33c
created by github.com/syncthing/syncthing/internal/model.(*Model).AddConnection
	/build/syncthing/src/src/github.com/syncthing/syncthing/internal/model/model.go:972 +0x5ae

rax     0xca
rbx     0xdcc1d8
rcx     0x47afe3
rdx     0x0
rdi     0xdcc1d8
rsi     0x0
rbp     0x1
rsp     0x7ffc29ea3248
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x0
r13     0x1
r14     0x12
r15     0x13
rip     0x47afe1
rflags  0x286
cs      0x33
fs      0x0
gs      0x0
```

### PR DESCRIPTION
**Pull request by calmh**
My theory is that some error condition on the socket results in it
blocking for writes, which maybe also blocks reads... This separates the
two into separate services with their own socket, with restarts and
retries as appropriates on write timeouts and read/write errors. It
should be more robust, hopefully, but I have a hard time testing the
actual error conditions...

### CODE REVIEW

File: internal/beacon/broadcast.go [hunk 1]
```diff
@@ -42,13 +62,37 @@ func (b *Broadcast) Recv() ([]byte, net.Addr) {
...
+func (w *broadcastWriter) Serve() {
+	if debug {
+		l.Debugln(w, "starting")
+		defer l.Debugln(w, "stopping")
+	}
 
+	var err error
+	w.conn, err = net.ListenUDP("udp4", nil)
+	if err != nil {
+		if !w.failed {
```
Comment (calmh) [inline internal/beacon/broadcast.go]: This whole dance with `r.failed` and `w.failed` is to avoid logging each time we fail to try something. Instead, only the first time or after we've actually succeeded at least once.

File: internal/beacon/broadcast.go [hunk 2]
```diff
@@ -42,13 +62,37 @@ func (b *Broadcast) Recv() ([]byte, net.Addr) {
...
+			l.Warnln("Local discovery (broadcast writer):", err)
+			w.failed = true
+		}
+		return
+	}
```
Comment (AudriusButkevicius) [inline internal/beacon/broadcast.go]: Can be reduced to `if err != nil && !w.failed`

File: internal/discover/discover.go [hunk 3]
```diff
@@ -86,17 +86,10 @@ func (d *Discoverer) StartLocal(localPort int, localMCAddr string) {
 }
 
 func (d *Discoverer) startLocalIPv4Broadcasts(localPort int) {
-	bb, err := beacon.NewBroadcast(localPort)
-	if err != nil {
-		if debug {
-			l.Debugln("discover: Start local v4:", err)
-		}
-		l.Infoln("Local discovery over IPv4 unavailable")
```
Comment (AudriusButkevicius) [inline internal/discover/discover.go]: We loose this log line, which is a bit sad.

Comment (calmh) [inline internal/discover/discover.go]: That's fixable... Hang on.

Comment (calmh) [inline internal/discover/discover.go]: Added that back as the Warnln for when opening/binding the socket fails. The the most common case that would be fatal... I can't think of a reason that both opening the listening socket and a random-port sending socket would fail, but if it does we get a duplicate... No big deal I think.

Comment (calmh) [inline internal/discover/discover.go]: There's another log line somewhere that complains about no local discovery at all when both v4 and v6 fails to initialize - that'll never happen in this setup since we'll always add the v4 discovery thing and it'll retry continuously in the background... I think we can sacrifice that, but it should maybe be cleaned up...

Comment (calmh) [inline internal/discover/discover.go]: Well, it could maybe still happen depending on config (local discovery enabled, but the v4 port number set to zero) so I'll leave it in.

**Comment by AudriusButkevicius** [comment]
Looks good to me. Are you happy to merge?

**Comment by calmh** [comment]
Slightly nervous, but what the hell, nobody remembers a coward.
