### PR TITLE
Prevent Discovery from returning Nil IP (fixes #9189)

### LINKED ISSUE #9189: Discovery Returns <Nil> IP
## Does your log mention database corruption?
No

## Include required information
On Discovery Client Announcements, the `X-Forwarded-For`  header may container multiple IP Addresses, for instance when sitting behind multiple proxies.    
The syntax in this case is a string of IP Addresses separated by commas. 
[For reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax)

Currently, Discovery assumes `X-Forwarded-For` is a single IP, which results to a `nil` IP

## Syncthing Version
v1.24.0

## What happens
When a list of IPs is provided in `X-Forwarded-For`, Discovery treats the header value as a string with a single IP; 
[Link to line of code](https://github.com/syncthing/syncthing/blob/main/cmd/stdiscosrv/apisrv.go#L139)
This result to a `nil` IP; i.e. `tcp://<nil>:22000` when `listenAddress = tcp://0.0.0.0:22000 | tcp://:22000`

## What is expected
We should parse `X-Forwarded-For` by splitting the string by commas and taking the originating client IP (the leftmost value)

## Steps to Reproduce
A simple example to replicate this entails running Discovery with HTTP, use Nginx as a reverse proxy and hardcode (as an example) a list of IPs in the `X-Forwarded-For` header.  
    1. Send an Announcement with `tcp://0.0.0.0:<some-port>`
    2. Query the DeviceID
    3. Observe the returned IP Address is `tcp://<nil>:<some-port>`

### PR DESCRIPTION
**Pull request by vapatel2**
### Purpose

Treat X-Forwarded-For as a comma separated string to prevent Nil IP being returned by the Discovery Server
Fixes: [9189](https://github.com/syncthing/syncthing/issues/9189
)
### Testing

Unit Tests implemented

Testing with a Discovery Client can be done as follows:
```
A simple example to replicate this entails running Discovery with HTTP, use Nginx as a reverse proxy and hardcode (as an example) a list of IPs in the X-Forwarded-For header.
1. Send an Announcement with tcp://0.0.0.0:<some-port>
2. Query the DeviceID
3. Observe the returned IP Address is no longer nil; i.e.  `tcp://<nil>:<some-port>`
```

## Authorship
Vishal A. Patel

### CODE REVIEW

File: cmd/stdiscosrv/apisrv.go [hunk 1]
```diff
@@ -136,7 +136,13 @@ func (s *apiSrv) handler(w http.ResponseWriter, req *http.Request) {
 	}
 
 	if s.useHTTP {
-		remoteAddr.IP = net.ParseIP(req.Header.Get("X-Forwarded-For"))
+		// X-Forwarded-For can have multiple client IPs; split using the comma separator
+		forwardIPs := strings.Split(req.Header.Get("X-Forwarded-For"), ",")
```
Comment (calmh) [inline cmd/stdiscosrv/apisrv.go:140]: Could use `strings.Cut` here as we are only interested in the first element in the list

**Review by calmh — COMMENTED** [review]
LGTM

File: cmd/stdiscosrv/apisrv.go (hunk 1 above)
Comment (vapatel2) [reply cmd/stdiscosrv/apisrv.go]: Ah! I didn't know about `strings.Cut()`
Thanks for the tip; I've pushed a new commit to use this.

File: cmd/stdiscosrv/apisrv.go [hunk 2]
```diff
@@ -137,10 +137,10 @@ func (s *apiSrv) handler(w http.ResponseWriter, req *http.Request) {
 
 	if s.useHTTP {
 		// X-Forwarded-For can have multiple client IPs; split using the comma separator
-		forwardIPs := strings.Split(req.Header.Get("X-Forwarded-For"), ",")
-		if len(forwardIPs) > 0 {
-			// get the originating client (left most ip) and parse
-			remoteAddr.IP = net.ParseIP(forwardIPs[0])
+		forwardIP, _, found := strings.Cut(req.Header.Get("X-Forwarded-For"), ",")
+		if found {
```
Comment (calmh) [inline cmd/stdiscosrv/apisrv.go:141]: We should do this even if a comma is not found, no?

Comment (vapatel2) [reply cmd/stdiscosrv/apisrv.go]: You're right, we should.  Otherwise the code ignores the value when only one IP is provided.
Nice catch! 
I've pushed a commit for this

**Review by calmh — APPROVED** [review]
