### PR TITLE
fix(fs): fix directory junction handling (fixes #9775)

### LINKED ISSUE #9775: Junctions as dirs doesn't work anymore
### What happened?

I used to be able to sync the contents of NTFS junction directories. I recently noticed that it doesn't seem to work anymore.

I tried on 2 different machines, one with admin/systemwide install, the other with user install. On the systemwide install I added SyncthingServiceAcct to the perms on the sync'ed folder. The _Junctions as dirs_ option is set. 

Relevant logs below.

Here are some screenshots:
syncthing_main
files
options
perms

### Syncthing version

v1.28.0

### Platform & operating system

Windows 10 Pro x64 

### Browser version

Brave Browser 1.71.114

### Relevant log output

2024-10-18 22:21:00 casefs.go:255 basic c:\aaa\junction Stat . {0xc00013c070} <nil>
2024-10-18 22:21:00 casefs.go:255 basic c:\aaa\junction Stat .stfolder {0xc00013c230} <nil>
2024-10-18 22:21:00 casefs.go:479 basic c:\aaa\junction DirNames . [.stfolder file junctiontotarget] <nil>
2024-10-18 22:21:00 logfs.go:173 basic C:\ProgramData\Syncthing\index-v0.14.0.db Usage . {702322937856 999533756416} <nil>
2024-10-18 22:21:00 log 40 StateChanged map[duration:182.8508201 folder:dayss-x9hqe from:idle to:scan-waiting]
2024-10-18 22:21:00 walker/dayss-x9hqe@0xc0000e76b0 Walk [] Matcher/[]@0xc0002422d0
2024-10-18 22:21:00 log 41 StateChanged map[duration:0.8508201 folder:dayss-x9hqe from:scan-waiting to:scanning]
2024-10-18 22:21:00 walk: path=.
2024-10-18 22:21:00 ancestorDirList: Contains 'junction'
2024-10-18 22:21:00 ancestorDirList: Push 'junction'
2024-10-18 22:21:00 walk: path=.stfolder
2024-10-18 22:21:00 walker/dayss-x9hqe@0xc0000e76b0 ignored (internal): .stfolder
2024-10-18 22:21:00 walk: path=file
2024-10-18 22:21:00 walker/dayss-x9hqe@0xc0000e76b0 checking: File{Name:"file", Sequence:0, Permissions:0644, ModTime:2024-10-18 21:11:45.2540096 +0200 CEST, Version:{[{62S6MDD 1729282860}]}, VersionHash:, Length:7, Deleted:false, Invalid:false, LocalFlags:0x0, NoPermissions:false, BlockSize:131072, NumBlocks:0, BlocksHash:, Platform:{<nil> <nil> <nil> <nil> <nil> <nil>}, InodeChangeTime:1970-01-01 01:00:00 +0100 CET}
2024-10-18 22:21:00 walker/dayss-x9hqe@0xc0000e76b0 unchanged: File{Name:"file", Sequence:1, Permissions:0644, ModTime:2024-10-18 21:11:45.2540096 +0200 CEST, Version:{[{62S6MDD 1729282860}]}, VersionHash:, Length:7, Deleted:false, Invalid:false, LocalFlags:0x0, NoPermissions:false, BlockSize:131072, NumBlocks:1, BlocksHash:d3535c46046caa8f282f78819d9f8616010eacd1d507e952c833a67ada965799, Platform:{<nil> <nil> <nil> <nil> <nil> <nil>}, InodeChangeTime:1970-01-01 01:00:00 +0100 CET}
2024-10-18 22:21:00 walk: path=junctiontotarget
2024-10-18 22:21:00 ancestorDirList: Pop 'junction'
2024-10-18 22:21:00 log 42 StateChanged map[duration:0.8525193 folder:dayss-x9hqe from:scanning to:idle]

### PR DESCRIPTION
**Pull request by rasa**
### Purpose

This fixes #9775. I also improved the comments as they were lacking.

My apologies for introducing this bug. In summary, the bug was
```
mode = mode ^ (ModeSymlink | ModeIrregular)
```
didn't correctly reset those bits. This correctly resets them:
```
mode = mode &^ ModeSymlink &^ ModeIrregular
```
Tested and working in Windows 11 version 10.0.22631.4317. I didn't test in other versions, but I'm sure this is the only issue.

### CODE REVIEW

**Comment by calmh** [comment]
Nice, good catch! Can I suggest the slightly (imho) more readable

```
mode = mode &^ (ModeSymlink | ModeIrregular)
```

**Review by calmh — APPROVED** [review]

File: lib/fs/basicfs_lstat_windows.go [hunk 1]
```diff
@@ -77,10 +77,13 @@ func (fi *dirJunctFileInfo) IsDir() bool {
...
 func init() {
+	// Per https://tip.golang.org/doc/go1.23#minor_library_changes
+	// In go1.22 (and go1.23 when GODEBUG=winsymlink=0) directory junctions
+	// (aka "mount points") always have ModeSymlink set.
 	junctionPointModeMask = os.ModeSymlink
 	if version.Compare(runtime.Version(), "go1.23") >= 0 {
-		// if GODEBUG=winsymlink=0, then we are in g1.22 mode so let's check for
-		// os.ModeSymlink as well, as it can't hurt.
+		// In go1.23 directory junctions (and dedup files) always have
+		// ModeIrregular set (unless GODEBUG=winsymlink=0).
```
Comment (imsodin) [inline lib/fs/basicfs_lstat_windows.go:86]: That contradicts the go changelog (emphasis mine), from https://tip.golang.org/doc/go1.23#minor_library_changes:

> [...] reparse points that are *not* symlinks, Unix sockets, or *dedup* files now always have [ModeIrregular](https://tip.golang.org/pkg/os#ModeIrregular) set. [...]

My understanding of the go changelo gis that dedup files do not have mode irregular set in go 1.23. While the changed comment here says they always have it set.

I am not saying the logic here is wrong, I am still in the process of trying to understand what we do, but the comments are either contradictory or require clarification. And given this is all quite hard to understand/follow, I believe that's necessary to improve.

**Review by imsodin — CHANGES_REQUESTED** [review]

File: lib/fs/basicfs_lstat_windows.go [hunk 2]
```diff
@@ -77,10 +77,13 @@ func (fi *dirJunctFileInfo) IsDir() bool {
 var junctionPointModeMask os.FileMode
 
 func init() {
+	// Per https://tip.golang.org/doc/go1.23#minor_library_changes
+	// In go1.22 (and go1.23 when GODEBUG=winsymlink=0) directory junctions
+	// (aka "mount points") always have ModeSymlink set.
 	junctionPointModeMask = os.ModeSymlink
```
Comment (imsodin) [inline lib/fs/basicfs_lstat_windows.go:83]: Why are we keeping mode symlink in the mask for go 1.23? The linked changelog says "Mount points no longer have [ModeSymlink](https://tip.golang.org/pkg/os#ModeSymlink) set,", so I'd expect the mask be set to only os.ModeIrregular for >= 1.23 and to only os.ModeSymlink on < 1.23.

File: lib/fs/basicfs_lstat_windows.go (hunk 1 above)
Comment (rasa) [reply lib/fs/basicfs_lstat_windows.go]: @imsodin Good catch, fixed in https://github.com/syncthing/syncthing/pull/9786/commits/69f9c95028828fd0c11df73048aaf5230de431d2

File: lib/fs/basicfs_lstat_windows.go (hunk 2 above)
Comment (rasa) [reply lib/fs/basicfs_lstat_windows.go]: @imsodin Agreed, corrected in https://github.com/syncthing/syncthing/pull/9786/commits/69f9c95028828fd0c11df73048aaf5230de431d2

Comment (rasa) [reply lib/fs/basicfs_lstat_windows.go]: @imsodin Because users can set `GODEBUG=winsymlink=0` in their environment, which will cause Syncthing to operate in go1.22 mode (where `ModeSymlink` is set). See https://go.dev/doc/godebug#history

**Review by imsodin — APPROVED** [review]

**Comment by rasa** [comment]
The test failure at
https://github.com/syncthing/syncthing/actions/runs/11534450205/job/32108472429?pr=9786#step:7:3262 :
```
=== RUN   TestCompletionEmptyGlobal
    model_test.go:3765: Expected completion of 95%, got 100
--- FAIL: TestCompletionEmptyGlobal (0.01s)
```
is a false positive.
