### PR TITLE
lib/fs: Remove \\?\ for drive letters when watching (fixes #5578)

### LINKED ISSUE #5578: Filesystem watcher error when watching disk root directory on Windows
External W7 computers as send only, I have a backup server that is receive only. All been fine up until the last update. was on rc2 with no errors

On the remote computers im getting a title of Filesystem Watcher Errors and errors as follows

GetFileInformationByHandle \?\C:: Incorrect function.

on the computers where the software is running and on the network shares…

The network name cannot be found

Although I am able to access the remote folders through explorer. I have also noticed on the sync job rescan section it’s now saying “Failed to setup, retrying”

I have shutdown and restarted Syncthing and get the same issue.

It also seems that the syncs are working so maybe the error is benign / false.

image

image

### PR DESCRIPTION
**Pull request by imsodin**
Predecessor: #5633 reverted in https://github.com/syncthing/syncthing/commit/a04fcfe7494a6e3ede091534597539b77dc05a52 due to https://github.com/syncthing/syncthing/issues/5695

The problem was, that the prefix was removed only on the watched path, but not on the path that events were compared against.

### CODE REVIEW

File: lib/fs/basicfs_watch_test.go [hunk 1]
```diff
@@ -149,6 +149,53 @@ func TestWatchRename(t *testing.T) {
...
+		t.Skip("Windows specific test")
+	}
+
+	outChan := make(chan Event)
+	backendChan := make(chan notify.EventInfo, backendBuffer)
+
+	ctx, cancel := context.WithCancel(context.Background())
+
+	// testFs is Filesystem, but we need BasicFilesystem here
+	root := `D:\`
```
Comment (AudriusButkevicius) [inline lib/fs/basicfs_watch_test.go]: Why not c:\ which should always be there?

Comment (calmh) [reply lib/fs/basicfs_watch_test.go]: I assumed this does not matter as there is no d: on the build server

Comment (imsodin) [reply lib/fs/basicfs_watch_test.go]: It doesn't, there is no real filesystem access, the watching is faked, but c: would probably have been more "normal", not sure exactly what my thoughts on this choice were.
