### PR TITLE
lib/db: Handle indirection error repairing sequences (fixes #7026)

### LINKED ISSUE #7026: panic: key not found when repairing DB
https://sentry.syncthing.net/share/issue/b29b701f48f64fcf8ce06ef60e3cc765/

```
github.com/syncthing/syncthing/lib/db/lowlevel.go in func1 at line 818
github.com/syncthing/syncthing/lib/db/lowlevel.go in getMetaAndCheck at line 833
github.com/syncthing/syncthing/lib/db/lowlevel.go in loadMetadataTracker at line 856
github.com/syncthing/syncthing/lib/db/set.go in NewFileSet at line 46
```

We can't know for sure where the error is occuring, as the panic happens in defer, but given it happens on 1.10.0 only it's most likely the code added in https://github.com/syncthing/syncthing/pull/6950. The only places I see where a `key not found` could occur are the `Delete` calls. However the deleted keys are keys we just got by iterating, so they should exist.

The github-sentry integration seems to be broken

### PR DESCRIPTION
**Pull request by imsodin**
#7026 is about unspecific `key not found` errors on sentry. The only one that still gets events is https://sentry.syncthing.net/share/issue/270bbc681e3943f7a121268553e6f2e5/, and that's what I am addressing here:

`panic: repairing sequences: filling Blocks: key not found`

When repairing sequences all local files are deserialized, and apparently sometimes the blocks are indirected (or look like it), but theirs no entry for the hash. Instead of failing db repair and thus making the db entirely broken, the defective file info is now removed from the db - to be rescanned later.

Some related changes: I moved checking/repairing globals out of `recalcMeta` into `getMetaAndCheck`. Having that happen as a side effect of recalculating metadata is plain confusing (and I probably wrote that code :) ).  
And the db migration 15 (which uses `recalcMeta`), is redundant with 16 (the meta just gets recalculated twice) - thus removed.

### CODE REVIEW

File: lib/db/lowlevel.go [hunk 1]
```diff
@@ -1022,6 +1032,25 @@ func (db *Lowlevel) repairSequenceGCLocked(folderStr string, meta *metadataTrack
...
+				if err != nil {
+					return 0, err
+				}
+				if err := t.Delete(sk); err != nil {
+					return 0, err
+				}
+				if err := t.Delete(it.Key()); err != nil {
+					return 0, err
+				}
+			}
```
Comment (calmh) [inline lib/db/lowlevel.go:1053]: it also needs to be removed from globals?

**Review by calmh — APPROVED** [review]
