### PR TITLE
lib/model: Ignore difference in extended attributes & ownership when deleting (fixes #9371)

### LINKED ISSUE #9371: Deleting or renaming directories when syncing xattrs or ownership causes empty dir tree to get "put back" by ST
### Does your log mention database corruption?

No

### Versions

 - macOS 14.3 ← _I believe this may be the key factor_ (also tested up to 14.4 dev beta3  23E5196e)
 - syncthing ~~1.27.2~~ 1.27.3 macOS Bundle, also tested on v1.27.4-rc.1

### Setup

- 2 computers, both macOS + same versions of everything
- Both computers on the same LAN and have good connectivity
- 1 single Sync folder: 113,028 files, 20,458 directories, ~18.6 GiB
- ~~Trash Can~~ Simple file versioning (also tested with File Versioning disabled, makes no difference)

### Issue

In the last few days, while working in one particular subfolder of my single Sync directory, I experienced a situation where a deleted folder from machine A (that was present and fully synced between my 2 computers) almost immediately **re-appears**.

The error message `syncing: delete dir: file modified but not rescanned; will try again later` seems to repeat ad infinitum in the logs below. 

The only way I "solved" this was to very quickly delete the folder at the same time from both machines. But, if I re-create that folder and then delete it from machine A or B independently, the problem resurfaces.

The clocks are set correctly on both machines.

Deleting the directory via Terminal `rm -rf ./whatever/` behaves the same as trashing it via Finder.

probably related forum thread: https://forum.syncthing.net/t/deleted-folders-keep-re-appearing/19290/28

**update**: PR submitted ~~https://github.com/syncthing/syncthing/pull/9424~~ ... and now an updated one https://github.com/syncthing/syncthing/pull/9430

### Logs

<details><summary>(click to reveal)</summary>

```
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/parallel"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/block_docstring"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/_utils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/render/ocv"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/ma/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/lib/tests/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/size"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/f2cmap"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/mingw"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/videoio_registry"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ie/detail"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/reveal"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/lib"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/string"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/src"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/misc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/segmentation"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_logical"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/checks"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/tests/examples/limited_api"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/include/numpy/random"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/typing"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/wip/gst"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/linalg/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/compat/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ogl"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/regression/gh25337"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/mixed"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/cli"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/samples"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/pass"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/utils/nested"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/core/cpu"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/_core"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ov"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/aruco"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/bin"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/kind"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ml"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/detail"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/barcode"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/parameter"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/quoted_character"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/oak"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/fft/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/mat_wrapper"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ocl"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/Error"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/_examples/cffi"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/core/fluid"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_character"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/_backends"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/utils/fs"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/video"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/testing/_private"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 "Sync" (9bupw-pod9e): Failed to sync 106 items
2024-01-26 14:05:49 Folder "Sync" (9bupw-pod9e) isn't making sync progress - retrying in 1m1s.
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/mixed"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/__pycache__"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/matrixlib/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/quoted_character"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/core/fluid"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/compat/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/dnn"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/wip/gst"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/reveal"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/kind"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/_backends"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/barcode"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/fail"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/onnx/ep"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/oak"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/bin"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/_examples/numba"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/parameter"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ocl"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/own/detail"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/aruco"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/.dylibs"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/opencv_python-4.9.0.80.dist-info"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/tests/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/mingw"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/tests/examples/cython"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/utils/nested"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/misc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/regression/gh25337"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/abstract_interface"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ipp"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/render/ocv"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/flann"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/crackfortran"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/cli"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/videoio_registry"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ov"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/testing/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/src"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/utils/fs"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/lib/tests/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_character"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/common"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/string"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/mat_wrapper"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/wip/onevpl"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/imgproc/fluid"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/segmentation"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/detail"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_integer"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_complex"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/include/numpy/random"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/_typing"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ie/detail"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/fft/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/negative_bounds"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/assumed_shape"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/size"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/_pyinstaller"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ogl"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/linalg/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_real"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/samples"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/pass"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/callback"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/fisheye"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/_examples/cffi"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/tests/examples/limited_api"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/streaming"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/Error"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/value_attrspec"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/return_logical"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/tests/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/_core"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/lib"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/core/cpu"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/ma/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/fcompiler"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/typing"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data/misc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/array_api/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/core/ocl"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/command"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/_utils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/ml"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/video"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy-1.26.3.dist-info"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/f2cmap"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/doc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/.dylibs"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/wip/draw"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ot/cpu"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/cuda"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/polynomial/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/isocintrin"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/block_docstring"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/testing/_private"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/module_data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/parallel"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/lib/npy-pkg-config"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/_examples/cython"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/array_from_pyobj"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils/checks"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:49 "Sync" (9bupw-pod9e): Failed to sync 106 items
2024-01-26 14:05:49 Folder "Sync" (9bupw-pod9e) isn't making sync progress - retrying in 1m0s.
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/distutils/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/core/include/numpy"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/own"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/ot"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/onnx"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/ie"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/distutils/fcompiler"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/compat/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/utils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/misc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/mat_wrapper"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/wip"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/core/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/_utils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/render"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/imgproc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/distutils/command"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/typing"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi/core"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:05:50 "Sync" (9bupw-pod9e): Failed to sync 20 items
2024-01-26 14:05:50 Folder "Sync" (9bupw-pod9e) isn't making sync progress - retrying in 1m0s.
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2/gapi"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/core"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/matrixlib"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/lib"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/lib"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ot"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/typing/tests/data"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/fft"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/include"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/compat"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/wip"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/render"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/ma"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/distutils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/utils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/ie"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/polynomial"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/linalg"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/tests/examples"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/include/numpy"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/own"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/array_api"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/onnx"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/core/include"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/testing"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random/_examples"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/lib/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/core/tests"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/core"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/compat"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/cv2"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/random"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.z/numpy/distutils"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src/regression"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/numpy/f2py/tests/src"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 Puller (folder "Sync" (9bupw-pod9e), item "Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DBB851BA-9EFB-4042-950E-441689B493EE/libs.x/cv2/gapi/imgproc"): syncing: delete dir: file modified but not rescanned; will try again later
2024-01-26 14:06:49 "Sync" (9bupw-pod9e): Failed to sync 48 items
2024-01-26 14:06:49 Folder "Sync" (9bupw-pod9e) isn't making sync progress - retrying in 1m0s.
```

</details>

### PR DESCRIPTION
**Pull request by luckman212**
alternate solution (no longer just macOS specific) that adds a bool flag to `scanIfItemChanged()` to indicate when the scan was initiated from a delete function, and if so, tell `IsEquivalentOptional()` to ignore Xattrs and Ownership regardless of the global setting.

I tested this with my sledgehammer and it seems to pass.

### CODE REVIEW

**Comment by luckman212** [comment]
@tomasz1986 How is this looking? I see one of the automated tests failed but based on an old version, not sure what this means.

Sample size of 1: I've been running the patched binary on 2 machines for about a week now with no ill effects noted.

**Comment by anonhostpi** [comment]
only noticeable error in the build logs:

https://github.com/syncthing/syncthing/actions/runs/8015648590/job/21983704437?pr=9430#step:7:4343

**Comment by anonhostpi** [comment]
### Line 838:

https://github.com/syncthing/syncthing/blob/07a9fa2dbd60cdd2ee7f1a74324476547c65f76c/lib/connections/service.go#L838-L842

### Line 689:

https://github.com/syncthing/syncthing/blob/07a9fa2dbd60cdd2ee7f1a74324476547c65f76c/lib/connections/service.go#L689

**Comment by anonhostpi** [comment]
Seems to be normal though: https://github.com/syncthing/syncthing/actions/runs/8015648590/job/21983703884?pr=9430#step:7:4342

**Comment by anonhostpi** [comment]
The error on 4196 seems a bit obscure, but 4103, at least gives you a trace:

> sync_test.go:154: Unexpected message count

**Comment by anonhostpi** [comment]
https://github.com/syncthing/syncthing/issues/4213

**Comment by luckman212** [comment]
Would really like to see this fix land in 1.27.4, and it looks like there are only a few days left.

I'm over my head with these build errors. Is that a blocker here? I don't know what I can do about those or if there's even anything that needs to be done. They look like red herrings.

**Comment by luckman212** [comment]
@calmh Do I need to rebase my fork here...

**Comment by tomasz1986** [comment]
> Would really like to see this fix land in 1.27.4, and it looks like there are only a few days left.
> 
> I'm over my head with these build errors. Is that a blocker here? I don't know what I can do about those or if there's even anything that needs to be done. They look like red herrings.

PRs here sometime can take quite a while to review. I wouldn't push it. I don't think the build error is necessarily a problem here, it is just that one of the maintainers needs to find enough time to look at the code, and this isn't always possible in a quick manner.

If you do need to have this implemented right away, I would suggest to simply compile your own build with the patch with upgrades disabled, and then use that for the time being until the fix has been added to the official codebase. Building Syncthing is very simple, i.e. literally a one-line command as long as you have Go installed (see https://docs.syncthing.net/dev/building.html).

**Comment by luckman212** [comment]
I understand, of course PRs take time to review. And I'm happy to keep running my patched build, but any bug that results in sync breaking this badly seems like it would warrant some extra prioritization. I don't make these decisions of course.

File: lib/model/folder_sendrecv.go [hunk 1]
```diff
@@ -2086,14 +2085,13 @@ func (f *sendReceiveFolder) scanIfItemChanged(name string, stat fs.FileInfo, ite
...
 	}
-
 	if !statItem.IsEquivalentOptional(item, protocol.FileInfoComparison{
 		ModTimeWindow:   f.modTimeWindow,
 		IgnorePerms:     f.IgnorePerms,
 		IgnoreBlocks:    true,
 		IgnoreFlags:     protocol.LocalAllFlags,
 		IgnoreOwnership: !f.SyncOwnership,
-		IgnoreXattrs:    !f.SyncXattrs,
+		IgnoreXattrs:    fromDelete || !f.SyncXattrs,
```
Comment (anonhostpi) [inline lib/model/folder_sendrecv.go:2094]: From what I can see this is the only noteworthy significant change.  All other changes in this PR are just "argument-passing."

The only concerns I see here is how could you reliably test this change on different platforms and _what set of cases (in addition to #9371) would you test this against?_

I would look into what test files use this block in their test, and what gh issues those tests were related to, if you are looking to speed this up.

I'd also recommend keeping up your vigor with documenting your work (taking screenshots, recordings, etc), since that seems to have gotten a positive response on your other issues.

**Comment by anonhostpi** [comment]
> I'm over my head with these build errors. Is that a blocker here? I don't know what I can do about those or if there's even anything that needs to be done. They look like red herrings.

I'd assume that they are red herrings

**Comment by luckman212** [comment]
I've just rebased my fork and branch to the tip to make it easier. I don't have time in the next 48 hrs to look at the tests, but if no maintainers have looked by then I will take a look over the weekend.

**Comment by luckman212** [comment]
In the discussion at https://forum.syncthing.net/t/nested-folders-keep-reappearing/21704/10 it appears we may need to take `SyncOwnership` into account as well as `SyncXattrs`. I will publish an updated patch shortly after testing.

**Review by calmh — APPROVED** [review]

**Comment by calmh** [comment]
> Would really like to see this fix land in 1.27.4

Not gonna happen, sorry. Next one.

**Comment by anonhostpi** [comment]
Good work @luckman212. I'm glad I followed this from start to finish. I would be proud, if I were in your shoes.
