### PR TITLE
fix(gui): expand tildes for subdir check (fixes #9400)

### LINKED ISSUE #9400: Folder overlap not detected when using tilde
### Steps to reproduce
1. After setup, the default folder should be at `/home/<username>/Sync`. Click 'Add Folder' and enter `~/Sync` or `~/Sync/a` for the folder path.
### Expected behavior
Following text should be shown:
> Warning, this path is a subdirectory of an existing folder "Default Folder" (default).
### Actual behavior
No warning is shown.
### System information
Syncthing v1.27.3-rc.2 on Ubuntu 22
### Further comments
I believe it would also be helpful to 1) require checking a box to confirm "I understand the implications" and 2) show the warning in the folder list as well.
Related issue would be detecting overlaps that are caused by symlinks.
As far as I can tell, [overlap detection is currently happening on the frontend](https://github.com/syncthing/syncthing/blob/main/gui/default/syncthing/core/pathIsSubDirDirective.js).

### PR DESCRIPTION
**Pull request by tobifroe**
### Purpose
This closes #9400 by always expanding tildes when parent/subdir checks are done.

### Testing
I tested this by creating folders with paths to parent or subdirectories of the default folder that include a tilde in their path as shown in the attached screenshots. 
With this change, overlap will be detected regardless of wether or not tildes are used in other folder paths.

### Screenshots
Default Folder:
2024-10-26-At-08h40m33s
Newly created folder (parent directory in this case)
2024-10-26-At-08h40m13s

### CODE REVIEW

File: gui/default/syncthing/core/pathIsSubDirDirective.js [hunk 1]
```diff
@@ -6,7 +6,11 @@ angular.module('syncthing.core')
                 ctrl.$validators.folderPathErrors = function (viewValue) {
                     // This function checks whether ydir is a subdirectory of xdir,
                     // e.g. it would return true if xdir = "/home/a", ydir = "/home/a/b".
+                    // Tildes in both xdir and ydir are expanded for comparison
+                    // so that e.g. xdir = "home/a/", ydir = "~/b" will return true.
                     function isSubDir(xdir, ydir) {
+                        xdir = xdir.replace("~", scope.system.tilde);
```
Comment (calmh) [inline gui/default/syncthing/core/pathIsSubDirDirective.js:12]: I don't think we want `/home/foo/my~dir/` to get expanded though, so this should probably be limited to replacing tilde followed by slash (and maybe backslash) at the beginning of the string?

Comment (tobifroe) [reply gui/default/syncthing/core/pathIsSubDirDirective.js]: You're right. I adapted the replace call. Thank you for the fast review btw! :)

File: gui/default/syncthing/core/pathIsSubDirDirective.js [hunk 2]
```diff
@@ -6,7 +6,12 @@ angular.module('syncthing.core')
                 ctrl.$validators.folderPathErrors = function (viewValue) {
                     // This function checks whether ydir is a subdirectory of xdir,
                     // e.g. it would return true if xdir = "/home/a", ydir = "/home/a/b".
+                    // Tildes in both xdir and ydir are expanded for comparison
+                    // so that e.g. xdir = "home/a/", ydir = "~/b" will return true.
                     function isSubDir(xdir, ydir) {
+                        var tildeExpansionRegex = new RegExp("^~\/");
+                        xdir = xdir.replace(tildeExpansionRegex, `${scope.system.tilde}/`);
+                        ydir = ydir.replace(tildeExpansionRegex, `${scope.system.tilde}/`);
```
Comment (calmh) [inline gui/default/syncthing/core/pathIsSubDirDirective.js:14]: I think you want to use `scope.system.pathSeparator` instead of a hardcoded slash. And perhaps, since we split on that on the line below, perhaps then just check if the first component is `~`?

Comment (tobifroe) [reply gui/default/syncthing/core/pathIsSubDirDirective.js]: I replaced the hardcoded slash with `scope.system.pathSeperator`. I do think we need to check for `~/` at the beginning of the string since we wouldn't want to expand  `~my-dir/foo`, right?

**Comment by acolomb** [comment]
Note that on Windows, both `\` **and** `/` are considered as path separators.  We should treat both `~/` and `~\` as referring to the home directory.

**Comment by acolomb** [comment]
The backslash is not special on other OSes, so would it make more sense to check for ( `\` or `system.pathSeparator` )? In case they are identical, it would not hurt.

**Comment by tobifroe** [comment]
@acolomb Shouldn't we check for `/` or `system.pathSeperator` to not match backslashes on Linux? I don't have a Windows machine available to check the value of `system.pathSeperator` there.

**Comment by acolomb** [comment]
Sorry, that was a typo of mine.  Of course I meant: `/` OR `system.pathSeparator`

On Windows, the browser's debug console tells me that the latter is `"\\"`, which should mean a single backslash if I'm reading JSON correctly here.

**Comment by tobifroe** [comment]
Thank you for clarifying @acolomb, changed the regex to reflect that.

File: gui/default/syncthing/core/pathIsSubDirDirective.js (hunk 2 above)
Comment (imsodin) [reply gui/default/syncthing/core/pathIsSubDirDirective.js]: Not asking for any change, just trying to clarify if it's of any interest to you:

How I understand @calmh's suggestion that still works, but no regex required: After splitting, you check that `xdirArr[0] === "~"` and then replace that. For `~my-dir/foo` the array will be `[~my-dir, foo]`, so no match/replace. The small downside: You need to split the expanded tilde again. The upside: No regex or handling of separator types needed, you just get the same behaviour as splitting (rightly or wrongly, but if it's wrong fixing both tilde and splitting consistently would be nice).

**Review by imsodin — APPROVED** [review]
Approved, the below is just a meta-comment on reviewing.

by @acolomb:

> Note that on Windows, both `\` **and** `/` are considered as path separators. We should treat both `~/` and `~\` as referring to the home directory.

This is a case of requiring a PR to do more than what it's main intent is. I believe we should generally not do that, resp. at most suggest that as an optional extension of the main intent. Sometimes it might not be clear if the proposal is integral to the change at hand or not - one possible litmus test is to ask yourself if the change is a net improval without it already (obviously neither final nor complete criteria). Feature creep can introduce all kinds of issues (delaying PRs, introducing unexpected side effects). Don't get me wrong, it's great if we find additional, concrete improvements during a PR, I just would like to see those more treated as optional suggestions than integral parts of the review.

**Comment by imsodin** [comment]
@calmh Policybot is listing a missing contributor approval. I noticed that before on PRs you approved. I don't see a way to "kick it" to make it re-evaluate the situation (some CI solution at work is very prone to missing hooks, that's why "kick it" is an ingrained action for me :) ) - do you know of one? Or any known issues/ideas/... for dealing with/troubleshooting this?

**Comment by calmh** [comment]
@imsodin It's silliness... your review is disqualified since you've pushed a commit and become a contributor. Merge commits shouldn't count towards that though, I'll see if I can fix what the problem is.

**Comment by calmh** [comment]
@imsodin https://github.com/syncthing/syncthing/pull/9818

**Comment by acolomb** [comment]
> This is a case of requiring a PR to do more than what it's main intent is. I believe we should generally not do that, resp. at most suggest that as an optional extension of the main intent.

@imsodin Thanks for the heads up, will try to keep it in mind next time.  However, to defend the circumstances here, I was reacting to a previous review comment which suggested using the `pathSeparator`.  So I meant to point out that this *proposed fix* to the PR content was incomplete, by not catching all otherwise valid combinations.  That's not feature creep IMO, but preventing fixes for improved correctness which are themselves not always correct.
