### PR TITLE
lib/connections: Validate device id before assuming success (fixes #5934)

### LINKED ISSUE #5934: Dialing regards any established connection as successful / does not check device ID
Dialing a host's address may end up connecting (successfully) to a different host (to which a connection may already exist). 
Currently, the dialer regards this as success, and the connection is only dropped later when the device ID is checked. This prevents falling back to dialing of other addresses. 

Two possible solutions come to mind:
- Dialer should check node ID after establishing connection before returning success. 
- If a successful connection exists via an address and a different device announces the very same address (including the dialing device's addresses themselves), dialing that and assuming to reach the other device is not logical. This could be suppressed. 

Two examples in which this causes issues:
1. Two hosts behind the same NAT, one directly reachable via port forwarding, both configured to the same (default) listening port. An outside node successfully connects to the port-forwarded node, then tries to connect to the NATed node using the same external IP and port, and establishes a successful connection - but to the wrong node. 
2. Syncthing running on a NATting device itself with other nodes behind the NAT. In this case, the NATting device may be tricked into trying to connect to itself. 

Example logs (anonymized) follow. 
Case 1:
```
2019/08/06 19:25:34.081495 structs.go:217: DEBUG: dialing UUID_OF_DEVICE_WE_WANT_TO_REACH tcp://EXTERNAL_IP_OF_NAT:22000 prio 10
2019/08/06 19:25:34.117970 tcp_dial.go:48: DEBUG: Dial (BEP/tcp): setting traffic class: setsockopt: protocol not available
2019/08/06 19:25:34.546076 structs.go:222: DEBUG: dialing UUID_OF_DEVICE_WE_WANT_TO_REACH tcp://EXTERNAL_IP_OF_NAT:22000 success: LOCAL_IP_OF_DIALING_NODE:49308-EXTERNAL_IP_OF_NAT:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
2019/08/06 19:25:34.546099 service.go:872: DEBUG: connected to UUID_OF_DEVICE_WE_WANT_TO_REACH 10 using LOCAL_IP_OF_DIALING_NODE:49308-EXTERNAL_IP_OF_NAT:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 10
...
2019/08/06 19:25:34.546161 service.go:875: DEBUG: discarding 0 connections while connecting to UUID_OF_DEVICE_WE_WANT_TO_REACH 10
...
2019/08/06 19:25:34.546258 service.go:477: DEBUG: sleep until next dial 1m0s
2019/08/06 19:25:34.723211 service.go:282: INFO: Connected to already connected device UUID_OF_OTHER_DEVICE_BEHIND_THE_SAME_NAT (existing: LOCAL_IP_OF_DIALING_NODE:48686-EXTERNAL_IP_OF_NAT:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 new: LOCAL_IP_OF_DIALING_NODE:49308-EXTERNAL_IP_OF_NAT:22000/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256)
```

Case 2:
```
2019/08/06 19:21:34.136916 structs.go:217: DEBUG: dialing UUID_OF_DEVICE_WE_WANT_TO_REACH tcp://EXTERNAL_IP_OF_NATTING_DEVICE:22000 prio 9
2019/08/06 19:21:34.137011 tcp_listen.go:107: DEBUG: Listen (BEP/tcp): connect from EXTERNAL_IP_OF_NATTING_DEVICE:39702
2019/08/06 19:21:34.186905 structs.go:222: DEBUG: dialing UUID_OF_DEVICE_WE_WANT_TO_REACH tcp://EXTERNAL_IP_OF_NATTING_DEVICE:22000 success: EXTERNAL_IP_OF_NATTING_DEVICE:39702-EXTERNAL_IP_OF_NATTING_DEVICE:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
2019/08/06 19:21:34.186926 service.go:872: DEBUG: connected to UUID_OF_DEVICE_WE_WANT_TO_REACH 9 using EXTERNAL_IP_OF_NATTING_DEVICE:39702-EXTERNAL_IP_OF_NATTING_DEVICE:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256 10
2019/08/06 19:21:34.187022 service.go:229: INFO: Connected to myself (UUID_OF_NATTING_DEVICE) at EXTERNAL_IP_OF_NATTING_DEVICE:39702-EXTERNAL_IP_OF_NATTING_DEVICE:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256 - should not happen
2019/08/06 19:21:34.194114 service.go:229: INFO: Connected to myself (UUID_OF_NATTING_DEVICE) at EXTERNAL_IP_OF_NATTING_DEVICE:22000-EXTERNAL_IP_OF_NATTING_DEVICE:39702/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256 - should not happen
```

### Version Information

Syncthing Version: v1.2.1
OS Version: Gentoo Linux x86_64

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Duplicates some checks, but meh.

### CODE REVIEW

File: lib/connections/service.go [hunk 1]
```diff
@@ -884,3 +891,36 @@ func (s *service) dialParallel(deviceID protocol.DeviceID, dialTargets []dialTar
...
+	cs := c.ConnectionState()
+
+	// We should have received exactly one certificate from the other
+	// side. If we didn't, they don't have a device ID and we drop the
+	// connection.
+	certs := cs.PeerCertificates
+	if cl := len(certs); cl != 1 {
+		l.Infof("Got peer certificate list of length %d != 1 from peer at %s; protocol error", cl, c)
+		c.Close()
+		return fmt.Errorf("expected 1 certificate, got %s", cl)
```
Comment (golangcibot) [inline lib/connections/service.go]: printf: Errorf format %s has arg cl of wrong type int (from `govet`)

File: lib/connections/service.go [hunk 2]
```diff
@@ -884,3 +891,36 @@ func (s *service) dialParallel(deviceID protocol.DeviceID, dialTargets []dialTar
 	}
 	return internalConn{}, false
 }
+
+func (s *service) validateIdentity(c internalConn, expectedId protocol.DeviceID) error {
```
Comment (golangcibot) [inline lib/connections/service.go]: method parameter `expectedId` should be `expectedID` (from `golint`)

File: lib/connections/service.go [hunk 3]
```diff
@@ -884,3 +891,36 @@ func (s *service) dialParallel(deviceID protocol.DeviceID, dialTargets []dialTar
...
+		return fmt.Errorf("expected 1 certificate, got %d", cl)
+	}
+	remoteCert := certs[0]
+	remoteID := protocol.NewDeviceID(remoteCert.Raw)
+
+	// The device ID should not be that of ourselves. It can happen
+	// though, especially in the presence of NAT hairpinning, multiple
+	// clients between the same NAT gateway, and global discovery.
+	if remoteID == s.myID {
+		l.Infof("Connected to myself (%s) at %s - should not happen", remoteID, c)
```
Comment (calmh) [inline lib/connections/service.go]: Not related to this PR but I think we should drop this log message; it can and does happen, and the message just causes confusion.

Comment (AudriusButkevicius) [reply lib/connections/service.go]: It does help us to identify a certain type of problem, even if its not useful to the end user.
