### PR TITLE
gui: Disable Restore Versions filters when no versioned files exist (fixes #5408)

### LINKED ISSUE #5408: Selection of time in versions GUI not possible without editing the string inside the textfield
Steps to reproduce:
- Create a folder with versioning 
- Click on the folder and click the versions button
- click on the date textfield
- select Custom Range
- click on one of the drop down selectors for time
- The list of numbers appears and disappears a very short time after it --> no time for choose an other time

I'm using the latest Firefox and ST v0.14.54 on Linux

### PR DESCRIPTION
**Pull request by tomasz1986**
Currently, the name and date filters in the Restore Versions modal are always enabled, even if there are no versioned files present. With this change, they are enabled only when there are no errors and versioned files actually exist.

In addition to disabling the filters, also completely skip date picker generation, as it serves no function while still displaying a non-sense date range, which starts today and ends in the past.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

#### Before

image

#### After

image

### CODE REVIEW

**Comment by calmh** [comment]
Is there really no sane way of checking if an object is empty? Do we need to create a helper function?

**Comment by tomasz1986** [comment]
Yeah, I actually marked this WIP, as I'm going to change the approach completely. There's no need to generate the tree at all when there're no versions.

**Comment by tomasz1986** [comment]
I've changed the code a bit, so that tree generation is skipped almost immediately if there are no versions. I don't think it's that great though, as ideally all further parsing should be stopped in the function below. There's no point going forward if `data` is just `{}`, but I'm not really sure how to change the code to do do it cleanly.

https://github.com/syncthing/syncthing/blob/39d3424e34ae9c4636c4da53a075f744c6776567/gui/default/syncthing/core/syncthingController.js#L2592-L2605

I've also modified the HTML, so that the table and filter inputs are always shown. This way there's no GUI jumping, as the modal stays the same size and doesn't shrink, and also the `Loading data...` line is shown inside the table and not before it. I've also changed `loading: $translate.instant("Loading...")` to `loading: $translate.instant("Loading data...")` in JS to make both the same for consistency.

Do you mean creating a helper function instead of `(restoreVersions.versions | json) === '{}'`?

**Comment by calmh** [comment]
Yeah that's pretty ugly I think. There's `angular.equals(foo, {})` or `query.isEmptyObject` we could maybe use instead.

File: gui/default/syncthing/core/syncthingController.js [hunk 1]
```diff
@@ -2591,17 +2591,21 @@ angular.module('syncthing.core')
...
-                            $.each(data, function (key, values) {
-                                $.each(values, function (idx, value) {
-                                    value.modTime = new Date(value.modTime);
-                                    value.versionTime = new Date(value.versionTime);
-                                });
-                                values.sort(function (a, b) {
-                                    return b.versionTime - a.versionTime;
+                            if (isEmptyObject(data)) {
+                                $scope.restoreVersions.noversions = true;
+                            } else {
```
Comment (imsodin) [inline gui/default/syncthing/core/syncthingController.js:2596]: Could you initially set it to `$scope.restoreVersions.versions = null` and then `if !closed && !isEmptyObject { iterate and assign to ...versions`? Then in all the conditions you can check for `!restoreVersions.versions`. No new fields or weird stringify checks to identify an empty object.

Comment (tomasz1986) [reply gui/default/syncthing/core/syncthingController.js]: I've done that now (and actually did try doing something similar a few times before), but there's one problem that I'm unable to solve. Basically, with the current code, the Restore Versions modal loads fine on the first try. However, if you close and re-open it, the following error pops up.

```
TypeError: Cannot read properties of undefined (reading 'expanderClosed')
    at setIcon (jquery.fancytree-all-deps.js:11752:14)
    at Fancytree.nodeRenderStatus (jquery.fancytree-all-deps.js:11848:5)
    at Fancytree.nodeRenderStatus (jquery.fancytree-all-deps.js:1701:22)
    at Fancytree.nodeRenderTitle (jquery.fancytree-all-deps.js:6521:10)
    at Fancytree._super (jquery.fancytree-all-deps.js:1685:22)
    at Fancytree.nodeRenderTitle (jquery.fancytree-all-deps.js:13185:15)
    at Fancytree.nodeRenderTitle (jquery.fancytree-all-deps.js:1701:22)
    at Fancytree.nodeRender (jquery.fancytree-all-deps.js:13123:11)
    at Fancytree.nodeRender (jquery.fancytree-all-deps.js:1701:22)
    at Fancytree.nodeRender (jquery.fancytree-all-deps.js:13144:11)
```

I've only managed to get around it by changing the code from

```
        <table id="restoreTree">
          <tbody>
            <tr>
              <td>
                <span ng-if="restoreVersions.versions"translate>Loading data...</span>
                <span ng-if="!restoreVersions.versions" translate>There are no file versions to restore.</span>
              </td>
              <td></td>
            </tr>
          </tbody>
        </table>
```

to something more like

```
        <table id="restoreTree" ng-if="restoreVersions.versions">
          <tbody>
            <tr>
              <td translate>Loading data...</td>
              <td></td>
            </tr>
          </tbody>
        </table>
        <table id="restoreTree" ng-if="!restoreVersions.versions">
          <tbody>
            <tr>
              <td translate>There are no file versions to restore.</td>
              <td></td>
            </tr>
          </tbody>
        </table>
```

which does get rid of the error, but the table code ends up being duplicated. The two messages themselves need to be inside the table cells in order to match the same style (padding, etc.) as when there are actual versioned files rendered there.

Comment (imsodin) [reply gui/default/syncthing/core/syncthingController.js]: Can you try readding the condition in L3:
https://github.com/syncthing/syncthing/pull/8539/commits/39249a02cac5c0fabb4b14190007f5bd7a9e56f5#diff-35607bd09efb510801fed738df57073a32758c8f16b7f40693fe007d92fd306dL3  
Not that I'd understand why it helps, but it looks like an unrelated change and with this UI code any change in code may trigger any change in behaviour (maybe not quite as bad, but almost :P ).

Comment (tomasz1986) [reply gui/default/syncthing/core/syncthingController.js]: Yeah, it works with that too (as it's essentially the same as when moved down to the table element), but the problem is that I wanted to move the span element

https://github.com/syncthing/syncthing/pull/8539/files#diff-35607bd09efb510801fed738df57073a32758c8f16b7f40693fe007d92fd306dL3

from outside into the table, so that its position and padding matches the table cells, which prevents the text from jumping that takes place now while the table is being loaded 😕. That's why I was experimenting with two different conditions — one for `restoreVersions.versions` itself, and one for when `restoreVersions.versions` is empty.

**Comment by tomasz1986** [comment]
I've found the helper function `sizeOf` which is already used in other HTML files of the GUI, so I've decided to use it here too, which has simplified the whole diff greatly. Please check the current iteration and let me know whether the code is fine like this or whether there's still something to fix.

File: gui/default/syncthing/folder/restoreVersionsModalView.html [hunk 2]
```diff
@@ -1,12 +1,14 @@
...
+    <div ng-if="restoreVersions.versions && !restoreVersions.errors">
       <div id="restoreTree-container">
         <table id="restoreTree">
           <tbody>
             <tr>
-              <td></td>
+              <td>
+                <span ng-if="sizeOf(restoreVersions.versions) > 0" translate>Loading data...</span>
+                <span ng-if="sizeOf(restoreVersions.versions) == 0" translate>There are no file versions to restore.</span>
+              </td>
```
Comment (imsodin) [inline gui/default/syncthing/folder/restoreVersionsModalView.html:11]: I assume this exists for the time until fancytree is initialised, isn't it? What's the point of the conditional, instead of just always showing "loading data" until fancytree is ready?

**Review by imsodin — COMMENTED** [review]
Looks good, just one change I don't understand.

File: gui/default/syncthing/folder/restoreVersionsModalView.html (hunk 2 above)
Comment (tomasz1986) [reply gui/default/syncthing/folder/restoreVersionsModalView.html:11]: Good question, and the code was remnants of the previous iteration, however I've now added yet another similar `sizeOf` check in the controller, so that the tree code doesn't run at all when there are no versions. This way, the window loads faster, there is no 1970 year in the disabled date filter, and the two conditionals are actually required again (because without the tree code running, the existing table isn't replaced with the tree table).

I hope the explanation is clear… What do you think?

Comment (imsodin) [reply gui/default/syncthing/folder/restoreVersionsModalView.html:11]: Yep makes sense. I don't think I'll remember/be able to figure it out if I ever stumble over this again though, but it wasn't any better before so 🤷

**Review by imsodin — APPROVED** [review]
