### PR TITLE
lib: Add util.Service as suture.Service template (fixes #5801)

### LINKED ISSUE #5801: panic: close of nil channel in relay client stop
1.2.0-rc.1

```
Stacktrace (most recent call first):

  File "C:/BuildAgent/work/174e136266f8a219/lib/relay/client/dynamic.go", line 124, in Stop
    close(c.stop)
  File "C:/BuildAgent/work/174e136266f8a219/lib/connections/relay_listen.go", line 124, in Stop
    t.client.Stop()
  File "C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go", line 651, in func1

panic: close of nil channel
```

https://crash.syncthing.net/report/f9/b0/f9b0fd4fbea87f1291d8559b2980ecbc98ae47e3b88b9c2320cc8865fa2f2c71

//@calmh

### PR DESCRIPTION
**Pull request by imsodin**
> Yeah this goes back to the "we need a template for suture services"
https://github.com/syncthing/syncthing/pull/5802#issuecomment-502695914

I created such a template and put it into place wherever there already was a `stopped` channel.

### CODE REVIEW

File: lib/relay/client/client.go [hunk 1]
```diff
@@ -39,3 +42,62 @@ func NewClient(uri *url.URL, certs []tls.Certificate, invitations chan protocol.
...
+
+type commonClient struct {
+	*util.Service
+
+	invitations              chan protocol.SessionInvitation
+	closeInvitationsOnFinish bool
+
+	stop chan struct{}
+
+	conn *tls.Conn
```
Comment (golangcibot) [inline lib/relay/client/client.go]: `conn` is unused (from `structcheck`)

**Comment by AudriusButkevicius** [comment]
I was imagining it differently, it essentially `util.AsSuture(func (closed chan struct{}) service.State) suture.Service`, where state can be IsComplete I guess. Idk. Or no return value from the runner func.

**Comment by AudriusButkevicius** [comment]
Essentially you just have a function that runs for the duration of the channel being open.
There could be an alternative implementation that returns an error, which could be used for listener services etc.

**Comment by imsodin** [comment]
Who closes the channel? As it is I don't get what you mean, maybe some pseudocode for a "sample implementation".

**Comment by AudriusButkevicius** [comment]
The wrapper implements stop and start, the function which we wrap just gets a channel as an argument which the wrapper closes on call to stop. On the phone so pseudo code is hard.

**Comment by imsodin** [comment]
At the very least this needs a second channel, that the caller closes after the first channel closed, so that the service thingy knows stopping has finished. At that point as I understand your proposal we are essentially back to my PR (except that I return util.Service, which admittedly might be just suture.Service and the struct type can be internalized, but that seems like a minor detail).

**Comment by AudriusButkevicius** [comment]
Well it knows when the function returned, it can have a second channel internally.

**Comment by imsodin** [comment]
Ah yes, I think I am finally getting now how it should work, sorry for the slowness :)  
However the more I seem to understand the less it differs from my PR: The only difference I see is that on close, in your version a close channel is closed, in my version a close function is called. I chose the latter, as it is more flexible. In some cases cleanup needs to be done regardless of whether serve is running or not and in other places (folder) the closing mechanism isn't a channel, but a context.

**Comment by AudriusButkevicius** [comment]
The problem with your proposal is that you have to manage the lifetime of the channel yourself, which is essentially what blew up in the face in the relay service, so I'd like to have a thing that literally deals with
`func(close chan struct{}) error`

**Comment by imsodin** [comment]
Is this (close to) what you want?

**Comment by AudriusButkevicius** [comment]
Yeah this is more like it.

I guess we could have a second implementation that returns
```
type ServiceWithError interface {
  suture.Service
  Error() error
}
```

That wraps `func(chan) error`

**Comment by imsodin** [comment]
Sure we could, that smells a bit like feature creep to me though ;)

File: lib/relay/client/static.go [hunk 2]
```diff
@@ -332,13 +241,17 @@ func performHandshakeAndValidation(conn *tls.Conn, uri *url.URL) error {
 	return nil
 }
 
-func messageReader(conn net.Conn, messages chan<- interface{}, errors chan<- error) {
+func messageReader(conn net.Conn, messages chan<- interface{}, errors chan<- error, stop chan struct{}) {
```
Comment (golangcibot) [inline lib/relay/client/static.go]: `conn` can be `io.Reader` (from `interfacer`)

File: lib/relay/client/static.go [hunk 3]
```diff
@@ -137,52 +99,28 @@ func (c *staticClient) Serve() {
 
 			case protocol.RelayFull:
 				l.Infof("Disconnected from relay %s due to it becoming full.", c.uri)
-				c.setError(fmt.Errorf("Relay full"))
-				c.disconnect()
+				return fmt.Errorf("Relay full")
```
Comment (golangcibot) [inline lib/relay/client/static.go]: ST1005: error strings should not be capitalized (from `stylecheck`)

File: lib/relay/client/static.go [hunk 4]
```diff
@@ -137,52 +99,28 @@ func (c *staticClient) Serve() {
...
 
-		case <-c.stop:
+		case <-stop:
 			l.Debugln(c, "stopping")
-			c.setError(nil)
-			c.disconnect()
+			return nil
 
-		// We always exit via this branch of the select, to make sure the
-		// the reader routine exits.
```
Comment (imsodin) [inline lib/relay/client/static.go]: I now pass the closed channel to that routine to remove this tedious requirement.

**Comment by imsodin** [comment]
@AudriusButkevicius Added that option and adapted relay clients to use it (which required a bit of a refactor, but made things simpler in my opinion).

File: lib/connections/service.go [hunk 5]
```diff
@@ -313,11 +319,11 @@ next:
 		l.Infof("Established secure connection to %s at %s", remoteID, c)
 
 		s.model.AddConnection(modelConn, hello)
-		continue next
+		continue
 	}
 }
 
-func (s *service) connect() {
+func (s *service) connect(stop chan struct{}) {
```
Comment (golangcibot) [inline lib/connections/service.go]: cyclomatic complexity 34 of func `(*service).connect` is high (> 30) (from `gocyclo`)

File: lib/connections/service.go [hunk 6]
```diff
@@ -328,6 +334,12 @@ func (s *service) connect() {
 	var sleep time.Duration
 
 	for {
+		select {
+		case <-stop:
+			return
+		default:
+		}
```
Comment (AudriusButkevicius) [inline lib/connections/service.go]: There is a massive sleep at the moment, the stop should be plumbed in there.

File: lib/model/folder.go [hunk 7]
```diff
@@ -256,7 +256,7 @@ func (f *folder) Delay(next time.Duration) {
 
 func (f *folder) Stop() {
 	f.cancel()
-	<-f.stopped
+	f.Service.Stop()
```
Comment (AudriusButkevicius) [inline lib/model/folder.go]: Shouldn't we just do defer f.cancel() in serve?

File: lib/model/folder.go [hunk 8]
```diff
@@ -119,7 +120,6 @@ func (f *folder) Serve() {
 	defer func() {
 		f.scanTimer.Stop()
 		f.setState(FolderIdle)
-		close(f.stopped)
```
Comment (AudriusButkevicius) [inline lib/model/folder.go]: f.cancel() here?

File: lib/relay/client/dynamic.go [hunk 9]
```diff
@@ -14,45 +14,29 @@ import (
...
 type dynamicClient struct {
-	pooladdr                 *url.URL
-	certs                    []tls.Certificate
-	invitations              chan protocol.SessionInvitation
-	closeInvitationsOnFinish bool
-	timeout                  time.Duration
-
-	mut    sync.RWMutex
-	err    error
+	*commonClient
```
Comment (AudriusButkevicius) [inline lib/relay/client/dynamic.go]: does this need to be a pointer?

File: lib/relay/client/dynamic.go [hunk 10]
```diff
@@ -115,24 +93,23 @@ func (c *dynamicClient) Serve() {
...
 
 func (c *dynamicClient) Stop() {
+	c.ServiceWithError.Stop()
 	c.mut.RLock()
 	defer c.mut.RUnlock()
-	close(c.stop)
-	if c.client == nil {
-		return
+	if c.client != nil {
+		c.client.Stop()
```
Comment (AudriusButkevicius) [inline lib/relay/client/dynamic.go]: Make the service defer client stop?

File: lib/stun/stun.go [hunk 11]
```diff
@@ -100,24 +103,25 @@ func New(cfg config.Wrapper, subscriber Subscriber, conn net.PacketConn) (*Servi
...
-		stop:    make(chan struct{}),
-	}, otherDataConn
+	}
+	s.Service = util.AsService(s.serve)
+	return s, otherDataConn
 }
 
 func (s *Service) Stop() {
-	close(s.stop)
+	s.Service.Stop()
```
Comment (AudriusButkevicius) [inline lib/stun/stun.go]: Again, can the stunConn be closed in serve?

File: lib/ur/usage_report.go [hunk 12]
```diff
@@ -422,23 +411,16 @@ func (s *Service) VerifyConfiguration(from, to config.Configuration) error {
...
 	if from.Options.URAccepted != to.Options.URAccepted || from.Options.URUniqueID != to.Options.URUniqueID || from.Options.URURL != to.Options.URURL {
-		s.stopMut.RLock()
 		select {
 		case s.forceRun <- struct{}{}:
-		case <-s.stop:
+		default:
+			// s.forceRun is one buffered, so even though nothing
+			// was sent, a run will still happen after this point.
 		}
-		s.stopMut.RUnlock()
```
Comment (AudriusButkevicius) [inline lib/ur/usage_report.go]: There is a change in behaviour here. This used to block until the forceRun completed potentially, or atleast was accepted.
That might no longer be the case. I suspect it's ok, but suggest you verify if it really is.

File: lib/util/utils.go [hunk 13]
```diff
@@ -170,3 +174,69 @@ func Address(network, host string) string {
...
+	s.err = err
+	s.mut.Unlock()
+}
+
+func (s *service) Stop() {
+	s.mut.Lock()
+	s.stopping = true
+	s.mut.Unlock()
+	close(s.stop)
+	<-s.stopped
```
Comment (AudriusButkevicius) [inline lib/util/utils.go]: I think these services can never be restarted, as s.stop is only initialised once?
Also it feels wrong touching s.stop and s.stopped outside of the lock, as they are clearly initialised under the lock, so I feel this is racey.

File: lib/stun/stun.go (hunk 11 above)
Comment (imsodin) [reply lib/stun/stun.go]: In this case it looks like no, as the `stunConn` is established in `New`, not in `serve`.

File: lib/model/folder.go (hunk 7 above)
Comment (imsodin) [reply lib/model/folder.go]: The cancelled context is also used in functions within serve, e.g. puller, so that would be too late.

File: lib/ur/usage_report.go (hunk 12 above)
Comment (imsodin) [reply lib/ur/usage_report.go]: The relevant select above just has three options: stop, forceRun (resets timer) and timer fired (send a usage report). So the only way there could be a significant difference is if at the time of this being called, a report is being sent. Then this would have blocked until that is finished, now it immediately unblocks. The result is the same: As soon as the usage report goes through, another one happens. And on the side that changes the config I can't see any reason why someone should want to wait on the previous (not the scheduled) usage report being finished.

File: lib/util/utils.go (hunk 13 above)
Comment (imsodin) [reply lib/util/utils.go]: They indeed can't be restarted after `Stop`, that's by design as mandated by suture:

> [...] A supervisor will call .Stop() only once. Thus, it may be as destructive as it likes to get the service to stop.
> 
> Once Stop has been called on a Service, the Service SHOULD NOT be reused in any other supervisor! [...]

I added `stopping` after a race came up in testing - in hindsight that's an ugly bolt-on. I revised the stop/stopped-locking-machinism, I hope it's clearer now (and should be race free).

**Comment by imsodin** [comment]
Regarding name of services:  
The object returned by `util.AsService` is always embedded into another object, which itself can/should implement `fmt.Stringer`. I think it's always a good thing for any non-trivial types to implement that, otherwise all it's components are accessed when being logged, which could be racy. In a few places we just "convert a function to a service", in which case there was neither a name before nor now, I could either add another wrapper (`ServiceWithName`) or add a name parameter to `AsService`, which will then be somewhat redundant, as in most places the value passed will just be `.String()`.  
Any opinions on which is the better variant?

**Comment by calmh** [comment]
Do nothing about the naming, sounds like status quo is fine

File: lib/model/folder.go (hunk 7 above)
Comment (AudriusButkevicius) [reply lib/model/folder.go]: I guess we could in the run do
```
go func()
  select {
   case <-stop:
     f.cancel()
  }
}()
```

Yet I don't feel strongly about this.

**Comment by AudriusButkevicius** [comment]
https://media.giphy.com/media/GGMUpbtiNX4C4/giphy.gif
