### PR TITLE
lib/config: Prevent nil deref in debug logging (fixes #5955)

### LINKED ISSUE #5955: folderconfiguration.go crash on creating new config on Android
Go crash, see forum topic for details: https://forum.syncthing.net/t/problem-creating-configuration-on-android-q/13648

```
12:12:58E/Go       goroutine 1 [running]:
12:12:58E/Go       github.com/syncthing/syncthing/lib/config.(*FolderConfiguration).prepare(0x628bc0b0)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/config/folderconfiguration.go:253 +0x206
12:12:58E/Go       github.com/syncthing/syncthing/lib/config.NewFolderConfiguration(0x777638d6, 0x92749d36, 0x9f569bb3, 0x4ff8f9e6, 0x4c28ebf5, 0xca934f1f, 0x5a5d7db, 0xa870023f, 0x5ff844ee, 0x7, ...)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/config/folderconfiguration.go:86 +0x12f
12:12:58E/Go       github.com/syncthing/syncthing/lib/syncthing.DefaultConfig(0x62a8bc20, 0x44, 0x777638d6, 0x92749d36, 0x9f569bb3, 0x4ff8f9e6, 0x4c28ebf5, 0xca934f1f, 0x5a5d7db, 0xa870023f, ...)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/syncthing/utils.go:53 +0x2d7
12:12:58E/Go       main.generate(0xfffe9811, 0x39, 0x0, 0x0)
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:440 +0x452
12:12:58E/Go       main.main()
12:12:58E/Go       	F:/GitHub/syncthing-android/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:347 +0x23e
```

### PR DESCRIPTION
**Pull request by imsodin**
This is relevant to the current RC.

### CODE REVIEW

File: lib/config/folderconfiguration.go [hunk 1]
```diff
@@ -248,9 +248,12 @@ func (f *FolderConfiguration) prepare() {
 	case f.RawModTimeWindowS > 0:
 		f.cachedModTimeWindow = time.Duration(f.RawModTimeWindowS) * time.Second
 	case runtime.GOOS == "android":
-		if usage, err := disk.Usage(f.Filesystem().URI()); err != nil || usage.Fstype == "" || strings.Contains(strings.ToLower(usage.Fstype), "fat") {
+		if usage, err := disk.Usage(f.Filesystem().URI()); err != nil {
```
Comment (golangcibot) [inline lib/config/folderconfiguration.go]: ifElseChain: rewrite if-else to switch statement (from `gocritic`)
