### PR TITLE
lib/fs, lib/model: Add warning about kqueue resource usage (fixes #7855)

### LINKED ISSUE #7855: Watching for changes using too many system resources on BSDs (kqueue)
Kqueue is a very heavyweight mechanism to watch for changes. Issues about systems being brought to their knees by Syncthing's watching for changes with large folders come in every now and then, see e.g. https://forum.syncthing.net/t/truenas-freenas-folder-watcher-unusably-slow-crashes-host/17161

We should somehow prevent this. Either disabling kqueue alltogether or adding a limit for items in a folder (disable kqueue once reached). The latter will be somewhat annoying, as I guess users will want to adjust/override that, and we'd need to enable watching only after the initial scan (so we know how many items there are). However just disabling it will probably make a lot of people mad.

### PR DESCRIPTION
**Pull request by imsodin**
Once-per-folder warning about kqueue potentially using a lot of resources and slowing the system down, when exceeding a more or less arbitrary number of files/dirs to be watched.  
The motivation to do it in the folder instead of e.g. a generic one-off warning on kqueue systems at startup is to only warn if folder watching is enabled. The limit is meant to not warn on trivially low number of items, but that might be a bad idea, as that threshold isn't meaningful - there might be a super-low powered device where <10k is already problematic, or multiple folders which cumulatively become problematic. Then again I don't want to add more complexity (some global counter in a model routine) just for a warning like this.

### CODE REVIEW

File: lib/model/folder.go [hunk 1]
```diff
@@ -997,6 +1006,10 @@ func (f *folder) monitorWatch(ctx context.Context) {
 			}
 			lastWatch = time.Now()
 			watchaggregator.Aggregate(aggrCtx, eventChan, f.watchChan, f.FolderConfiguration, f.model.cfg, f.evLogger)
+			if fs.WatchKqueue {
```
Comment (calmh) [inline lib/model/folder.go:1009]: On mobile so asking instead of investigating; is there a risk of ending up here more than once, so that there should be a == null check to avoid leaking subscriptions?

File: lib/model/folder.go [hunk 2]
```diff
@@ -1023,8 +1036,19 @@ func (f *folder) monitorWatch(ctx context.Context) {
 			}
 			aggrCancel()
 			errChan = nil
+			if summarySub != nil {
+				summarySub.Unsubscribe()
+			}
 			aggrCtx, aggrCancel = context.WithCancel(ctx)
+		case summary := <-summaryChan:
+			if !f.warnedKqueue && summary.Data.(map[string]interface{})["localTotalItems"].(int) > kqueueItemCountThreshold {
```
Comment (calmh) [inline lib/model/folder.go:1044]: Seems like we should have defined types for the event data probably

File: lib/model/folder.go (hunk 1 above)
Comment (imsodin) [reply lib/model/folder.go:1009]: I am pretty sure it can't happen (we only get here after a failure/error from the watch, where we do unsubscribe), however there's no point un/subscribing on failure for this (warn once if watching is enabled) -> removed.

File: lib/model/folder.go (hunk 2 above)
Comment (imsodin) [reply lib/model/folder.go:1044]: Not should we have done that in general, I also should check the type. This would have panicked, as we wrap the map into another map. I added the types and a failure condition if the type is wrong.

File: lib/model/folder_summary.go [hunk 3]
```diff
@@ -76,8 +76,56 @@ func (c *folderSummaryService) String() string {
 	return fmt.Sprintf("FolderSummaryService@%p", c)
 }
 
-func (c *folderSummaryService) Summary(folder string) (map[string]interface{}, error) {
-	var res = make(map[string]interface{})
+type FolderSummary struct {
+	Errors     int
```
Comment (calmh) [inline lib/model/folder_summary.go:80]: JSON tags for keeping same casing as previously?

File: lib/model/folder_summary.go [hunk 4]
```diff
@@ -330,9 +383,9 @@ func (c *folderSummaryService) sendSummary(ctx context.Context, folder string) {
 	if err != nil {
 		return
 	}
-	c.evLogger.Log(events.FolderSummary, map[string]interface{}{
-		"folder":  folder,
-		"summary": data,
+	c.evLogger.Log(events.FolderSummary, folderSummaryEventData{
```
Comment (calmh) [inline lib/model/folder_summary.go:386]: Double check that verbose service doesn't crash due to this change as well?

File: lib/model/folder.go [hunk 5]
```diff
@@ -1024,7 +1037,19 @@ func (f *folder) monitorWatch(ctx context.Context) {
...
+				f.evLogger.Log(events.Failure, "Unexpected type of folder-summary event in folder.monitorWatch")
+			} else if data.Summary.LocalTotalItems > kqueueItemCountThreshold {
+				f.warnedKqueue = true
+				summarySub.Unsubscribe()
+				summaryChan = nil
+				l.Warnf("Filesystem watching (kqueue) is enabled on %v with a lot of files/directories, and that requires a lot of resources and might slow down your system significantly", f.Description())
+			}
 		case <-ctx.Done():
+			if summaryChan != nil {
+				summarySub.Unsubscribe()
```
Comment (calmh) [inline lib/model/folder.go:1051]: This could be a defer, I think?

**Review by calmh — COMMENTED** [review]
👍

File: lib/model/folder_summary.go (hunk 3 above)
Comment (imsodin) [reply lib/model/folder_summary.go:80]: TIL (again probably): Lowercasing is not the default behaviour for the json marshaller.

File: lib/model/folder_summary.go (hunk 4 above)
Comment (imsodin) [reply lib/model/folder_summary.go]: Right, of course it crashes. Checked all usages of `events.FolderSummary` now and we should be good. (Somehow whenever a change comes up as a followup, I tend to skip the "think about consequences" step of doing changes...).

**Review by calmh — APPROVED** [review]

**Comment by calmh** [comment]
Lgtm didn't look at the windows failure, probably spurious?

**Comment by imsodin** [comment]
Yes it is.
