### PR TITLE
Fix total transfer rates (fixes #1615)

### LINKED ISSUE #1615: Total transfer rate not updating (v0.11)
screen shot 2015-04-09 at 10 19 38

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

File: gui/scripts/syncthing/core/controllers/syncthingController.js [hunk 1]
```diff
@@ -368,7 +367,16 @@ angular.module('syncthing.core')
...
-                $scope.connections_total = data['total'];
+
+                try {
+                    data.total.inbps = Math.max(0, (data.total.inBytesTotal - $scope.connections_total.inBytesTotal) / td);
+                    data.total.outbps = Math.max(0, (data.total.outBytesTotal - $scope.connections_total.outBytesTotal) / td);
+                } catch (e) {
+                    data.total.inbps = 0;
+                    data.total.outbps = 0;
+                }
+                $scope.connections_total = data.total;
```
Comment (calmh) [inline gui/scripts/syncthing/core/controllers/syncthingController.js]: Make this camelCase while we're anyway digging around here, as everything else is. Otherwise LGTM. :)

Comment (AudriusButkevicius) [inline gui/scripts/syncthing/core/controllers/syncthingController.js]: Ah yes!
Muscle memory from other stuff.
