### PR TITLE
lib: Ensure timely service termination (fixes #5860)

### LINKED ISSUE #5860: Takes a long time to shut down on Ctrl-C (1.2.1-rc.1)
```
MRIW7] 22:14:47 INFO: Detected 2 NAT services
[monitor] 22:14:48 INFO: Signal 2 received; exiting
[MRIW7] 22:14:48 INFO: TCP listener (127.0.0.1:22002) shutting down
2019/07/16 22:14:58 Supervisor discover.cachingMux: discover.cachingMux: Service IPv6 local failed to terminate in a timely manner
2019/07/16 22:14:58 Supervisor local: local: Service multicastBeacon failed to terminate in a timely manner
[MRIW7] 22:14:58 INFO: connections.Service: Service c.S.listenerSupervisor failed to terminate in a timely manner
[MRIW7] 22:14:58 INFO: c.S.listenerSupervisor: Service dynamic+https://relays.syncthing.net/endpoint failed to terminate in a timely manner
[MRIW7] 22:14:58 INFO: Exiting
```

v1.2.1-rc.1

### PR DESCRIPTION
**Pull request by imsodin**
Now instead of various services not terminating at all or only after like forever, everything shuts down more or less immediately. Beware this is late-night-iterating between fixing something, getting another trace, fixing the next hangup, ... - some of my approaches taken are probably on the crude/heavy-handed side, but they seem to be working, so it's at least a basis to improve on.

### CODE REVIEW

File: lib/beacon/broadcast.go [hunk 1]
```diff
@@ -150,77 +150,74 @@ func (w *broadcastWriter) Serve() {
...
 	}
-}
 
-func (w *broadcastWriter) Stop() {
-	w.connMut.Lock()
-	if w.conn != nil {
-		w.conn.Close()
-	}
-	w.connMut.Unlock()
+	return nil
```
Comment (golangcibot) [inline lib/beacon/broadcast.go]: unreachable: unreachable code (from `govet`)

File: lib/beacon/broadcast.go [hunk 2]
```diff
@@ -150,77 +150,74 @@ func (w *broadcastWriter) Serve() {
...
 
-}
-
-func (r *broadcastReader) Stop() {
-	r.connMut.Lock()
-	if r.conn != nil {
-		r.conn.Close()
-	}
-	r.connMut.Unlock()
+	return nil
```
Comment (golangcibot) [inline lib/beacon/broadcast.go]: unreachable: unreachable code (from `govet`)

File: lib/beacon/multicast.go [hunk 3]
```diff
@@ -142,54 +138,49 @@ func (w *multicastWriter) serve(stop chan struct{}) {
...
 		if success > 0 {
-			w.setError(nil)
-		} else {
-			l.Debugln(err)
-			w.setError(err)
+			w.SetError(nil)
 		}
 	}
+
+	return nil
```
Comment (golangcibot) [inline lib/beacon/multicast.go]: unreachable: unreachable code (from `govet`)

File: lib/beacon/multicast.go [hunk 4]
```diff
@@ -206,30 +197,50 @@ func (r *multicastReader) serve(stop chan struct{}) {
...
-			continue
-		}
-		l.Debugf("recv %d bytes from %s", n, addr)
+		go func() {
+			for {
+				n, _, addr, err := pconn.ReadFrom(bs)
+				if err != nil {
+					l.Debugln(err)
+					r.SetError(err)
+					select {
```
Comment (golangcibot) [inline lib/beacon/multicast.go]: S1000: should use a simple channel send/receive instead of `select` with a single case (from `gosimple`)

File: lib/beacon/broadcast.go [hunk 5]
```diff
@@ -150,77 +150,74 @@ func (w *broadcastWriter) Serve() {
...
-			return
-		}
-
-		r.setError(nil)
 
-		l.Debugf("recv %d bytes from %s", n, addr)
+	for {
+		go func() {
+			for {
+				n, addr, err := conn.ReadFrom(bs)
```
Comment (calmh) [inline lib/beacon/broadcast.go]: This is a race against the copy out of bs in the loop below.

I think it would be cleaner to not have this goroutine and break the loop by closing the socket as previously? If having a separate stop method doesn't fit in the new architecture, this could maybe be as simple as launching a `go func() { <-stop; conn.Close() }` at the beginning?

File: lib/nat/registry.go [hunk 6]
```diff
@@ -19,34 +19,33 @@ func Register(provider DiscoverFunc) {
...
 	c := make(chan Device)
-	done := make(chan struct{})
-
 	for _, discoverFunc := range providers {
 		go func(f DiscoverFunc) {
 			for _, dev := range f(renewal, timeout) {
-				c <- dev
+				select {
+				case c <- dev:
+				case <-stop:
```
Comment (calmh) [inline lib/nat/registry.go]: I'd add an explicit return to avoid having to understand how long time the `f(...)` call might take for each device while exiting

File: lib/relay/client/dynamic.go [hunk 7]
```diff
@@ -147,18 +149,32 @@ type dynamicAnnouncement struct {
...
 
+	wg := sync.NewWaitGroup()
+	wg.Add(len(input))
+	results := make(chan urlWithLatency, len(input))
 	for _, relay := range input {
-		latency, err := osutil.GetLatencyForURL(relay)
-		if err != nil {
-			latency = time.Hour
-		}
+		go func(irelay string) {
```
Comment (calmh) [inline lib/relay/client/dynamic.go]: Doing all of these at once might overwhelm the connection and skew the results. I think we are not that much in a hurry. (Although checking stop after each is nice.)

File: lib/nat/registry.go (hunk 6 above)
Comment (AudriusButkevicius) [reply lib/nat/registry.go]: This will leave hanging routines tho, we should push the stop down and pass in a context. The wg.Done should be moved up too.

File: lib/util/utils.go [hunk 8]
```diff
@@ -187,6 +187,7 @@ func AsService(fn func(stop chan struct{})) suture.Service {
 type ServiceWithError interface {
 	suture.Service
 	Error() error
+	SetError(error)
 }
```
Comment (AudriusButkevicius) [inline lib/util/utils.go]: Starting to realize util.Service should have passed in a context oppose to a channel.

File: lib/relay/client/dynamic.go (hunk 7 above)
Comment (imsodin) [reply lib/relay/client/dynamic.go]: Reverted the goroutines, is still fast enough in my tests.

File: lib/nat/registry.go (hunk 6 above)
Comment (imsodin) [reply lib/nat/registry.go]: The changes were anyway wrong (my assumption of number of elements in `nats` was incorrect). I reverted everything except the stop-select part.

File: lib/beacon/broadcast.go (hunk 5 above)
Comment (imsodin) [reply lib/beacon/broadcast.go]: Done

File: lib/beacon/multicast.go [hunk 9]
```diff
@@ -224,12 +236,12 @@ func (r *multicastReader) serve(stop chan struct{}) {
...
 		select {
 		case r.outbox <- recv{c, addr}:
-		case <-stop:
-			return
 		default:
 			l.Debugln("dropping message")
 		}
 	}
+
+	return nil
```
Comment (golangcibot) [inline lib/beacon/multicast.go]: unreachable: unreachable code (from `govet`)

File: lib/util/utils.go (hunk 8 above)
Comment (imsodin) [reply lib/util/utils.go]: That would definitely be useful in places, but not happening in this PR (just due to time).

**Comment by imsodin** [comment]
Just as a head up: I should have addressed all the comments, so this is ready again from my side.

File: lib/beacon/broadcast.go [hunk 10]
```diff
@@ -150,77 +158,62 @@ func (w *broadcastWriter) Serve() {
...
+	}()
 
 	bs := make([]byte, 65536)
 	for {
 		n, addr, err := conn.ReadFrom(bs)
 		if err != nil {
 			l.Debugln(err)
-			r.setError(err)
-			return
+			return err
```
Comment (AudriusButkevicius) [inline lib/beacon/broadcast.go]: Will the error be cleared post stop? As in, if a stop causes error, what happens?

File: lib/beacon/multicast.go [hunk 11]
```diff
@@ -161,35 +163,41 @@ func (w *multicastWriter) String() string {
...
+		return err
 	}
+	done := make(chan struct{})
+	defer close(done)
+	go func() {
+		select {
+		case <-stop:
+		case <-done:
+		}
+		l.Infoln("mutlicastreader close conn")
```
Comment (AudriusButkevicius) [inline lib/beacon/multicast.go]: Hmm

File: lib/beacon/broadcast.go [hunk 12]
```diff
@@ -150,77 +158,62 @@ func (w *broadcastWriter) Serve() {
...
-	r.connMut.Unlock()
+	done := make(chan struct{})
+	defer close(done)
+	go func() {
+		select {
+		case <-stop:
+		case <-done:
+		}
+		conn.Close()
+	}()
```
Comment (AudriusButkevicius) [inline lib/beacon/broadcast.go]: Just defer conn.Close?

File: lib/beacon/multicast.go [hunk 13]
```diff
@@ -78,29 +78,35 @@ func (m *Multicast) Error() error {
...
 	}
+	done := make(chan struct{})
+	defer close(done)
+	go func() {
+		select {
+		case <-stop:
+		case <-done:
+		}
+		conn.Close()
+	}()
```
Comment (AudriusButkevicius) [inline lib/beacon/multicast.go]: Ditto defer conn.Close()?

File: lib/beacon/multicast.go (hunk 11 above)
Comment (AudriusButkevicius) [reply lib/beacon/multicast.go]: Ditto

File: lib/beacon/broadcast.go (hunk 10 above)
Comment (imsodin) [reply lib/beacon/broadcast.go]: No it isn't, meaning if there's an error set at the time it is stopped, that error remains. I don't think it matters though, does it?

**Comment by AudriusButkevicius** [comment]
Other than that random log message, lgtm

File: lib/nat/registry.go [hunk 14]
```diff
@@ -19,34 +19,42 @@ func Register(provider DiscoverFunc) {
...
+			case <-stop:
+				return
+			}
 		}
-		close(done)
 	}()
 
 	wg.Wait()
 	close(c)
-	<-done
```
Comment (calmh) [inline lib/nat/registry.go]: This makes a race, we don't know that the goroutine above is done modifying `nats` before returning it

File: lib/util/utils.go (hunk 8 above)
Comment (calmh) [reply lib/util/utils.go]: It's a fairly straghtforward refactor to do separately.
