### PR TITLE
gui: Fix and align folder editing states (fixes #8145)

### LINKED ISSUE #8145: Folder ID not editable in add folder dialog
When just pressing "Add folder", the folder ID is now not editable. It must be, or we can't manually add folders from another device.
Screenshot 2022-01-28 at 08 02 37

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by acolomb** [comment]
You missed one instance of "add" in https://github.com/imsodin/syncthing/blob/gui/fix-8145/gui/default/syncthing/core/syncthingController.js#L757

**Comment by acolomb** [comment]
As commented in #8146, shouldn't we add some wrapper methods for these checks, especially for the case when it's `new` or `new-pending`?  That would make it easier to find occurrences where a certain value is depended upon.

**Comment by imsodin** [comment]
Fixed and added a utility function for new and newpending - thanks!

File: gui/default/syncthing/core/uniqueFolderDirective.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ angular.module('syncthing.core')
             require: 'ngModel',
             link: function (scope, elm, attrs, ctrl) {
                 ctrl.$parsers.unshift(function (viewValue) {
-                    if (scope.currentFolder._editing != "add") {
+                    if (!scope.editingFolderNew()) {
```
Comment (acolomb) [inline gui/default/syncthing/core/uniqueFolderDirective.js:7]: This branch should also match the "new-pending" case, because just as with existing folders the ID entry will be readonly.  Validating without being able to change it is pointless.

**Review by acolomb — CHANGES_REQUESTED** [review]
Looks better, although I'd have added `editingFolderNewIgnores()` as well and there is one instance where the new logic is broken.

File: gui/default/syncthing/core/uniqueFolderDirective.js (hunk 1 above)
Comment (imsodin) [reply gui/default/syncthing/core/uniqueFolderDirective.js:7]: That's exactly the downside of these utility functions: It's not immediately obvious what they do. This one here already does match `new` or `new-pending`, as both are variants of adding a new folder.

Comment (acolomb) [reply gui/default/syncthing/core/uniqueFolderDirective.js:7]: Yes, I meant the negation should match "new-pending".  In effect, this should be

    if (scope.currentFolder._editing != "new") {

Comment (imsodin) [reply gui/default/syncthing/core/uniqueFolderDirective.js]: Right, there's already code checking for existing folders with that ID to present the user with the option to share the folder instead of adding it, so at this point we now it's unique -> adjusted.

**Review by acolomb — APPROVED** [review]
