### PR TITLE
lib/syncthing: Stop only once (fixes #5908)

### LINKED ISSUE #5908: panic: close of closed channel in lib/syncthing when shutting down
```
Stacktrace (most recent call first):

  File "/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/syncthing/syncthing.go", line 410, in Stop
    close(a.stop)
  File "/opt/tcagent/syncthing-1-work/174e136266f8a219/cmd/syncthing/main.go", line 682, in func1
    app.Stop(syncthing.ExitRestart)

panic: close of closed channel
```

```
goroutine 38 [running]:
github.com/syncthing/syncthing/lib/syncthing.(*App).Stop(0xc0000bc240, 0x3, 0x0)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/syncthing/syncthing.go:410 +0x130
main.setupSignalHandling.func1(0xc0001e68a0, 0xc0000bc240)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/cmd/syncthing/main.go:682 +0x4b
created by main.setupSignalHandling
	/opt/tcagent/syncthing-1-work/174e136266f8a219/cmd/syncthing/main.go:680 +0xbf
```

https://crash.syncthing.net/report/838ac6a5c63b879e6481e16b5317bb9c57f356ac43ff3dcb3817cd3b94543bba

1.2.1 regression I think

//@calmh

### PR DESCRIPTION
**Pull request by imsodin**
Besides the once to prevent closing multiple times I also moved assigning `a.err` into that new once, as it technically could race with `Error`.

### CODE REVIEW

File: lib/syncthing/syncthing.go [hunk 1]
```diff
@@ -398,18 +396,19 @@ func (a *App) Error() error {
...
 // was already stopped before. In any case it returns the effective exit status.
 func (a *App) Stop(stopReason ExitStatus) ExitStatus {
-	select {
-	case <-a.stopped:
-	case <-a.stop:
-	default:
+	return a.stop(stopReason, nil)
+}
+
+func (a *App) stop(stopReason ExitStatus, err error) ExitStatus {
```
Comment (golangcibot) [inline lib/syncthing/syncthing.go]: field and method with the same name stop (from `typecheck`)

File: lib/syncthing/syncthing.go [hunk 2]
```diff
@@ -398,18 +396,19 @@ func (a *App) Error() error {
 // Stop stops the app and sets its exit status to given reason, unless the app
 // was already stopped before. In any case it returns the effective exit status.
 func (a *App) Stop(stopReason ExitStatus) ExitStatus {
-	select {
-	case <-a.stopped:
-	case <-a.stop:
-	default:
+	return a.stop(stopReason, nil)
```
Comment (golangcibot) [inline lib/syncthing/syncthing.go]: invalid operation: cannot call non-function a.stop (variable of type chan struct{}) (from `typecheck`)
