### PR TITLE
lib/discover: Filter locally announced addresses (fixes #7289)

### LINKED ISSUE #7289: TCP port 0 is announced in the LAN beacon
### Does your log mention database corruption?

No

### Include required information

There is code that end up making connections to tcp port 0 announced in the LAN beacon:

https://github.com/syncthing/syncthing/blob/main/lib/connections/tcp_listen.go#L171-L177

That makes clients try to connect to TCP port 0, and firewalls log those attempts - this is the main annoyance of these undesired connections.

I think that port-0 has a special meaning changing to a proper port if using a Discovery Server, but I have Global Discovery disabled in my setup, only LAN discovery. In any case, I think that  port 0 should not be announced in the LAN beacon.

LAN Beacon announcement from tcpdump:
```
17:39:04.027909 IP6 fe80::xxxxxxxxxxxx.48859 > ff12::8384.21027: UDP, length 108 
         ....
        0x0060:  8b50 6136 1213 7463 703a 2f2f 302e 302e  .Pa6..tcp://0.0.
        0x0070:  302e 303a 3232 3030 3012 0f74 6370 3a2f  0.0:22000..tcp:/
        0x0080:  2f30 2e30 2e30 2e30 3a30 1214 7175 6963  /0.0.0.0:0..quic
        0x0090:  3a2f 2f30 2e30 2e30 2e30 3a32 3230 3030  ://0.0.0.0:22000
        0x00a0:  1880 d3c8 f4c2 bdf4 fb39                 .........9
```

Typical firewall logs:
```
[104118.933309] refused connection: IN=eth0 OUT= MAC=XXXXX SRC=fe80:0000:0000:0000:6ac4:4dff:fe04:xxxx DST=fe80:0000:0000:0000:329c:23ff:fe01:xxxx LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=0 PROTO=TCP SPT=40630 DPT=0 WINDOW=65535 RES=0x00 SYN URGP=0 
```

(I reported this in #4278 but asked to open a new bug report)

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Remove unusable stuff from the local announce packet.

### CODE REVIEW

File: lib/discover/local.go [hunk 1]
```diff
@@ -281,3 +288,30 @@ func (c *localClient) registerDevice(src net.Addr, device Announce) bool {
...
+	for _, addr := range addrs {
+		u, err := url.Parse(addr)
+		if err != nil {
+			continue
+		}
+
+		tcpAddr, err := net.ResolveTCPAddr("tcp", u.Host)
+		if err != nil {
+			continue
+		}
```
Comment (imsodin) [inline lib/discover/local.go:305]: Do we want to filter out quic addresses here? There's probably no scenario where local discovery works but local tcp doesn't, and udp does, but as long as it's not definitely impossible (I don't know enough to say that) it wouldn't hurt to send them anyway.

File: lib/discover/local.go [hunk 2]
```diff
@@ -281,3 +288,30 @@ func (c *localClient) registerDevice(src net.Addr, device Announce) bool {
...
+
+		switch {
+		case len(tcpAddr.IP) == 0:
```
Comment (AudriusButkevicius) [inline lib/discover/local.go:308]: Do we not "fill" the unspecified address on the other side? We could continue to send them as long as we fill them?

File: lib/discover/local.go (hunk 1 above)
Comment (calmh) [reply lib/discover/local.go:305]: We don't filter out quic. The resolve says "tcp", but I don't think that matters.

File: lib/discover/local.go (hunk 2 above)
Comment (calmh) [reply lib/discover/local.go:308]: We don't, and I don't think we can as the local discovery packet doesn't come from a bep listening socket.

Comment (calmh) [reply lib/discover/local.go:308]: I guess in principle we could send it from the quic socket, if we listen on quic, but we currently don't. (All this predates quic support by a wide margin.)

File: lib/discover/local.go (hunk 1 above)
Comment (imsodin) [reply lib/discover/local.go:305]: My bad, I assumed this would always error for quic-schemed addresses, but `u.Host` is just `ip:port` at this point. Anyway indeed hardly relevant.

**Comment by calmh** [comment]
giphy
