### PR TITLE
lib/ignore: properly handle non-existing included ignore-files (fixes #8764)

### LINKED ISSUE #8764: Syncthing cannot load Ignore Patterns while #Include file is missing.
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
   - 1.23.0
 - browser and version, if applicable
   - synctrazor/brave
 - what happened,
   - when accepting new folder share, after inserting Ignore Patterns the `.stignore` file is created automatically but in the GUI the Ignore Patterns show as empty, however, the file is not empty.  Syncthing is also not adhering to what is in `.stignore` and syncing all files.
 - what you expected to happen instead, and
   - Sync while respecting the Ignore Patterns in `.stignore`.  Maybe attempt to find the `#include` file first
 - any steps to reproduce the problem.
   - Yes, an example is below. Accept a new share from a remote pc.  Must use the `#include` function and make sure the `#include` file does not exist on host computer.
 - how to fix it
   - manually copy the `#include` file to the host computer and Syncthing will now load and use the Ignore Patterns. All `#include` files must exist

```
//global ignore file that contains unimportant extensions and files to ignore
#include .stignoresync

//exclude larger directories
bigfolder
biggerfolder
```

### PR DESCRIPTION
**Pull request by er-pa**
In the sequence of loading ignores, the error `no such file or directory` is not being considered a fatal  error, since the `.stignore` file is allowed to not exist. However, included ignore files also tossed that same error in case those did not exist while in those cases it's actually considered an error that should impact the running-status of the folder. Changing the error when opening an included ignore file to something manually defined does fix this issue, as in it now works again as described in the Documentation.

### Testing

Add/edit a folder. Add ignore-lines with `#include .somethingnonexisting` and it should now error out properly and the folder should be stopped, instead of having the ignores not being loaded and the folder remain in a running state.

### CODE REVIEW

**Comment by er-pa** [comment]
I'll actually double-check the related test-case

File: lib/ignore/ignore.go [hunk 1]
```diff
@@ -411,7 +411,7 @@ func loadParseIncludeFile(filesystem fs.Filesystem, file string, cd ChangeDetect
 
 	fd, info, err := loadIgnoreFile(filesystem, file)
 	if err != nil {
-		return nil, err
+		return nil, parseError(fmt.Errorf("could not load included ignore file: %v", err))
```
Comment (imsodin) [inline lib/ignore/ignore.go:414]: Should use to use `%w` to preserve erro chain. And the inner error already signifies that something went wrong, the wrapping context could be more terse to shrink the overall length:

```suggestion
		return nil, parseError(fmt.Errorf("included ignore file: %w", err))
```

Comment (imsodin) [reply lib/ignore/ignore.go:414]: Actually the error is already wrapped in the calling function, so I'd say no wrapping/context is needed here at all: https://github.com/syncthing/syncthing/blob/3d94efd42785b207ddca3fb9af75d54dd863e178/lib/ignore/ignore.go#L561

File: lib/ignore/ignore_test.go [hunk 2]
```diff
@@ -197,6 +197,11 @@ func TestBadPatterns(t *testing.T) {
 		if !IsParseError(err) {
 			t.Error("Should have been a parse error:", err)
 		}
+		if strings.HasPrefix(pat, "#include") {
+			if fs.IsNotExist(err) {
+				t.Error("Includes should not toss a regular isNotExist error")
+			}
+		}
```
Comment (imsodin) [inline lib/ignore/ignore_test.go:204]: Shouldn't that be checked by the above `!IsParseError` already?

File: lib/ignore/ignore.go (hunk 1 above)
Comment (calmh) [reply lib/ignore/ignore.go:414]: So there should be a comment to this effect, but the entire point of this fix is to *not* preserve the error chain, because we treat fs.NotExist as a non-error in other places (.stignore may not exist).

Comment (imsodin) [reply lib/ignore/ignore.go:414]: Ah got it, thanks for the explanation. Maybe instead of the comment make it explicit by checking:

```suggestion
		if fs.IsNotExist(err) {
			err = errors.New("missing included file")
		}
		return nil, parseError(err)
```

I am fine either way, just a suggestion.

File: lib/ignore/ignore_test.go (hunk 2 above)
Comment (imsodin) [reply lib/ignore/ignore_test.go:204]: This comment is based on a wrong assumption, see the other comment above.

File: lib/ignore/ignore.go [hunk 3]
```diff
@@ -406,12 +406,20 @@ func loadParseIncludeFile(filesystem fs.Filesystem, file string, cd ChangeDetect
 	}
 
 	if cd.Seen(filesystem, file) {
-		return nil, parseError(fmt.Errorf("multiple include of ignore file %q", file))
+		return nil, fmt.Errorf("multiple include of ignore file %q", file)
```
Comment (calmh) [inline lib/ignore/ignore.go:409]:
```suggestion
		return nil, errors.New("multiple include")
```

(looks like the calling function adds the filename as context already)

**Comment by calmh** [comment]
(mac build error is a signing issue on the builder, I'll fix that at some point...)

**Review by calmh — APPROVED** [review]

File: lib/ignore/ignore.go [hunk 4]
```diff
@@ -406,11 +406,19 @@ func loadParseIncludeFile(filesystem fs.Filesystem, file string, cd ChangeDetect
 	}
 
 	if cd.Seen(filesystem, file) {
-		return nil, parseError(fmt.Errorf("multiple include of ignore file %q", file))
+		return nil, errors.New("multiple include")
```
Comment (imsodin) [inline lib/ignore/ignore.go:409]: Why shouldn't this be a parse error?

Comment (er-pa) [reply lib/ignore/ignore.go:409]: For the same reason as why there was no need to put the initially changed error inside a parseError, the returning error from this function is always being wrapped inside a parseError already;
`err = parseError(fmt.Errorf("failed to load include file %s: %w", includeFile, err)) `. I don't think it adds much at this point?

Comment (imsodin) [reply lib/ignore/ignore.go:409]: Thanks. (Damn I am thinking slowly (to the point of not thinking) today).
