### PR TITLE
lib/db: Fix prefixed walks (fixes #4925)

### LINKED ISSUE #4925: Deleted files within deleted directories aren't detected with FS watcher
Sometimes, the FsWatcher recognizes a directory as being deleted, but not the contents of this directory. I cannot reliably reproduce this.

Suppose I am in a shared directory, label "default". As a minimal example, I create a new folder and put a single file in it:

    mkdir newfolder
    touch newfolder/newfile

Wait ten seconds, until FsWatcher triggers a sync. The log shows correctly:

    [HU2GR] 00:01:14 VERBOSE: Folder "default" is now scanning
    [HU2GR] 00:01:14 VERBOSE: Local change detected in folder "default": modified dir newfolder
    [HU2GR] 00:01:14 VERBOSE: Local change detected in folder "default": modified file newfolder/newfile
    [HU2GR] 00:01:14 VERBOSE: Folder "default" is now idle
    [HU2GR] 00:01:14 VERBOSE: Folder "default" is now syncing
    [HU2GR] 00:01:17 VERBOSE: Folder "default" is now idle
    [HU2GR] 00:01:18 VERBOSE: Summary for folder "default" is map[localDirectories:2737 globalFiles:8590 inSyncFiles:8590 localBytes:404203037 pullErrors:0 inSyncBytes:404203037 localDeleted:546018 needSymlinks:0 needDirectories:0 needFiles:0 needDeletes:0 globalDirectories:2737 globalDeleted:882565 localFiles:8590 globalSymlinks:0 globalBytes:404203037 localSymlinks:0 needBytes:0 sequence:5339784 version:5339784 state:idle]
    [HU2GR] 00:01:33 VERBOSE: Completion for folder "default" on device ENFQI... is 99.99996833274659%
    [HU2GR] 00:01:52 VERBOSE: Device ENFQI... sent an index update for "default" with 2 items
    [HU2GR] 00:01:59 VERBOSE: Completion for folder "default" on device ENFQI... is 100%

(`ENFQI` being another computer under my control.)

If I delete the directory, like so:

    rm -r newfolder

Then sometimes only the directory will be recognized as deleted:

    [HU2GR] 00:13:14 VERBOSE: Summary for folder "default" is map[localFiles:8589 localDirectories:2737 pullErrors:0 inSyncBytes:404202845 globalFiles:8589 version:5339798 sequence:5339798 needBytes:0 globalSymlinks:0 globalDeleted:882566 needDeletes:0 state:idle globalDirectories:2737 inSyncFiles:8589 needSymlinks:0 localSymlinks:0 localDeleted:546019 needFiles:0 globalBytes:404202845 localBytes:404202845 needDirectories:0]
    [HU2GR] 00:13:16 VERBOSE: Completion for folder "default" on device ENFQI... is 100%
    [HU2GR] 00:14:31 VERBOSE: Folder "default" is now scanning
    [HU2GR] 00:14:31 VERBOSE: Local change detected in folder "default": deleted dir newfolder
    [HU2GR] 00:14:31 VERBOSE: Folder "default" is now idle
    [HU2GR] 00:14:31 VERBOSE: Folder "default" is now syncing
    [HU2GR] 00:14:34 VERBOSE: Folder "default" is now idle
    [HU2GR] 00:14:35 VERBOSE: Summary for folder "default" is map[inSyncBytes:404202717 needSymlinks:0 localDirectories:2736 version:5339799 sequence:5339799 globalDirectories:2736 localSymlinks:0 localFiles:8589 needDirectories:0 globalFiles:8589 needBytes:0 pullErrors:0 inSyncFiles:8589 localDeleted:546020 needFiles:0 needDeletes:0 globalDeleted:882567 globalBytes:404202717 state:idle globalSymlinks:0 localBytes:404202717]
    [HU2GR] 00:14:37 VERBOSE: Completion for folder "default" on device ENFQI... is 95%

The `*Directories` gets decremented, but not the `*Files`. I have to manually sync or wait for the periodic scan to propagate the deleted file. Until then, `ENFQI` (and in fact every other machine that was online at this moment) keeps stuck at 95%. What is happening here?

### Version Information

Syncthing Version: v0.14.47
OS Version: Gentoo Linux, amd64 (x86_64), fully updated (mostly stable packages) a few days ago.
File System in use: BTRFS (in case this is relevant)

### PR DESCRIPTION
**Pull request by imsodin**
### Purpose

Currently walking the db with a prefix is broken in the presence of a file, that has the same prefix, as the entire walk is aborted when such a file is encountered.

### Testing

Added new unit test.

### CODE REVIEW

File: lib/db/set_test.go [hunk 1]
```diff
@@ -892,6 +892,57 @@ func TestWithHaveSequence(t *testing.T) {
...
+
+	i = 0
+	s.WithPrefixedGlobalTruncated("dir/", func(fi db.FileIntf) bool {
+		i++
+		return true
+	})
+	if i != 1 {
+		t.Errorf(`Expected 1, got %v global items below "dir/"`, i)
+	}
+}
```
Comment (AudriusButkevicius) [inline lib/db/set_test.go]: Just out of curiosity, was this failing previously on second time iterating? If yes, that would mean the iterators are somehow stateful? If not, I am confused why you do the same thing twice.

File: lib/db/leveldb_dbinstance.go [hunk 2]
```diff
@@ -923,6 +903,19 @@ func unmarshalTrunc(bs []byte, truncate bool) (FileIntf, error) {
...
 }
 
+func unmarshalVersionList(data []byte) (VersionList, bool) {
+	var vl VersionList
+	if err := vl.Unmarshal(data); err != nil {
+		l.Debugln("unmarshal error:", err)
+		return VersionList{}, false
+	}
+	if len(vl.Versions) == 0 {
+		l.Debugln("empty version list")
```
Comment (AudriusButkevicius) [inline lib/db/leveldb_dbinstance.go]: I can't see how these debug logs are useful, they would appear thousands and thousands of times in a db walk, amd include no indication which file they are talking about etc. I'd just remove them.

File: lib/db/leveldb_dbinstance.go [hunk 3]
```diff
@@ -186,20 +186,27 @@ func (db *Instance) removeSequences(folder []byte, fs []protocol.FileInfo) {
...
-	slashedPrefix := prefix
-	if !bytes.HasSuffix(prefix, []byte{'/'}) {
-		slashedPrefix = append(slashedPrefix, '/')
-	}
-
 	for dbi.Next() {
 		name := db.deviceKeyName(dbi.Key())
-		if len(prefix) > 0 && !bytes.Equal(name, prefix) && !bytes.HasPrefix(name, slashedPrefix) {
+		if len(prefix) > 0 && !bytes.HasPrefix(name, prefix) {
 			return
```
Comment (AudriusButkevicius) [inline lib/db/leveldb_dbinstance.go]: So this no longer walks the directory itself? I think that's not how it should work, as I think walk returns the directory.

File: lib/db/leveldb_dbinstance.go [hunk 4]
```diff
@@ -306,75 +319,53 @@ func (db *Instance) getGlobal(folder, file []byte, truncate bool) (FileIntf, boo
 		return nil, false
 	}
 
-	var vl VersionList
-	err = vl.Unmarshal(bs)
-	if err == leveldb.ErrNotFound {
-		return nil, false
-	}
```
Comment (AudriusButkevicius) [inline lib/db/leveldb_dbinstance.go]: I wonder why this error check is here. Seems like an unprobable error to be returned by Unmarshal?

File: lib/db/leveldb_dbinstance.go (hunk 2 above)
Comment (calmh) [reply lib/db/leveldb_dbinstance.go]: It's the same territory as the error above, it's useless-ish but it's never supposed to happen

File: lib/db/leveldb_dbinstance.go (hunk 3 above)
Comment (calmh) [reply lib/db/leveldb_dbinstance.go]: I think this handled at the top.

**Comment by imsodin** [comment]
@calmh Exactly because the previous implementation didn't handle it correctly/there were no tests specifying the desired behaviour, I just implemented the behaviour I am used to from rsync. I can easily change it to include `dir` regardless of whether `dir` or `dir/` is given as prefix. Should I?

**Comment by calmh** [comment]
Yes, I think so. I don't offhand know whether we always/never/sometimes pass the slash, but I don't think we ever use the prefixed iteration to mean anything else than "everything" (no prefix) or "this directory and children" (any prefix). So accepting both and behaving the same in both cases seems sane

File: lib/db/leveldb_dbinstance.go (hunk 2 above)
Comment (AudriusButkevicius) [reply lib/db/leveldb_dbinstance.go]: Then change it to a panic?

**Comment by imsodin** [comment]
Just changed the behaviour to always iterate over the prefix, and thus discovered a small bug in `model.GlobalDirectoryTree` and a negligence in a model test: An index with only files, not parent directory is used. As far as I know this should never happen in reality (i.e. parents must exist). I see two options:

1. When updating files in the database, always check that parent directories exist.
2. As before, just ignore missing parent directories when walking the db (e.g. if prefix is `foo/bar` and `foo/bar` is not in the db, but `foo/bar/baz` is, just iterate over `foo/bar/baz`).

Opinions?

**Comment by imsodin** [comment]
I just went with previous behaviour. The `lib/db/benchmark_test.go` change is unrelated, it just floods logs with db debugging enabled (as in MBs). The [change in model.go](https://github.com/syncthing/syncthing/pull/4940/files#diff-1df9805b2381b6288b220226f82d5dc9L2406) is a fix to keep existing tests passing (i.e. the previous condition was useless, but for reasons unknown tests still passed).

File: lib/db/benchmark_test.go [hunk 5]
```diff
@@ -36,9 +40,9 @@ func init() {
 	oneFile = firstHalf[middle-1 : middle]
 
 	ldb, _ := tempDB()
-	s = db.NewFileSet("test)", fs.NewFilesystem(fs.FilesystemTypeBasic, "."), ldb)
-	replace(s, remoteDevice0, files)
-	replace(s, protocol.LocalDeviceID, firstHalf)
+	benchS = db.NewFileSet("test)", fs.NewFilesystem(fs.FilesystemTypeBasic, "."), ldb)
```
Comment (AudriusButkevicius) [inline lib/db/benchmark_test.go]: Bracket in string

Comment (imsodin) [reply lib/db/benchmark_test.go]: Yeah, that's common to all (most?) lib/db tests - no idea why, I just kept it when c&p-ing.

Comment (calmh) [reply lib/db/benchmark_test.go]: I think it's just a mistake that's been perpetuated. I've cleaned it out of the other test file in another pr
