### PR TITLE
lib: Handle adding enc folders on an existing conn (fixes #7509)

### LINKED ISSUE #7509: Sharing the first folder to an untrusted device on an established connection sends plain-text
Was discovered in https://forum.syncthing.net/t/problem-adding-second-trusted-device-connected-to-untrusted-device/16538

> 
> Prerequisites
> 
>     Devices A+B: Discovery and nat traversal deactivated, Relaying on (Windows x32)
>     Device U: Discovery, nat traversal and relaying deactivated (Ubuntu 20.04 64bit)
>     All Devices on v1.15.0-rc.5, Windows machines using SyncTrayzor
>     Devices A and B are connected to U. Status: Connected (unused)
> 
> Steps to reproduce
> 
>     Add new Folder to Device A and share it with encryption password
>     Receive Folder on U and add it.
> 
> => U will now show “Up to date” but will not receive any data. A will show “Syncing” for the device and “up to date” for the folder while not sending any data.
> 
>     Pause the new Folder on A and resume it
> 
> => A and U will now sync but U will now have the unencrypted data at the chosen path.

A connection handles multiple folders, every single can be encrypted or not. Which folders are or not encrypted is set when the connection is created. At the time the code was written that was ok, as we dropped a connections when any folder changed. Now we don't anymore, thus adding an encrypted folder doesn't make that connection encrypted until the connection is dropped (restart, device pause, ...).

Should this go into the changelog? It's definitely a "note-worthy" bug, but the untrusted feature is still in testing/preview. Not sure.

The point about having to pause and resume the folder to make anything happen is unrelated (did repro but don't yet know why it happens).

### PR DESCRIPTION
**Pull request by imsodin**
Fixes #7509 by adding a method to the connection to set new folder passwords. This means that any connection may become (partly) encrypted. Thus there's no longer two separate factory methods, but every connection is a `encryptedConnection`.

The passwords on the connection are (re-)set when sending cluster-configs, meaning when a new connection is added, when a new folder is added or when a folder changes.

### CODE REVIEW

File: lib/model/model.go [hunk 1]
```diff
@@ -2409,13 +2409,15 @@ func (m *model) numHashers(folder string) int {
 
 // generateClusterConfig returns a ClusterConfigMessage that is correct for
 // the given peer device
```
Comment (calmh) [inline lib/model/model.go:2411]:
```suggestion
// generateClusterConfig returns a ClusterConfigMessage and the set of folder passwords for
// the given peer device
```

File: lib/protocol/encryption.go [hunk 2]
```diff
@@ -135,42 +136,46 @@ func (e encryptedModel) ClusterConfig(deviceID DeviceID, config ClusterConfig) e
...
 }
 
 // The encryptedConnection sits between the model and the encrypted device. It
 // encrypts outgoing metadata and decrypts incoming responses.
 type encryptedConnection struct {
 	ConnectionInfo
-	conn       Connection
-	folderKeys map[string]*[keySize]byte // folder ID -> key
+	conn *rawConnection
+	em   *encryptedModel
```
Comment (calmh) [inline lib/protocol/encryption.go:148]: I think this should be a pointer to the folderKeyRegistry directly instead of reaching into the encryptedModel

File: lib/protocol/encryption.go [hunk 3]
```diff
@@ -590,3 +595,27 @@ func isEncryptedParentFromComponents(pathComponents []string) bool {
...
+	keys map[string]*[keySize]byte // folder ID -> key
+	mut  sync.RWMutex
+}
+
+func newFolderKeyRegistry() *folderKeyRegistry {
+	return &folderKeyRegistry{
+		keys: make(map[string]*[keySize]byte),
+	}
+}
+
```
Comment (calmh) [inline lib/protocol/encryption.go:609]: Don't really need a constructor for this one, nil map is fine until reset() happens

File: lib/protocol/encryption.go [hunk 4]
```diff
@@ -590,3 +595,27 @@ func isEncryptedParentFromComponents(pathComponents []string) bool {
...
+func (r *folderKeyRegistry) get(folder string) (*[keySize]byte, bool) {
+	r.mut.RLock()
+	key, ok := r.keys[folder]
+	r.mut.RUnlock()
+	return key, ok
+}
+
+func (r *folderKeyRegistry) reset(passwords map[string]string) {
```
Comment (calmh) [inline lib/protocol/encryption.go:617]: `setPasswords`? `reset` sounds like remove all passwords to me

File: lib/protocol/protocol.go [hunk 5]
```diff
@@ -140,6 +140,7 @@ type RequestResponse interface {
 
 type Connection interface {
 	Start()
+	ResetFolderPasswords(passwords map[string]string)
```
Comment (calmh) [inline lib/protocol/protocol.go:143]: Likewise, maybe `SetFolderPasswords`?

**Review by calmh — COMMENTED** [review]
Also fixes #7198 I think

File: lib/protocol/encryption.go (hunk 4 above)
Comment (imsodin) [reply lib/protocol/encryption.go:617]: I was just wondering whether one might misunderstand the end-result: It is exactly `passwords` but it could also be the previous state with the elements of `passwords` applied on top of it (i.e. missing passwords remaining). `reset` feels a bit more clear in that respect than just `set`. Maybe `replace` instead?

**Comment by imsodin** [comment]
#7198 sounds like the issue I am seeing when reproducing the issue here (having to pause/resume the folder before indexes get exchanged). And I am still seeing it with the PR applied.

File: lib/protocol/encryption.go (hunk 4 above)
Comment (calmh) [reply lib/protocol/encryption.go:617]: I think `set` implies replace, but I'm fine with `replace` as well.

File: lib/protocol/encryption.go (hunk 3 above)
Comment (imsodin) [reply lib/protocol/encryption.go:609]: I don't really want a nil-check in `folderKeyRegistry.get` though.

Comment (calmh) [reply lib/protocol/encryption.go:609]: Why would you need one?

Comment (imsodin) [reply lib/protocol/encryption.go:609]: I'd expect `key, ok := r.keys[folder]` to panic. And without checking I am not 100% that `model.AddConnection` is guaranteed to initialize the passwords before any message comes in from a remote. Expressing that thought makes it clear that I should keep initializing passwords when creating the connection. Likely it's all irrelevant practically, as the early messages aren't encrypted, but still.

Comment (calmh) [reply lib/protocol/encryption.go]: It doesn't panic though, a nil map is equivalent to a non-nil but empty map when reading.

Comment (imsodin) [reply lib/protocol/encryption.go]: Cool, wasn't aware of that. I didn't really internalize that aspect of go (treating nil as a valid state), I treat nil as "do not touch".
Any ways, it does now get initialized at connection construction time with a valid map of passwords.

**Review by calmh — APPROVED** [review]
