### PR TITLE
Refuse files with unknown bits set (fixes #1276)

### LINKED ISSUE #1276: Refuse files with unknown bits set
If you have a symlink (on Linux at least) in the directory that's being synced, the symlink target after some time will have the date Jan, 1 1970 (i.e. unix timestamp is zero) and chmodded to 666. I can't tell exactly when this happens because the timestamp is erased but one day my script in ~/bin is executable and another day it's chmodded to 666 and I can't execute it. I figured out it's because of symlinks (two symlinks in the same ~/bin dir point to the script, it distinguishes the command by $0 argument like busybox does) because another link that points to the file outside of the syncing directory got the same timestamp and access rights. So Syncthing follows the link somehow wrong I guess. I changed the mod and touched the file on both sides and it was ok for some time (i.e. several rescans) so I though it was just a temporary error but then it happened again. I don't see a pattern but if someone also observe the same behavior please comment.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

File: internal/model/model.go [hunk 1]
```diff
@@ -485,7 +485,13 @@ func (m *Model) Index(deviceID protocol.DeviceID, folder string, fs []protocol.F
 
 	for i := 0; i < len(fs); {
 		lamport.Default.Tick(fs[i].Version)
-		if symlinkInvalid(fs[i].IsSymlink()) {
+		if fs[i].Flags^(fs[i].Flags&protocol.FlagsAll) > 0 {
```
Comment (calmh) [inline internal/model/model.go]: `fs[i] &^ protocol.FlagsAll != 0`?

**Comment by AudriusButkevicius** [comment]
Done.
Added tests too, as this is quite important.
