### PR TITLE
Sanitize rescan interval values (fixes #1978)

### LINKED ISSUE #1978: Entering a large number into the renew interval of a share cause Syncthing to crash on startup
When entering a large enough value (I tried `60000000000`) into the rescanIntervalS property of a shared folder, Syncthing will crash during startup with the following message:

     panic: invalid argument to Int63n

Which is presumably triggered by [this piece of code](https://golang.org/src/math/rand/rand.go#L61) when generating a random number during startup to decide when to perform the initial scan of the folder. (I'm guessing, I don't know Go and I don't know how Syncthing handles startup)

This issue can be reproduced by directly editing config.xml or by changing the value through the web UI, and will be triggered upon the next start up.

I've only tested this on v0.11.9, Linux (64 bit).

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -28,6 +28,7 @@ import (
 const (
 	OldestHandledVersion = 5
 	CurrentVersion       = 10
+	MaxRescanIntervalS   = 365 * 24 * 60
```
Comment (alex2108) [inline internal/config/config.go]: I think there is another * 60 missing ;)

Comment (calmh) [inline internal/config/config.go]: :panda_face: Indeed
