### PR TITLE
lib/connections: Do not leak FDs, fix address copy (fixes #5767)

### LINKED ISSUE #5767: Runs out of file descriptors since QUIC addition
```
2019/06/09 10:46:32 http: TLS handshake error from [::1]:50326: remote error: tls: unknown certificate
2019/06/09 10:46:32 http: Accept error: accept tcp [::]:8384: accept: too many open files; retrying in 5ms
2019/06/09 10:46:32 http: Accept error: accept tcp [::]:8384: accept: too many open files; retrying in 10ms
2019/06/09 10:46:32 http: Accept error: accept tcp [::]:8384: accept: too many open files; retrying in 20ms
2019/06/09 10:46:32 http: TLS handshake error from [::1]:50328: remote error: tls: unknown certificate
2019/06/09 10:46:44 http: Accept error: accept tcp [::]:8384: accept: too many open files; retrying in 5ms
2019/06/09 10:46:44 http: TLS handshake error from [::1]:50355: remote error: tls: unknown certificate
2019/06/09 10:46:55 http: Accept error: accept tcp [::]:8384: accept: too many open files; retrying in 5ms
2019/06/09 10:46:55 http: TLS handshake error from [::1]:50363: remote error: tls: unknown certificate
2019/06/09 10:47:04 http: Accept error: accept tcp [::]:8384: accept: too many open files; retrying in 5ms
2019/06/09 10:47:04 http: TLS handshake error from [::1]:50373: remote error: tls: unknown certificate
```

```
COMMAND   PID USER   FD     TYPE             DEVICE   SIZE/OFF    NODE NAME
syncthing 507   jb  cwd      DIR                1,4        864       2 /
syncthing 507   jb  txt      REG                1,4   21005988 1209879 /Users/jb/bin/syncthing
syncthing 507   jb  txt      REG                1,4      21024 1603827 /Library/Preferences/Logging/.plist-cache.13bzgK1z
syncthing 507   jb  txt      REG                1,4     973824  706375 /usr/lib/dyld
syncthing 507   jb  txt      REG                1,4   27154336  720553 /usr/share/icu/icudt62l.dat
syncthing 507   jb    0r     CHR                3,2        0t0     313 /dev/null
syncthing 507   jb    1     PIPE 0xde648a63368c87d7      65536         ->0xde648a63368c8417
syncthing 507   jb    2     PIPE 0xde648a63368c8717      16384         ->0xde648a63368c8897
syncthing 507   jb    3r     CHR               14,1 0t47472640     589 /dev/urandom
syncthing 507   jb    4u  KQUEUE                                       count=0, state=0xa
syncthing 507   jb    5u     REG                1,4          0 1201738 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/LOCK
syncthing 507   jb    6w     REG                1,4     102621 1201739 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/LOG
syncthing 507   jb    7r     REG                1,4    2111357 2867839 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000605.ldb
syncthing 507   jb    8w     REG                1,4      71372 1605251 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/MANIFEST-000229
syncthing 507   jb    9r     REG                1,4    2117163 2867844 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000610.ldb
syncthing 507   jb   10r     REG                1,4     651530 2867819 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000603.ldb
syncthing 507   jb   11u   systm 0xde648a6338b4ccb7        0t0         [ctl com.apple.netsrc id 8 unit 23]
syncthing 507   jb   12u    unix 0xde648a634ba536ef        0t0         ->0xde648a634ba52fe7
syncthing 507   jb   13r     REG                1,4    2125379 2867838 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000604.ldb
syncthing 507   jb   14r     REG                1,4    2107926 2867840 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000606.ldb
syncthing 507   jb   15r     REG                1,4    2106936 2867841 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000607.ldb
syncthing 507   jb   16r     REG                1,4    2109751 2867845 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000611.ldb
syncthing 507   jb   17r     REG                1,4    2102375 2867842 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000608.ldb
syncthing 507   jb   18u    IPv4 0xde648a6332cf67df        0t0     UDP *:59503
syncthing 507   jb   19u    IPv4 0xde648a6332cf6d4f        0t0     UDP *:21027
syncthing 507   jb   20u    IPv6 0xde648a6332cf7007        0t0     UDP *:59504
syncthing 507   jb   21r     REG                1,4    2103296 2867843 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000609.ldb
syncthing 507   jb   22u    IPv6 0xde648a6332cf72bf        0t0     UDP *:21027
syncthing 507   jb   23u    IPv6 0xde648a6334014457        0t0     TCP *:8384 (LISTEN)
syncthing 507   jb   24r     REG                1,4    2130515 2867470 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000501.ldb
syncthing 507   jb   25u    IPv6 0xde648a6330a2ed4f        0t0     UDP *:60423
syncthing 507   jb   26u    IPv6 0xde648a6332cf6a97        0t0     UDP *:59505
syncthing 507   jb   27r     REG                1,4    2103100 2867846 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000612.ldb
syncthing 507   jb   28r     REG                1,4     436833 2867847 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000613.ldb
syncthing 507   jb   29r     REG                1,4    2110574 2867797 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000581.ldb
syncthing 507   jb   30u    IPv6 0xde648a6331181487        0t0     UDP *:53932
syncthing 507   jb   31r     REG                1,4     534804 2867543 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000572.ldb
syncthing 507   jb   32r     REG                1,4    2107952 2867476 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000507.ldb
syncthing 507   jb   33r     REG                1,4    2108641 2867795 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000579.ldb
syncthing 507   jb   34u    IPv6 0xde648a63309c226f        0t0     UDP *:63738
syncthing 507   jb   35u    IPv6 0xde648a632ec2330f        0t0     UDP *:51465
syncthing 507   jb   36r     REG                1,4    2110570 2867796 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000580.ldb
syncthing 507   jb   37u    IPv6 0xde648a6332cf521f        0t0     UDP *:61344
syncthing 507   jb   38u    IPv6 0xde648a6332cf7ae7        0t0     UDP *:62407
syncthing 507   jb   39u    IPv6 0xde648a632ec20cff        0t0     UDP *:64778
syncthing 507   jb   40u    IPv6 0xde648a6330a30b37        0t0     UDP *:58184
syncthing 507   jb   41u    IPv6 0xde648a6331185b37        0t0     UDP *:65063
syncthing 507   jb   42u    IPv6 0xde648a6332cf5fb7        0t0     UDP *:63986
syncthing 507   jb   43u    IPv6 0xde648a6330a2f2bf        0t0     UDP *:61574
syncthing 507   jb   44u    IPv6 0xde648a6331183527        0t0     UDP *:65064
syncthing 507   jb   45u    IPv6 0xde648a6331185057        0t0     UDP *:58504
syncthing 507   jb   46u    IPv6 0xde648a632ec2387f        0t0     UDP *:64649
syncthing 507   jb   47u    IPv6 0xde648a6330a2dcff        0t0     UDP *:53679
syncthing 507   jb   48u    IPv6 0xde648a6331183a97        0t0     UDP *:60359
syncthing 507   jb   49u    IPv6 0xde648a6331184007        0t0     UDP *:62425
syncthing 507   jb   50u    IPv6 0xde648a632ec2435f        0t0     UDP *:62628
syncthing 507   jb   51u    IPv6 0xde648a63309bff17        0t0     UDP *:53365
syncthing 507   jb   52w     REG                1,4   16260319 2867526 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000555.log
syncthing 507   jb   53r     REG                1,4    2120182 2867469 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000500.ldb
syncthing 507   jb   54u    IPv6 0xde648a6330a2c1cf        0t0     UDP *:62508
syncthing 507   jb   55u    IPv6 0xde648a63352e930f        0t0     UDP *:56174
syncthing 507   jb   56u    IPv6 0xde648a63309c4def        0t0     UDP *:61668
syncthing 507   jb   57u    IPv6 0xde648a634a8a3b37        0t0     UDP *:64281
syncthing 507   jb   58u    IPv6 0xde648a63352e7a97        0t0     UDP *:50080
syncthing 507   jb   59u    IPv6 0xde648a63352e573f        0t0     UDP *:63386
syncthing 507   jb   60u    IPv6 0xde648a634a8a435f        0t0     UDP *:61308
syncthing 507   jb   61u    IPv6 0xde648a6330a2f82f        0t0     UDP *:60465
syncthing 507   jb   62u    IPv6 0xde648a63505f2d9f        0t0     UDP *:62939
syncthing 507   jb   63u    IPv6 0xde648a63311811cf        0t0     UDP *:61998
syncthing 507   jb   64u    IPv6 0xde648a634a89f73f        0t0     UDP *:58149
syncthing 507   jb   65r     REG                1,4    2121699 2867475 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000506.ldb
syncthing 507   jb   66u    IPv6 0xde648a63352e5f67        0t0     UDP *:60152
syncthing 507   jb   67u    IPv6 0xde648a63505f021f        0t0     UDP *:50200
syncthing 507   jb   68u    IPv6 0xde648a63505f078f        0t0     UDP *:63326
syncthing 507   jb   69u    IPv6 0xde648a634cedca47        0t0     UDP *:56819
syncthing 507   jb   70u    IPv6 0xde648a63352e6fb7        0t0     UDP *:55302
syncthing 507   jb   71u    IPv6 0xde648a633118221f        0t0     UDP *:60590
syncthing 507   jb   72u    IPv6 0xde648a634cedd26f        0t0     UDP *:64916
syncthing 507   jb   73u    IPv6 0xde648a63352e726f        0t0     UDP *:59852
syncthing 507   jb   74u    IPv6 0xde648a6330a2f577        0t0     UDP *:53863
syncthing 507   jb   75u    IPv6 0xde648a63352e9def        0t0     UDP *:64519
syncthing 507   jb   76u    IPv6 0xde648a63309c4057        0t0     UDP *:52336
syncthing 507   jb   77u    IPv6 0xde648a6331182fb7        0t0     UDP *:61670
syncthing 507   jb   78u    IPv6 0xde648a632ec1f1cf        0t0     UDP *:50024
syncthing 507   jb   79u    IPv6 0xde648a632ec2078f        0t0     UDP *:63098
syncthing 507   jb   80u    IPv6 0xde648a6332cf4487        0t0     UDP *:59260
syncthing 507   jb   81u    IPv6 0xde648a6330a2c9f7        0t0     UDP *:62787
syncthing 507   jb   82u    IPv6 0xde648a63309c535f        0t0     UDP *:60430
syncthing 507   jb   83u    IPv6 0xde648a632ec1f487        0t0     UDP *:56336
syncthing 507   jb   84u    IPv6 0xde648a632ec2021f        0t0     UDP *:50931
syncthing 507   jb   85u    IPv6 0xde648a63352e7527        0t0     UDP *:62219
syncthing 507   jb   86u    IPv6 0xde648a63352e9b37        0t0     UDP *:52304
syncthing 507   jb   87u    IPv6 0xde648a6332cf8b37        0t0     UDP *:53774
syncthing 507   jb   88u    IPv6 0xde648a6330a2da47        0t0     UDP *:60665
syncthing 507   jb   89u    IPv6 0xde648a63352e64d7        0t0     UDP *:58242
syncthing 507   jb   90u    IPv6 0xde648a633118587f        0t0     UDP *:51400
syncthing 507   jb   91u    IPv6 0xde648a6330a2ccaf        0t0     UDP *:63086
syncthing 507   jb   92u    IPv6 0xde648a63309c01cf        0t0     UDP *:56082
syncthing 507   jb   93u    IPv6 0xde648a632ec2126f        0t0     UDP *:52829
syncthing 507   jb   94u    IPv6 0xde648a63352e95c7        0t0     UDP *:52305
syncthing 507   jb   95u    IPv6 0xde648a63309c0caf        0t0     UDP *:65094
syncthing 507   jb   96u    IPv6 0xde648a63352e77df        0t0     UDP *:64163
syncthing 507   jb   97u    IPv6 0xde648a634a8a021f        0t0     UDP *:65462
syncthing 507   jb   98u    IPv6 0xde648a6330a2d4d7        0t0     UDP *:50523
syncthing 507   jb   99u    IPv6 0xde648a634a8a0fb7        0t0     UDP *:54332
syncthing 507   jb  100u    IPv6 0xde648a63309c487f        0t0     UDP *:50516
syncthing 507   jb  101u    IPv6 0xde648a63309c58cf        0t0     UDP *:62024
syncthing 507   jb  102u    IPv6 0xde648a634a8a1d4f        0t0     UDP *:59508
syncthing 507   jb  103u    IPv6 0xde648a63352e8d9f        0t0     UDP *:62819
syncthing 507   jb  104u    IPv6 0xde648a63311868cf        0t0     UDP *:62428
syncthing 507   jb  105u    IPv6 0xde648a634a8a126f        0t0     UDP *:54406
syncthing 507   jb  106u    IPv6 0xde648a63309c14d7        0t0     UDP *:53943
syncthing 507   jb  107u    IPv6 0xde648a632ec22577        0t0     UDP *:49903
syncthing 507   jb  108u    IPv6 0xde648a63309c0487        0t0     UDP *:59078
syncthing 507   jb  109u    IPv6 0xde648a63311837df        0t0     UDP *:58483
syncthing 507   jb  110u    IPv6 0xde648a63309c178f        0t0     UDP *:52380
syncthing 507   jb  111u    IPv6 0xde648a634a8a330f        0t0     UDP *:58284
syncthing 507   jb  112u    IPv6 0xde648a632ec248cf        0t0     UDP *:65114
syncthing 507   jb  113u    IPv6 0xde648a634a8a2007        0t0     UDP *:50279
syncthing 507   jb  114u    IPv6 0xde648a63505f2007        0t0     UDP *:63208
syncthing 507   jb  115u    IPv6 0xde648a6330a3135f        0t0     UDP *:65456
syncthing 507   jb  116u    IPv6 0xde648a634a8a282f        0t0     UDP *:61724
syncthing 507   jb  117u    IPv6 0xde648a633118530f        0t0     UDP *:58251
syncthing 507   jb  118u    IPv6 0xde648a6330a3030f        0t0     UDP *:63128
syncthing 507   jb  119u    IPv6 0xde648a63352e59f7        0t0     UDP *:50734
syncthing 507   jb  120u    IPv6 0xde648a63311824d7        0t0     UDP *:64063
syncthing 507   jb  121u    IPv6 0xde648a63352e9057        0t0     UDP *:52124
syncthing 507   jb  122u    IPv6 0xde648a6330a3087f        0t0     UDP *:61254
syncthing 507   jb  123u    IPv6 0xde648a6332cf4f67        0t0     UDP *:49650
syncthing 507   jb  124u    IPv6 0xde648a634a8a40a7        0t0     UDP *:53180
syncthing 507   jb  125u    IPv6 0xde648a6331181f67        0t0     UDP *:49957
syncthing 507   jb  126u    IPv6 0xde648a6330a2d21f        0t0     UDP *:57078
syncthing 507   jb  127u    IPv6 0xde648a6330a2fd9f        0t0     UDP *:65141
syncthing 507   jb  128u    IPv6 0xde648a63352e621f        0t0     UDP *:50221
syncthing 507   jb  129u    IPv6 0xde648a63309c2527        0t0     UDP *:61038
syncthing 507   jb  130u    IPv6 0xde648a634a89f487        0t0     UDP *:52525
syncthing 507   jb  131u    IPv6 0xde648a63505ef1cf        0t0     UDP *:50562
syncthing 507   jb  132u    IPv6 0xde648a63309c1cff        0t0     UDP *:55489
syncthing 507   jb  133u    IPv6 0xde648a63311819f7        0t0     UDP *:58850
syncthing 507   jb  134u    IPv6 0xde648a632ec1ff67        0t0     UDP *:49972
syncthing 507   jb  135u    IPv6 0xde648a634a8a35c7        0t0     UDP *:62197
syncthing 507   jb  136u    IPv6 0xde648a632ec22007        0t0     UDP *:54187
syncthing 507   jb  137u    IPv6 0xde648a63505f3def        0t0     UDP *:59792
syncthing 507   jb  138u    IPv6 0xde648a634a8a4617        0t0     UDP *:55036
syncthing 507   jb  139u    IPv6 0xde648a634cedb73f        0t0     UDP *:52595
syncthing 507   jb  140u    IPv6 0xde648a63309c0f67        0t0     UDP *:50132
syncthing 507   jb  141u    IPv6 0xde648a63505f04d7        0t0     UDP *:55282
syncthing 507   jb  142u    IPv6 0xde648a6330a2c73f        0t0     UDP *:61544
syncthing 507   jb  143u    IPv6 0xde648a634a8a3def        0t0     UDP *:57052
syncthing 507   jb  144u    IPv6 0xde648a63505f2ae7        0t0     UDP *:62282
syncthing 507   jb  145u    IPv6 0xde648a634cee035f        0t0     UDP *:65130
syncthing 507   jb  146u    IPv6 0xde648a6332cf5cff        0t0     UDP *:63725
syncthing 507   jb  147u    IPv6 0xde648a6332cf935f        0t0     UDP *:57697
syncthing 507   jb  148u    IPv6 0xde648a63505f0a47        0t0     UDP *:56463
syncthing 507   jb  149u    IPv6 0xde648a63505f35c7        0t0     UDP *:57155
syncthing 507   jb  150u    IPv6 0xde648a6330a2c487        0t0     UDP *:51897
syncthing 507   jb  151u    IPv6 0xde648a634cede007        0t0     UDP *:60699
syncthing 507   jb  152u    IPv6 0xde648a632ec217df        0t0     UDP *:63111
syncthing 507   jb  153u    IPv6 0xde648a63505ef9f7        0t0     UDP *:54308
syncthing 507   jb  154u    IPv6 0xde648a63505eff67        0t0     UDP *:58538
syncthing 507   jb  155u    IPv6 0xde648a63505f1d4f        0t0     UDP *:64373
syncthing 507   jb  156u    IPv6 0xde648a634a8a1a97        0t0     UDP *:63623
syncthing 507   jb  157u    IPv6 0xde648a63505f1527        0t0     UDP *:50183
syncthing 507   jb  158u    IPv6 0xde648a6332cf7577        0t0     UDP *:51911
syncthing 507   jb  159u    IPv6 0xde648a63352e8ae7        0t0     UDP *:60319
syncthing 507   jb  160u    IPv6 0xde648a6332cf9b87        0t0     UDP *:64131
syncthing 507   jb  161u    IPv6 0xde648a63505f126f        0t0     UDP *:62874
syncthing 507   jb  162u    IPv6 0xde648a634cee0b87        0t0     UDP *:54135
syncthing 507   jb  163u    IPv6 0xde648a634cee00a7        0t0     UDP *:62761
syncthing 507   jb  164r     REG                1,4    2103680 2867468 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000499.ldb
syncthing 507   jb  165u    IPv6 0xde648a63505f0cff        0t0     UDP *:50835
syncthing 507   jb  166u    IPv6 0xde648a633118173f        0t0     UDP *:50019
syncthing 507   jb  167r     REG                1,4    2105735 2867477 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000508.ldb
syncthing 507   jb  168u    IPv6 0xde648a634a8a4b87        0t0     UDP *:53119
syncthing 507   jb  169u    IPv6 0xde648a634a8a2d9f        0t0     UDP *:55851
syncthing 507   jb  170u    IPv6 0xde648a634a89ef17        0t0     UDP *:58144
syncthing 507   jb  171u    IPv6 0xde648a6331185def        0t0     UDP *:63895
syncthing 507   jb  172u    IPv6 0xde648a634a8a3057        0t0     UDP *:54344
syncthing 507   jb  173u    IPv6 0xde648a63309c3ae7        0t0     UDP *:60584
syncthing 507   jb  174u    IPv6 0xde648a634cedb9f7        0t0     UDP *:65043
syncthing 507   jb  175u    IPv6 0xde648a634cedbcaf        0t0     UDP *:61763
syncthing 507   jb  176u    IPv6 0xde648a634a8a078f        0t0     UDP *:59077
syncthing 507   jb  177u    IPv6 0xde648a6331182cff        0t0     UDP *:54727
syncthing 507   jb  178u    IPv6 0xde648a634cedf87f        0t0     UDP *:62752
syncthing 507   jb  179u    IPv6 0xde648a63352e5caf        0t0     UDP *:54360
syncthing 507   jb  180r     REG                1,4    2149690 2867790 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000574.ldb
syncthing 507   jb  181r     REG                1,4    2143496 2867800 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000584.ldb
syncthing 507   jb  182r     REG                1,4    2110208 2867792 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000576.ldb
syncthing 507   jb  183r     REG                1,4    2129188 2867801 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000585.ldb
syncthing 507   jb  184r     REG                1,4    2121435 2867789 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000573.ldb
syncthing 507   jb  185u    IPv6 0xde648a6332cf4caf        0t0     UDP *:56564
syncthing 507   jb  186u    IPv6 0xde648a634cedfdef        0t0     UDP *:53558
syncthing 507   jb  187r     REG                1,4    2116956 2867808 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000592.ldb
syncthing 507   jb  188r     REG                1,4    2117194 2867813 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000597.ldb
syncthing 507   jb  189u    IPv6 0xde648a634cedb487        0t0     UDP *:49767
syncthing 507   jb  190r     REG                1,4    2116402 2867814 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000598.ldb
syncthing 507   jb  191r     REG                1,4    2124453 2867817 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000601.ldb
syncthing 507   jb  192r     REG                1,4    2125467 2867818 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000602.ldb
syncthing 507   jb  193u    IPv6 0xde648a634cedd7df        0t0     UDP *:63796
syncthing 507   jb  194r     REG                1,4    2116739 2867807 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000591.ldb
syncthing 507   jb  195r     REG                1,4    2115956 2867804 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000588.ldb
syncthing 507   jb  196u    IPv6 0xde648a634cedcfb7        0t0     UDP *:63322
syncthing 507   jb  197r     REG                1,4    2117630 2867812 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000596.ldb
syncthing 507   jb  198u    IPv6 0xde648a634a89ff67        0t0     UDP *:57374
syncthing 507   jb  199u    IPv6 0xde648a63505f282f        0t0     UDP *:62531
syncthing 507   jb  200r     REG                1,4    2120703 2867816 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000600.ldb
syncthing 507   jb  201u    IPv6 0xde648a6330a31b87        0t0     UDP *:52513
syncthing 507   jb  202r     REG                1,4    2116756 2867809 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000593.ldb
syncthing 507   jb  203r     REG                1,4    2116734 2867815 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000599.ldb
syncthing 507   jb  204r     REG                1,4    2118510 2867802 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000586.ldb
syncthing 507   jb  205u    IPv6 0xde648a633118635f        0t0     UDP *:60154
syncthing 507   jb  206r     REG                1,4    2117932 2867811 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000595.ldb
syncthing 507   jb  207r     REG                1,4    2117576 2867803 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000587.ldb
syncthing 507   jb  208r     REG                1,4    2118016 2867806 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000590.ldb
syncthing 507   jb  209r     REG                1,4    2118836 2867810 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000594.ldb
syncthing 507   jb  210r     REG                1,4    2117609 2867805 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000589.ldb
syncthing 507   jb  211u    IPv6 0xde648a632ec24617        0t0     UDP *:61216
syncthing 507   jb  212u    IPv6 0xde648a6332cf54d7        0t0     UDP *:53709
syncthing 507   jb  213u    IPv6 0xde648a634cedaf17        0t0     UDP *:51799
syncthing 507   jb  214u    IPv6 0xde648a63505f0fb7        0t0     UDP *:51898
syncthing 507   jb  215u    IPv6 0xde648a634a89f9f7        0t0     UDP *:65187
syncthing 507   jb  216u    IPv6 0xde648a634cee08cf        0t0     UDP *:65371
syncthing 507   jb  217u    IPv6 0xde648a63505f22bf        0t0     UDP *:49423
syncthing 507   jb  218u    IPv6 0xde648a6330a2f007        0t0     UDP *:53371
syncthing 507   jb  219u    IPv6 0xde648a63309c430f        0t0     UDP *:63087
syncthing 507   jb  220u    IPv6 0xde648a632ec1ef17        0t0     UDP *:60371
syncthing 507   jb  221u    IPv6 0xde648a632ec23def        0t0     UDP *:64730
syncthing 507   jb  222u    IPv6 0xde648a634cede82f        0t0     UDP *:61128
syncthing 507   jb  223u    IPv6 0xde648a63352ea617        0t0     UDP *:49894
syncthing 507   jb  224u    IPv6 0xde648a634a89fcaf        0t0     UDP *:50676
syncthing 507   jb  225u    IPv6 0xde648a63309c50a7        0t0     UDP *:50695
syncthing 507   jb  226u    IPv6 0xde648a634cedc4d7        0t0     UDP *:61130
syncthing 507   jb  227u    IPv6 0xde648a63352e987f        0t0     UDP *:57923
syncthing 507   jb  228u    IPv6 0xde648a63505ef73f        0t0     UDP *:51784
syncthing 507   jb  229u    IPv6 0xde648a634a8a0a47        0t0     UDP *:52370
syncthing 507   jb  230u    IPv6 0xde648a6331186b87        0t0     UDP *:61521
syncthing 507   jb  231u    IPv6 0xde648a6331186617        0t0     UDP *:65485
syncthing 507   jb  232u    IPv6 0xde648a634cedf30f        0t0     UDP *:64807
syncthing 507   jb  233u    IPv6 0xde648a6332cf41cf        0t0     UDP *:50346
syncthing 507   jb  234u    IPv6 0xde648a6331181caf        0t0     UDP *:53062
syncthing 507   jb  235u    IPv6 0xde648a63352eab87        0t0     UDP *:62547
syncthing 507   jb  236u    IPv6 0xde648a63505f330f        0t0     UDP *:62745
syncthing 507   jb  237u    IPv6 0xde648a6332cf49f7        0t0     UDP *:57057
syncthing 507   jb  238u    IPv6 0xde648a63311860a7        0t0     UDP *:64638
syncthing 507   jb  239u    IPv6 0xde648a634cedeae7        0t0     UDP *:52468
syncthing 507   jb  240u    IPv6 0xde648a634cedd527        0t0     UDP *:60979
syncthing 507   jb  241u    IPv6 0xde648a634cee0617        0t0     UDP *:54637
syncthing 507   jb  242u    IPv6 0xde648a63309c382f        0t0     UDP *:52973
syncthing 507   jb  243u    IPv6 0xde648a63352e4f17        0t0     UDP *:61363
syncthing 507   jb  244u    IPv4 0xde648a63468fc897        0t0     TCP 172.16.33.86:63614->83-233-120-221.cust.bredband2.com:snapenetio (ESTABLISHED)
syncthing 507   jb  245u    IPv6 0xde648a6332cf3f17        0t0     UDP *:65257
syncthing 507   jb  246u    IPv6 0xde648a63505f17df        0t0     UDP *:57785
syncthing 507   jb  247u    IPv6 0xde648a63309c073f        0t0     UDP *:60949
syncthing 507   jb  248u    IPv6 0xde648a632ec24b87        0t0     UDP *:52506
syncthing 507   jb  249u    IPv6 0xde648a634f567a97        0t0     UDP *:63749
syncthing 507   jb  250u    IPv6 0xde648a63309c3007        0t0     UDP *:53284
syncthing 507   jb  251r     REG                1,4    2109891 2867798 /Users/jb/Library/Application Support/Syncthing/index-v0.14.0.db/000582.ldb
syncthing 507   jb  252u    IPv6 0xde648a634bf00457        0t0     TCP localhost:8384->localhost:50172 (ESTABLISHED)
syncthing 507   jb  253u    IPv6 0xde648a634bb548d7        0t0     TCP localhost:8384->localhost:50273 (ESTABLISHED)
syncthing 507   jb  255u    IPv6 0xde648a634d465fd7        0t0     TCP localhost:8384->localhost:49943 (ESTABLISHED)
```

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
It's unexpected that `&(*foo)` does not work :/

### CODE REVIEW

File: lib/connections/quic_listen.go [hunk 1]
```diff
@@ -59,7 +59,8 @@ func (t *quicListener) OnNATTypeChanged(natType stun.NATType) {
 func (t *quicListener) OnExternalAddressChanged(address *stun.Host, via string) {
 	var uri *url.URL
 	if address != nil {
-		uri = &(*t.uri)
+		uri = &url.URL{}
+		*uri = *t.uri
```
Comment (imsodin) [inline lib/connections/quic_listen.go]: Why does `uri` need to be a pointer? There's nil checks, but wouldn't the line below (`uri.Host`) anyway blow up if `t.uri` was nil?

File: lib/connections/quic_dial.go [hunk 2]
```diff
@@ -45,23 +45,26 @@ func (d *quicDialer) Dial(id protocol.DeviceID, uri *url.URL) (internalConn, err
...
+	var createdConn net.PacketConn
 	if listenConn := registry.Get(uri.Scheme, packetConnLess); listenConn != nil {
 		conn = listenConn.(net.PacketConn)
 	} else {
 		if packetConn, err := net.ListenPacket("udp", ":0"); err != nil {
 			return internalConn{}, err
 		} else {
-			closeConn = true
 			conn = packetConn
+			createdConn = packetConn
```
Comment (imsodin) [inline lib/connections/quic_dial.go]: Why do we need to pass the same connection by another variable to `quic.DialContext`?

Comment (AudriusButkevicius) [reply lib/connections/quic_dial.go]: Because of the if statement above which only sets conn not createdConn

File: lib/connections/quic_listen.go (hunk 1 above)
Comment (AudriusButkevicius) [reply lib/connections/quic_listen.go]: .Host would not blow up as `&(*t.uri)` is never null, so is `uri = &uri.URL{}`

There is a distinction between not having resolved an address yet (nil), and having resolved the addres (address not nil, hence current uri is t.uri + new host that is resolved).

Comment (imsodin) [reply lib/connections/quic_listen.go]: Yeah right. Personally I'd consider it slightly simpler if `uri` wasn't a pointer. The condition later at line 72 would then just need to check `address == nil` instead. Anyways definitely nothing important.

Generally lgtm, maybe lets wait for Jakob to have a quick look as he brought this up.

File: lib/connections/quic_listen.go [hunk 3]
```diff
@@ -59,7 +59,8 @@ func (t *quicListener) OnNATTypeChanged(natType stun.NATType) {
 func (t *quicListener) OnExternalAddressChanged(address *stun.Host, via string) {
 	var uri *url.URL
 	if address != nil {
-		uri = &(*t.uri)
+		uri = &url.URL{}
```
Comment (calmh) [inline lib/connections/quic_listen.go]: I'd have preferred this as

```
copy := *t.uri
uri = &copy
```

to be more explicit about it being a copy that needs to happen, but /shrug

**Comment by calmh** [comment]
Ah, the "why" is answered by your question on the issue, there is no listener.

**Comment by AudriusButkevicius** [comment]
We don't reuse the connections when dialing off a random new connection, so we close it.
We do not close connections when we dial using the listener connection.

The listener closes the connection once it's done with it (which should never happen), at which point all the dialed connections will die with it.

Yes, we could do reference counting.

The only case where I was able to reproduce it was using random connection to dial out, which lines up with the fact that random ports were taken, but I don't understand why random connections were picked if you were also listening on quic?

**Comment by calmh** [comment]
Yes, I wan't listening on QUIC (or anything else), hence the issue. Our comments crossed paths. I understand then.

**Comment by calmh** [comment]
GitHub is doing weirdness. I definitely didn't post that comment again with the approval...
