### PR TITLE
all: Transactionalize db.FileSet (fixes #5952)

### LINKED ISSUE #5952: panic: Should never get a deleted file as needed when we don't have it
Sentry Issue: [SYNCTHING-2E](https://sentry.syncthing.net/syncthing/syncthing/issues/94/?referrer=github_integration)

```
Stacktrace (most recent call first):

  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/model/folder_sendonly.go", line 69, in func1
    panic("Should never get a deleted file as needed when we don't have it")
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/db/set.go", line 313, in func1
    return fn(f)
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/db/instance.go", line 398, in withNeedLocal
    if !fn(f) {
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/db/instance.go", line 319, in withNeed
    db.withNeedLocal(folder, truncate, fn)
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/db/set.go", line 157, in WithNeed
    s.db.withNeed([]byte(s.folder), device[:], false, nativeFileIterator(fn))
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/model/folder_sendonly.go", line 50, in pull
    f.fset.WithNeed(protocol.LocalDeviceID, func(intf db.FileIntf) bool {
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/model/folder.go", line 137, in func2
    if f.puller.pull() {
  File "/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/model/folder.go", line 163, in Serve
    pull()
  File "/opt/tcagent/syncthing-3-work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go", line 600, in func1

panic: Should never get a deleted file as needed when we don't have it
```

This implies inconsistencies in the model somehow?

### PR DESCRIPTION
**Pull request by imsodin**
When pulling we go once over all needed files in the db, and then at various later points do lookups in the db. In the meantime changes may happen (e.g. that's the only explanation I have for #5952). This PR moves db access through `db.FileSet` to `db.Snapshot` which can be obtained from `db.FileSet`.  
The huge diff on lowlevel.go and transaction.go is just copying over the methods that created a transaction at the beginning to actually be methods on transactions themselves.

Maybe it would be worth keeping utility functions on `db.FileSet` that allow access without taking a snapshot. I would definitely make especially some testing code shorter, then again I think it has some merit being force to think about snapshots (potential concurrent db changes) when dealing with the db.

### CODE REVIEW

File: lib/db/set_test.go [hunk 1]
```diff
@@ -1449,7 +1470,9 @@ func TestIgnoreAfterReceiveOnly(t *testing.T) {
 
 	s.Update(protocol.LocalDeviceID, fs)
 
-	if f, ok := s.Get(protocol.LocalDeviceID, file); !ok {
+	snap := s.Snapshot()
+	defer snap.Release()
+	if f, ok := snap.Get(protocol.LocalDeviceID, file); !ok {
```
Comment (golangcibot) [inline lib/db/set_test.go]: ifElseChain: rewrite if-else to switch statement (from `gocritic`)

File: lib/db/transactions.go [hunk 2]
```diff
@@ -94,6 +96,291 @@ func (t readOnlyTransaction) getGlobal(keyBuf, folder, file []byte, truncate boo
...
+	if err != nil {
+		return nil, err
+	}
+
+	vl, ok := unmarshalVersionList(bs)
+	if !ok {
+		return nil, nil
+	}
+
+	var devices []protocol.DeviceID
```
Comment (golangcibot) [inline lib/db/transactions.go]: Consider preallocating `devices` (from `prealloc`)

File: lib/model/folder_sendrecv.go [hunk 3]
```diff
@@ -806,12 +811,12 @@ func (f *sendReceiveFolder) deleteDir(file protocol.FileInfo, dbUpdateChan chan<
...
-func (f *sendReceiveFolder) deleteFile(file protocol.FileInfo, dbUpdateChan chan<- dbUpdateJob, scanChan chan<- string) {
-	cur, hasCur := f.fset.Get(protocol.LocalDeviceID, file.Name)
-	f.deleteFileWithCurrent(file, cur, hasCur, dbUpdateChan, scanChan)
+func (f *sendReceiveFolder) deleteFile(file protocol.FileInfo, snap *db.Snapshot, dbUpdateChan chan<- dbUpdateJob, scanChan chan<- string) {
+	cur, hasCur := snap.Get(protocol.LocalDeviceID, file.Name)
+	f.deleteFileWithCurrent(file, cur, hasCur, snap, dbUpdateChan, scanChan)
 }
 
-func (f *sendReceiveFolder) deleteFileWithCurrent(file, cur protocol.FileInfo, hasCur bool, dbUpdateChan chan<- dbUpdateJob, scanChan chan<- string) {
+func (f *sendReceiveFolder) deleteFileWithCurrent(file, cur protocol.FileInfo, hasCur bool, snap *db.Snapshot, dbUpdateChan chan<- dbUpdateJob, scanChan chan<- string) {
```
Comment (golangcibot) [inline lib/model/folder_sendrecv.go]: `(*sendReceiveFolder).deleteFileWithCurrent` - `snap` is unused (from `unparam`)

File: lib/model/folder_sendrecv.go [hunk 4]
```diff
@@ -1039,8 +1044,8 @@ func (f *sendReceiveFolder) renameFile(cur, source, target protocol.FileInfo, db
 
 // handleFile queues the copies and pulls as necessary for a single new or
 // changed file.
-func (f *sendReceiveFolder) handleFile(file protocol.FileInfo, copyChan chan<- copyBlocksState, dbUpdateChan chan<- dbUpdateJob) {
-	curFile, hasCurFile := f.fset.Get(protocol.LocalDeviceID, file.Name)
+func (f *sendReceiveFolder) handleFile(file protocol.FileInfo, snap *db.Snapshot, copyChan chan<- copyBlocksState, dbUpdateChan chan<- dbUpdateJob) {
```
Comment (golangcibot) [inline lib/model/folder_sendrecv.go]: `(*sendReceiveFolder).handleFile` - `dbUpdateChan` is unused (from `unparam`)

File: lib/model/testutils_test.go [hunk 5]
```diff
@@ -171,3 +172,40 @@ func (c *alwaysChanged) Seen(fs fs.Filesystem, name string) bool {
...
+}
+
+func globalSize(t *testing.T, m Model, folder string) db.Counts {
+	t.Helper()
+	snap := dbSnapshot(t, m, folder)
+	defer snap.Release()
+	return snap.GlobalSize()
+}
+
+func receiveOnlyChangedSize(t *testing.T, m Model, folder string) db.Counts {
```
Comment (golangcibot) [inline lib/model/testutils_test.go]: `receiveOnlyChangedSize` - `folder` always receives `"ro"` (from `unparam`)

**Comment by calmh** [comment]
This sounds like a good change and I’m not ignoring it; I’ve been traveling with limited internet but I’m back in business for real on Monday.
