### PR TITLE
lib/model: Remove runner during folder cleanup (fixes #9269)

### LINKED ISSUE #9234: Nil deref in index handler
Panic were reported in android a few times and then here an actual/ful panic trace was referenced:
https://forum.syncthing.net/t/syncthing-1-26-crashing-on-android-in-syncthing-fork/21115/2

> 
> 11-19 11:32:51.661 11506 21478 W SyncthingNativeCode: panic: runtime error: invalid memory address or nil pointer dereference
> 11-19 11:32:51.661 11506 21478 W SyncthingNativeCode: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x637d5ee060]
> 11-19 11:32:51.661 11506 21478 W SyncthingNativeCode:
> 11-19 11:32:51.661 11506 21478 W SyncthingNativeCode: goroutine 325 [running]:
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).startLocked(_, {{0x4000363e44, 0xc}, {0x4000363e70, 0xc}, 0x0, {0x400011af78, 0x18}, 0x1, {0x40000c2b40, ...}, ...}, ...)
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/model/indexhandler.go:419 +0x100
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).AddIndexInfo(0x400040e370, {0x40001307b0, 0xc}, 0x4000000640)
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/model/indexhandler.go:439 +0x430
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/model.(*model).ccHandleFolders(_, {_, _, _}, {{0xdb, 0xa, 0xa4, 0x47, 0xc6, 0x6f, ...}, ...}, ...)
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/model/model.go:1496 +0x5a8
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0x40001c6180, {0x637d8d4148, 0x4000eec350}, {{0x400154ca00?, 0x40000e8088?, 0x40000e8088?}, 0x68?})
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/model/model.go:1296 +0x784
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*connectionWrappingModel).ClusterConfig(0x4000bc5d68?, {{0x400154ca00?, 0x10?, 0x637d710540?}, 0x1?})
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/protocol/protocol.go:1143 +0x50
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/protocol.encryptedModel.ClusterConfig(...)
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/protocol/encryption.go:155
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0x4000116a20)
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/protocol/protocol.go:496 +0x308
> 11-19 11:32:51.663 21476     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func2()
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/protocol/protocol.go:307 +0x24
> 11-19 11:32:51.663 21476     0 E Go      : created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
> 11-19 11:32:51.663 21476     0 E Go      :      github.com/syncthing/syncthing/lib/protocol/protocol.go:306 +0x144
> 11-19 11:32:51.663 21476     0 E Go      :

There's recently changed/added code that sets up index handlers and access fmut protected fields without holding the lock: https://github.com/syncthing/syncthing/blob/main/lib/model/model.go#L1370  
I don't see how exactly this can lead to the panic, but presumably some race around pausing a folder.

I am sending a PR shortly.

### LINKED ISSUE #9269: panic: nil pointer dereference in (*indexHandlerRegistry).startLocked
```
2023/12/07 21:27:41 INFO: syncthing v1.27.0 "Gold Grasshopper" (go1.20.11 linux-amd64) root@buildkitsandbox 2023-12-05 07:12:09 UTC [noupgrade]
Panic at 2023-12-07T21:35:02+01:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xd61b6e]

goroutine 171032 [running]:
github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).startLocked(_, {{0xc00512dbc0, 0xb}, {0xc00512dbd0, 0xe}, 0x0, {0xc00116e9e0, 0x20}, 0x0, {0xc000e1bba0, ...}, ...}, ...)
	github.com/syncthing/syncthing/lib/model/indexhandler.go:419 +0x16e
github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).AddIndexInfo(0xc0015e9400, {0xc0009d0ae0, 0xb}, 0xc00175a500)
	github.com/syncthing/syncthing/lib/model/indexhandler.go:439 +0x4b5
github.com/syncthing/syncthing/lib/model.(*model).ccHandleFolders(_, {_, _, _}, {{0x81, 0xc1, 0x8d, 0x7b, 0xd9, 0x97, ...}, ...}, ...)
	github.com/syncthing/syncthing/lib/model/model.go:1431 +0xca6
github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0xc000002000, {0x13c2688, 0xc000fe6170}, {{0xc0011ac000?, 0xc0000d0088?, 0xc001429d78?}, 0xcf?})
	github.com/syncthing/syncthing/lib/model/model.go:1296 +0x8e8
github.com/syncthing/syncthing/lib/protocol.(*connectionWrappingModel).ClusterConfig(0xc001429d78?, {{0xc0011ac000?, 0x10?, 0xe96c40?}, 0x1?})
	github.com/syncthing/syncthing/lib/protocol/protocol.go:1143 +0x43
github.com/syncthing/syncthing/lib/protocol.encryptedModel.ClusterConfig(...)
	github.com/syncthing/syncthing/lib/protocol/encryption.go:155
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0xc000d9b9e0)
	github.com/syncthing/syncthing/lib/protocol/protocol.go:496 +0x3b7
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func2()
	github.com/syncthing/syncthing/lib/protocol/protocol.go:307 +0x25
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
	github.com/syncthing/syncthing/lib/protocol/protocol.go:306 +0x116
```

`runner` is nil here:

https://github.com/syncthing/syncthing/blob/75310b58a06605055823826b4e63e4356ce2e7c5/lib/model/indexhandler.go#L419

//@calmh

### PR DESCRIPTION
**Pull request by imsodin**
Before introducing the service map and using it for folder runners, the entries in folderCfgs and folderRunners for the same key/folder were removed under a single lock. Stopping the folder happens separately before that with just the read lock. Now with the service map stopping the folder and removing it from the map is a single operation. And that still happens with just a read-lock. However even with a full lock it’s still problematic: After the folder stopped, the runner isn’t present anymore while the folder-config still is and sais the folder isn't paused.

The index handler in turn looks at the folder config that is not paused, thus assumes the runner has to be present -> nil deref on the runner.

A better solution might be to push most of these fmut maps into the folder - they anyway are needed in there. Then there's just a single map/source of info that's necessarily consistent. That's quite a bit of work though, and probably/likely there will be corner cases there too.

### CODE REVIEW

**Comment by calmh** [comment]
Well, good to see that we independently reached the same conclusion about the problem at least. Though we now have paralell issues and PRs :p

**Comment by imsodin** [comment]
Was about to check your PR, already closed "my" ticket again in favor of yours

File: lib/model/service_map.go [hunk 1]
```diff
@@ -59,13 +59,45 @@ func (s *serviceMap[K, S]) Get(k K) (v S, ok bool) {
...
+func (s *serviceMap[K, S]) Stop(k K) (found bool) {
+	if tok, ok := s.tokens[k]; ok {
+		found = true
+		s.supervisor.Remove(tok)
+	}
+	delete(s.tokens, k)
+	return
+}
+
+// RemoveAndWaitChan removes the service at the given key, stopping it on
```
Comment (calmh) [inline lib/model/service_map.go:74]:
```suggestion
// StopAndWaitChan removes the service at the given key, stopping it on
```

File: lib/model/service_map.go [hunk 2]
```diff
@@ -59,13 +59,45 @@ func (s *serviceMap[K, S]) Get(k K) (v S, ok bool) {
...
 // Remove removes the service at the given key, stopping it on the supervisor.
 // If there is no service at the given key, nothing happens. The return value
 // indicates whether a service was removed.
 func (s *serviceMap[K, S]) Remove(k K) (found bool) {
 	if tok, ok := s.tokens[k]; ok {
 		found = true
 		s.supervisor.Remove(tok)
+	} else {
+		_, sok := s.services[k]
+		found = sok
```
Comment (calmh) [inline lib/model/service_map.go:100]:
```suggestion
		_, found = s.services[k]
```

**Review by calmh — APPROVED** [review]
Cool. I think I prefer your solution. We should add a `fixes` for my new issue as well.

**Comment by imsodin** [comment]
> Cool. I think I prefer your solution.

After looking at your PR I think there's still a tiny bug in mine: Removing the token from the service map happens under read-lock, so multiple goroutines might race for removing it. I dont think it can cause any problems, but it's not right. I'll also remove it in `Remove` like in your PR.

**Comment by imsodin** [comment]
Luckily stopping a service in suture is idempotent. The bool return on `Stop` was pretty useless now that we don't delete the token, so I removed that. Can you have a look and ack again if the code still looks good - thanks.
