### PR TITLE
lib/db: Fix iterating sequence index (fixes #5340)

### LINKED ISSUE #5340: Incorrectly out of sync, sequence number oddness.
It seems there might be an occasional issue with the index sending. I noticed this in my home setup. Two devices, "kvin" and "pseudo"; kvin thinks pseudo is out of sync missing one file, pseudo thinks it has everything, but the file is missing.

kvin side:

screen shot 2018-11-29 at 09 15 05

screen shot 2018-11-29 at 09 15 13

(note 2702 files locally, pseudo missing one pdf)

pseudo side:

screen shot 2018-11-29 at 09 15 20

(2701 files locally)

Checking the file via rest shows it present on kvin but not pseudo, which matches the above:

```
jb@kvin:~ $ curl ... 'http://localhost:8384/rest/db/file?folder=documents&file=Kastelo/Ekonomi/2018+Bokföring/INV04871726_A00552008_11252018.pdf'
{
  "availability": null,
  "global": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2018-11-26T07:03:54+01:00",
    "modifiedBy": "SYNO4VL",
    "mustRescan": false,
    "name": "Kastelo/Ekonomi/2018 Bokföring/INV04871726_A00552008_11252018.pdf",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 902,
    "size": 71947,
    "type": 0,
    "version": [
      "SYNO4VL:1"
    ]
  },
  "local": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2018-11-26T07:03:54+01:00",
    "modifiedBy": "SYNO4VL",
    "mustRescan": false,
    "name": "Kastelo/Ekonomi/2018 Bokföring/INV04871726_A00552008_11252018.pdf",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 902,
    "size": 71947,
    "type": 0,
    "version": [
      "SYNO4VL:1"
    ]
  }
}

$ curl ... 'https://pseudo.int.nym.se:8384/rest/db/file?folder=documents&file=Kastelo/Ekonomi/2018+Bokföring/INV04871726_A00552008_11252018.pdf'
No such object in the index
```

The sequence number 902 is suspiciously low for this folder though; it's been around for a long time. Spot checking a couple of other files doesn't reveal anything conclusive though. One from Nov 14 (two weeks ago) has sequence 850 while another from Now 27 (one day after the affected one above) has sequence 49569. The latter seems more reasonable, and I'm not sure what would cause the large amount of updates between the 26th and 27th otherwise. (I mean, there are 2700 files in the folder, and they only change very occasionally.) This file is very recent, and a sequence < 2700 should be impossible.

Restarting kvin with `-reset-deltas` resolved.

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

There was a problem in iterating the sequence index that could result
in missing updates. The issue is that while the index was (correctly)
iterated in a snapshot, the actual file infos were read dirty outside of
the snapshot. This fixes this by doing the reads inside the snapshot,
and also updates a couple of other places that did the same thing more
or less harmfully (I didn't investigate).

To avoid similar issues in the future I did some renaming of the
getFile* methods - the ones in a transaction are just getFile, while the
ones directly on the database are variants of getFileDirty to highlight
what's going on.

### Testing

There's a new unit test. Unfortunately it rather needs to run longer than is acceptable in the short test suite. Without the change, the test would fail after a few seconds. When run with `STTRACE=db` it would also trigger a `panic: sequence index corruption`.

### CODE REVIEW

File: lib/db/instance.go [hunk 1]
```diff
@@ -124,11 +124,7 @@ func (db *instance) withHave(folder, device, prefix []byte, truncate bool, fn It
 			return
 		}
 
-		// The iterator function may keep a reference to the unmarshalled
-		// struct, which in turn references the buffer it was unmarshalled
-		// from. dbi.Value() just returns an internal slice that it reuses, so
-		// we need to copy it.
-		f, err := unmarshalTrunc(append([]byte{}, dbi.Value()...), truncate)
```
Comment (calmh) [inline lib/db/instance.go]: This talk was about the old xdr implementation. The protobuf unmarshaller keeps no references.

File: lib/db/instance.go [hunk 2]
```diff
@@ -297,7 +297,7 @@ func (db *instance) withGlobal(folder, prefix []byte, truncate bool, fn Iterator
 
 		fk = db.keyer.GenerateDeviceFileKey(fk, folder, vl.Versions[0].Device, name)
 
-		f, ok := db.getFileTrunc(fk, truncate)
+		f, ok := t.getFileTrunc(fk, truncate)
```
Comment (AudriusButkevicius) [inline lib/db/instance.go]: From consistency perspective, shouldn't the root check at the top of this function happen part of the transaction?

Comment (calmh) [reply lib/db/instance.go]: I considered it, but since it just reads one value it's equivalent anyway and taking the snapshot looked like overhead. However I see now that `getGlobal` actually takes a snapshot of its own, so it would be cleaner to do that... I'll tweak.

Comment (imsodin) [reply lib/db/instance.go]: Same for `withHave`. As far as I understood, taking the snapshot is no or negligible overhead, because `db.Get` internally takes a snapshot too. So first doing `db.Get` then in most cases starting a transaction and thus taking a seconds snapshot seems like more overhead.

File: lib/db/instance.go [hunk 3]
```diff
@@ -209,14 +205,18 @@ func (db *instance) withAllFolderTruncated(folder []byte, fn func(device []byte,
...
+
+func (db *instance) getFileDirtyByKey(key []byte) (protocol.FileInfo, bool) {
+	if f, ok := db.getFileDirtyTrunc(key, false); ok {
 		return f.(protocol.FileInfo), true
 	}
 	return protocol.FileInfo{}, false
 }
 
-func (db *instance) getFileTrunc(key []byte, trunc bool) (FileIntf, bool) {
+func (db *instance) getFileDirtyTrunc(key []byte, trunc bool) (FileIntf, bool) {
```
Comment (imsodin) [inline lib/db/instance.go]: There are now only calls to `db.getFileDirty(...` left, so this function and `getFileDirtyByKey` could be removed.

**Comment by calmh** [comment]
Seeing as we might need a meme then

**Comment by calmh** [comment]
I was considering doing just that. On the one hand we've had this bug since 0.14.48, on the other hand it's an annoying, confidence-reducing issue that we should get out the fix for sooner rather than later, and it's >2w left of the RC time...

**Comment by imsodin** [comment]
Dammit, when rebasing #5441 I think I just discovered the exact same problem you solved here but with `getGlobal` instead. Let me do a minimal PR with just that fixed, I am not yet sure whether or not it requires another RC
