### PR TITLE
fix(connections): announce PtP links again (fixes #9730)

### LINKED ISSUE #9730: connections: point-to-point links should still be announced
I'm afraid this has an undesirable side effect:

https://github.com/syncthing/syncthing/blob/8ff670c5643cefdcb26d841123e5b71523dcb4e8/lib/connections/util.go#L62-L81

We should still announce those IPs to the global discovery server.

_Originally posted by @bt90 in https://github.com/syncthing/syncthing/issues/9720#issuecomment-2366731067_

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

File: lib/osutil/net.go [hunk 1]
```diff
@@ -21,7 +23,7 @@ func GetLans() ([]*net.IPNet, error) {
 		if intf.Flags&net.FlagRunning == 0 {
 			continue
 		}
-		if intf.Flags&net.FlagPointToPoint != 0 {
+		if !includePtP && intf.Flags&net.FlagPointToPoint != 0 {
```
Comment (bt90) [inline lib/osutil/net.go:26]: Should we use `excludePtP` ? I'd avoid a flag that's only used inverted.

Comment (calmh) [reply lib/osutil/net.go:26]: Yeah... I though it was nicer to avoid the double negative on the caller side, so we don't have to think "pass false to not exclude PtP"

Comment (bt90) [reply lib/osutil/net.go:26]: Polluting the caller is worse. Let's stick with `include`.

**Review by bt90 — APPROVED** [review]
