### PR TITLE
lib/config, lib/model: Handle shared with information in config (fixes #4870)

### LINKED ISSUE #4870: Don't show a warning when a file from a paused folder is requested
> ```
> 2018-04-03 19:02:20: Request from SomePeer for file 2011/201108 Coups de pagaies sur Dordogne/20110804_134450-FV-p8040297.jpg in unshared folder “xxx5x-xxx2x”.
> ```
> The peer is member in the folder share settings

> I think this is a race, essentially a folder gets paused as a request from a remote peer comes in. Paused folders are not shared with anyone.
> 
> This shouldn’t happen as the connection gets broken, but I suspect there is a window between folder tear down and actual disconnection where this can happen.

https://forum.syncthing.net/t/some-requests-from-peer-in-unshared-folder/11451
https://forum.syncthing.net/t/request-from-for-file-in-unshared-folder/11468

### PR DESCRIPTION
**Pull request by imsodin**
Original/main purpose is to actually fix #4870. In the previous PR I tried to deduce whether the folder is paused from the information within the model. That clearly fails, because paused folders aren't in the model. 

Paused folders also caused problems elsewhere in the past (cluster config for one). `folderDevices` and `deviceFolders` is fully redundant and additionally they track information about which folder is shared with whom -> that's actually config business (again, paused folders). So I moved that functionality to wrapper.go and adapted all affected sections in model.go (sometimes adding the distinction between a unshared vs just paused folder).

### CODE REVIEW

File: lib/model/model.go [hunk 1]
```diff
@@ -1136,53 +1104,57 @@ func (m *Model) handleIntroductions(introducerCfg config.DeviceConfiguration, cm
...
+func (m *Model) handleDeintroductions(introducerCfg config.DeviceConfiguration, cm protocol.ClusterConfig, foldersDevices config.FolderDeviceSet) bool {
 	changed := false
-	foldersIntroducedByOthers := make(folderDeviceSet)
+	devicesNotIntroduced := make(map[protocol.DeviceID]struct{})
 
+	folders := m.cfg.FolderList()
 	// Check if we should unshare some folders, if the introducer has unshared them.
-	for _, folderCfg := range m.cfg.Folders() {
-		folderChanged := false
+	for i := range folders {
```
Comment (AudriusButkevicius) [inline lib/model/model.go]: Just `for _, folderCfg := range folders` ?

File: lib/model/model_test.go [hunk 2]
```diff
@@ -1286,7 +1286,8 @@ func TestAutoAcceptPrefersLabel(t *testing.T) {
 			},
 		},
 	})
-	if fcfg, ok := wcfg.Folder(id); !ok || !m.folderSharedWith(id, device1) || !strings.HasSuffix(fcfg.Path, label) {
+	if fcfg, ok := wcfg.Folder(id); !ok || !wcfg.IsSharedWith(id, device1) || !strings.HasSuffix(fcfg.Path, label) {
+
```
Comment (AudriusButkevicius) [inline lib/model/model_test.go]: new blank line

File: lib/model/model.go (hunk 1 above)
Comment (AudriusButkevicius) [reply lib/model/model.go]: Actually, you are right, but I'd just modify folders[i] to cause less confusion

File: lib/model/model.go [hunk 3]
```diff
@@ -935,28 +909,23 @@ func (m *Model) ClusterConfig(deviceID protocol.DeviceID, cm protocol.ClusterCon
...
 				"device":      deviceID.String(),
 			})
 			l.Infof("Unexpected folder %s sent from device %q; ensure that the folder exists and that this device is selected under \"Share With\" in the folder configuration.", folder.Description(), deviceID)
 			continue
+		} else if folder.Paused {
+			paused = append(paused, folder.ID)
+			continue
+		} else if cfg.Paused {
+			continue
 		}
```
Comment (AudriusButkevicius) [inline lib/model/model.go]: All of these end up with continues, can we break them into separate ifs, so that we don't have to think about the previous if checking if next one will be hit.

File: lib/model/model.go [hunk 4]
```diff
@@ -1106,15 +1074,10 @@ func (m *Model) handleIntroductions(introducerCfg config.DeviceConfiguration, cm
 			if _, ok := m.cfg.Devices()[device.ID]; !ok {
 				// The device is currently unknown. Add it to the config.
 				m.introduceDevice(device, introducerCfg)
-				changed = true
```
Comment (AudriusButkevicius) [inline lib/model/model.go]: This was lost somehow?

Comment (imsodin) [reply lib/model/model.go]: Not lost, removed. It is superfluous as will already be set to true here:
https://github.com/syncthing/syncthing/pull/4974/files/dfa19b40a8c03563a50dd7278f6b5114768e35aa#diff-1df9805b2381b6288b220226f82d5dc9R1090

Comment (AudriusButkevicius) [reply lib/model/model.go]: That doesn't show anything meaningful.

Comment (AudriusButkevicius) [reply lib/model/model.go]: ah it's at the bottom, ok.

Comment (imsodin) [reply lib/model/model.go]: I seriously need to stop linking code and start copying it - these github-diff-links are so broken.

**Comment by imsodin** [comment]
@calmh Would you like to review this? If not I'd like to merge :)

@AudriusButkevicius Could you re-approve please?

**Comment by calmh** [comment]
I glanced through it, I'll take this one on faith.
