### PR TITLE
fix(model): earlier free-space check (fixes #10347)

### LINKED ISSUE #10347: Syncthing seems to ignore Minimum Free Disk Space on folders
### What happened?

When sharing a folder between devices, Syncthing seems to ignore Minimum Free Disk Space, only stopping when the target disk is truly filled to the brim. I originally experienced the issue sharing large folders to a laptop with a small drive, but managed to replicate the problem on a VM as follows:
1) Share a folder with a device that can't fit it
2) Set some minimum space limit when accepting the folder on the target device

Image

3) Syncthing will fill up the entire disk with no regard for the previous limit, to the point of lagging the whole system.

Image

Also, the size of the folder is misreported by the UI
Image

Expected behavior: Folder should stop syncing when the minimum space limit is reached

PD: I'm not sure if the log is even useful, since the VM crashed shortly after running out of space and it seems that it didn't catch anything super useful before that happened.

### Syncthing version

v2.0.6

### Platform & operating system

Windows 11 x64

### Browser version

_No response_

### Relevant log output

```shell
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\contourpy\dechunk.py file.modified="2025-06-04 10:35:53.8234804 -0500 -05" file.permissions=0644 file.size=7963 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\fontTools\varLib\iup.c file.modified="2025-06-04 10:35:40.9483594 -0500 -05" file.permissions=0644 file.size=838607 file.blocksize=131072 blocks.local=0 blocks.download=7 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\inversify\es\planning\metadata_reader.js file.modified="2025-07-04 12:05:03.1397874 -0500 -05" file.permissions=0755 file.size=873 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\librosa\beat.py file.modified="2025-06-04 10:36:17.7719847 -0500 -05" file.permissions=0644 file.size=25312 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\config-file-ts\node_modules\minimatch\dist\esm\ast.d.ts.map file.modified="2025-07-04 15:47:00.8074855 -0500 -05" file.permissions=0644 file.size=868 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\fontTools\subset\__pycache__\util.cpython-310.pyc file.modified="2025-06-04 10:35:41.3946474 -0500 -05" file.permissions=0644 file.size=981 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\c++\TruthTableCalcLauncher\TruthTableCalcLauncher\x64\Debug\TruthTab.d43e099a.tlog\link.command.1.tlog file.modified="2025-05-11 20:10:17.8651319 -0500 -05" file.permissions=0644 file.size=1890 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\transformers\models\vitmatte\__pycache__\image_processing_vitmatte.cpython-310.pyc file.modified="2025-06-04 10:36:25.0770003 -0500 -05" file.permissions=0644 file.size=11371 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\tzdata\zoneinfo\Atlantic\Faeroe file.modified="2025-06-04 10:35:24.3756643 -0500 -05" file.permissions=0644 file.size=441 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\transformers\models\segformer\__pycache__\modeling_tf_segformer.cpython-310.pyc file.modified="2025-06-04 10:36:24.4442914 -0500 -05" file.permissions=0644 file.size=32116 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\numpy\random\_generator.cp310-win_amd64.pyd file.modified="2025-06-04 10:35:34.0944464 -0500 -05" file.permissions=0644 file.size=714240 file.blocksize=131072 blocks.local=0 blocks.download=6 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\decompiled\deezer-desktop-old\node_modules\@szmarczak\http-timer\dist\source\index.d.ts file.modified="2025-07-04 15:42:04.1476985 -0500 -05" file.permissions=0644 file.size=820 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\kiwisolver\__pycache__\__init__.cpython-310.pyc file.modified="2025-06-04 10:35:39.2823476 -0500 -05" file.permissions=0644 file.size=696 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\sklearn\datasets\tests\test_olivetti_faces.py file.modified="2025-06-04 10:36:11.9200216 -0500 -05" file.permissions=0644 file.size=945 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\scipy\optimize\tests\test_nnls.py file.modified="2025-06-04 10:35:45.9191774 -0500 -05" file.permissions=0644 file.size=26192 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\@electron\node-gyp\gyp\pylib\gyp\generator\msvs.py file.modified="2025-07-04 15:47:02.0079004 -0500 -05" file.permissions=0644 file.size=150898 file.blocksize=131072 blocks.local=0 blocks.download=2 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\transformers\models\mobilenet_v2\feature_extraction_mobilenet_v2.py file.modified="2025-06-04 10:36:19.1816866 -0500 -05" file.permissions=0644 file.size=1266 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:27 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\make-fetch-happen\lib\agent.js file.modified="2025-07-04 15:46:59.7453096 -0500 -05" file.permissions=0755 file.size=5877 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\llvmlite\ir\__pycache__\transforms.cpython-310.pyc file.modified="2025-06-04 10:35:39.2041891 -0500 -05" file.permissions=0644 file.size=2773 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\matplotlib\sphinxext\figmpl_directive.py file.modified="2025-06-04 10:36:14.4903301 -0500 -05" file.permissions=0644 file.size=9308 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\sklearn\semi_supervised\__pycache__\_label_propagation.cpython-310.pyc file.modified="2025-06-04 10:36:13.8391469 -0500 -05" file.permissions=0644 file.size=19172 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\err-code\test\.eslintrc.json file.modified="2025-07-04 15:46:59.1712764 -0500 -05" file.permissions=0644 file.size=44 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\_foreach_sub_native.h file.modified="2025-06-04 10:36:02.8119181 -0500 -05" file.permissions=0644 file.size=2295 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\logit_native.h file.modified="2025-06-04 10:36:00.6817844 -0500 -05" file.permissions=0644 file.size=742 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\llvmlite\ir\__pycache__\types.cpython-310.pyc file.modified="2025-06-04 10:35:39.2081864 -0500 -05" file.permissions=0644 file.size=25331 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\TTS\tts\models\__pycache__\tacotron2.cpython-310.pyc file.modified="2025-06-04 10:36:26.5918212 -0500 -05" file.permissions=0644 file.size=12024 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\torch\csrc\profiler\unwind\action.h file.modified="2025-06-04 10:35:58.42382 -0500 -05" file.permissions=0644 file.size=1483 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\@types\node\tls.d.ts file.modified="2025-07-04 15:42:05.4500572 -0500 -05" file.permissions=0644 file.size=59812 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\matplotlib\mpl-data\images\forward.png file.modified="2025-06-04 10:36:14.7098311 -0500 -05" file.permissions=0644 file.size=357 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\sklearn\decomposition\__pycache__\_incremental_pca.cpython-310.pyc file.modified="2025-06-04 10:36:12.7729942 -0500 -05" file.permissions=0644 file.size=14144 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\conv_transpose3d_ops.h file.modified="2025-06-04 10:36:01.6964599 -0500 -05" file.permissions=0644 file.size=1756 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=FindDuplicateFolders\.git\objects\32\2fe01dd23191d38c0354428551b738e6cbc195 file.modified="2024-04-17 11:29:03.8428941 -0500 -05" file.permissions=0644 file.size=1368 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\linalg_cross_compositeexplicitautogradnonfunctional_dispatch.h file.modified="2025-06-04 10:36:00.8690464 -0500 -05" file.permissions=0644 file.size=861 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\setuptools\_vendor\packaging\_manylinux.py file.modified="2025-06-04 09:31:01.9933742 -0500 -05" file.permissions=0644 file.size=9612 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\Cython\Compiler\Tests\__pycache__\TestTreePath.cpython-310.pyc file.modified="2025-06-04 10:35:42.7945531 -0500 -05" file.permissions=0644 file.size=5335 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\electron-winstaller\node_modules\fs-extra\lib\json\output-json.js file.modified="2025-07-04 15:47:00.7731335 -0500 -05" file.permissions=0755 file.size=657 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\transformers\models\herbert\__pycache__\tokenization_herbert_fast.cpython-310.pyc file.modified="2025-06-04 10:36:22.4221887 -0500 -05" file.permissions=0644 file.size=5479 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\empty_permuted_ops.h file.modified="2025-06-04 10:36:01.4825906 -0500 -05" file.permissions=0644 file.size=2353 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\orgqr_ops.h file.modified="2025-06-04 10:36:00.2790241 -0500 -05" file.permissions=0644 file.size=1759 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\filelock\__pycache__\_unix.cpython-310.pyc file.modified="2025-06-04 10:35:41.9171567 -0500 -05" file.permissions=0644 file.size=2233 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\librosa-0.11.0.dist-info\top_level.txt file.modified="2025-06-04 10:36:17.7985255 -0500 -05" file.permissions=0644 file.size=8 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\dir-compare\build\src\NameCompare\fileBasedNameCompare.js.map file.modified="2025-07-04 15:47:00.9811025 -0500 -05" file.permissions=0644 file.size=256 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\pip\_internal\models\installation_report.py file.modified="2025-06-04 08:52:34.229827 -0500 -05" file.permissions=0644 file.size=2609 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\libraries\3rdPartyLibraries\c++\eigen-3.4.0\Eigen\src\misc\Kernel.h file.modified="2024-01-12 12:09:03.1149367 -0500 -05" file.permissions=0777 file.size=2821 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\special_expit_native.h file.modified="2025-06-04 10:35:59.6749173 -0500 -05" file.permissions=0644 file.size=590 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\src\deezer-desktop\node_modules\roarr\dist\constants.js.flow file.modified="2025-07-04 15:42:03.8097639 -0500 -05" file.permissions=0644 file.size=116 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\sympy\polys\matrices\dfm.py file.modified="2025-06-04 10:35:25.3825057 -0500 -05" file.permissions=0644 file.size=1241 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\deezerMod\decompiled\deezer-desktop-old\node_modules\pako\lib\zlib\zstream.js file.modified="2025-07-04 12:05:03.346923 -0500 -05" file.permissions=0755 file.size=1811 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\TTS\utils\distribute.py file.modified="2025-06-04 10:36:26.1510151 -0500 -05" file.permissions=0644 file.size=716 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\matplotlib\tests\__pycache__\test_widgets.cpython-310.pyc file.modified="2025-06-04 10:36:16.0271356 -0500 -05" file.permissions=0644 file.size=42918 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\sympy\concrete\expr_with_limits.py file.modified="2025-06-04 10:35:24.7897401 -0500 -05" file.permissions=0644 file.size=21834 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name="VSCode_tests\\java\\WebScraperGradle\\do_not_compile\\New folder\\Plan por Mis Condiciones Acad_files\\PT_PROCESSING_ESP_1.gif" file.modified="2025-05-03 17:13:32.943 -0500 -05" file.permissions=0644 file.size=5779 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\transformers\models\speech_to_text\__pycache__\modeling_tf_speech_to_text.cpython-310.pyc file.modified="2025-06-04 10:36:24.5682759 -0500 -05" file.permissions=0644 file.size=51091 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\include\ATen\ops\_convolution_mode_compositeimplicitautograd_dispatch.h file.modified="2025-06-04 10:36:03.0972544 -0500 -05" file.permissions=0644 file.size=1207 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\libraries\3rdPartyLibraries\c++\eigen-3.4.0\blas\f2c\chbmv.c file.modified="2024-01-12 12:09:03.2016501 -0500 -05" file.permissions=0777 file.size=15595 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torch\_dispatch\__pycache__\python.cpython-310.pyc file.modified="2025-06-04 10:36:04.6085925 -0500 -05" file.permissions=0644 file.size=6729 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\encodec\modules\__pycache__\norm.cpython-310.pyc file.modified="2025-06-04 10:36:25.9885076 -0500 -05" file.permissions=0644 file.size=1206 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\sympy\functions\combinatorial\tests\test_comb_factorials.py file.modified="2025-06-04 10:35:24.8833579 -0500 -05" file.permissions=0644 file.size=26317 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\pytz\zoneinfo\Africa\Sao_Tome file.modified="2025-06-04 10:35:22.1259971 -0500 -05" file.permissions=0644 file.size=254 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:28 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\torchaudio\sox_effects\__init__.py file.modified="2025-06-04 10:36:17.3142271 -0500 -05" file.permissions=0644 file.size=272 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:28:29 INF Synced file (folder.label="Visual Studio Code" folder.id=iwkpe-a3cge folder.type=sendreceive file.name=VSCode_tests\python\CoquiTTS\.venv\Lib\site-packages\numpy\typing\tests\data\pass\arrayprint.py file.modified="2025-06-04 10:35:34.2045998 -0500 -05" file.permissions=0644 file.size=803 file.blocksize=131072 blocks.local=0 blocks.download=1 log.pkg=model)
2025-09-03 20:30:16 INF Folder changed state (folder=iwkpe-a3cge state=sync-preparing log.pkg=model)
```

### PR DESCRIPTION
**Pull request by calmh**
Since #10332 we'd create the temp file when closing out the puller state for a file, but this is inappropriate if the reason we're bailing out is that there isn't space for it to begin with. Instead, do the free space check before we even start copying/pulling.

### CODE REVIEW

File: lib/model/folder_sendrecv.go [hunk 1]
```diff
@@ -491,15 +491,26 @@ nextFile:
 			continue nextFile
 		}
 
+		// Verify there is some availability for the file before we start
+		// processing it
```
Comment (imsodin) [inline lib/model/folder_sendrecv.go:495]: Unrelated: Why are we even doing this so early? We might be able to pull it purely by copying. Seems like a check for the pull stage.

**Review by imsodin — APPROVED** [review]
Looks good to me - though lately that doesn't mean much, missed lots of issues in recent approvals :grimacing: 

Only tangentially related thought, triggered by the issue/change here:   
Maybe we should not defer creating the temp. file in the shared puller state at all, just create it right away when creating the state? That way the size is immediately accounted, i.e. the next `CheckAvailableSpace` call will fail even if the previous file might not have started copying/pulling (and thus creating the temp file) yet. Also seems like missing branches where we still need to create it was causing headaches and I couldn't figure out the benefit of doing it later anymore :)

File: lib/model/folder_sendrecv.go (hunk 1 above)
Comment (calmh) [reply lib/model/folder_sendrecv.go:495]: This is also true
