### PR TITLE
docker: Allow start even if chown fails (fixes #9133)

### LINKED ISSUE #9133: Syncthing Docker container fails to start if underlying filesystem doesn't support `chown`
### Does your log mention database corruption?

No

### Include required information

Please be sure to include at least:

Syncthing fails to start if its unable to `chown` the `/var/syncthing` docker volume. The mount providing the folder does not allow that. I think syncthing should still be able to start.

log says: `chown: /var/syncthing: Invalid argument`

### PR DESCRIPTION
**Pull request by calmh**
Maybe it fails, maybe it doesn't. If it fails and we didn't need it we don't need to complain. If it fails and we did need it, we'll fail on the next line instead.

### CODE REVIEW

File: script/docker-entrypoint.sh [hunk 1]
```diff
@@ -14,8 +14,10 @@ if [ "$(id -u)" = '0' ]; then
     setcap "$PCAP" "$binary"
   fi
 
-  chown "${PUID}:${PGID}" "${HOME}" \
-    && exec su-exec "${PUID}:${PGID}" \
+  # Chown may fail, which may cause us to be unable to start; but maybe
+  # it'll work anyway, so we the error slide.
```
Comment (imsodin) [inline script/docker-entrypoint.sh:18]:
```suggestion
  # it'll work anyway, so we let the error slide.
```

**Review by imsodin — APPROVED** [review]
