### PR TITLE
gui, lib/model: Fix download progress accounting (fixes #5811)

### LINKED ISSUE #5811: Web interface: download progress of folders do not get updated
### Version Information

Syncthing: v1.1.4, macOS (64 bit)
macOS: 10.14.5 (18F132)
Browsers:
- Safari: 12.1.1 (14607.2.6.1.1)
- Firefox: 67.0.3 (64-Bit)
- Chrome: 75.0.3770.100 (Official Build) (64-Bit)

### Expected Behavior

- Download progress of remote folders get updated automatically

### Actual Behavior

- Download progress of remote folders do not get updated and are stuck to size and percentage values of when the web interface was loaded.
- Local status like download/upload rate do get updated
- A `DownloadProgress` object is logged periodically in the browser's console
- No errors are logged in the browser or syncthing
- Same behavior on all browsers listed above
- Progress is displayed correctly when the users refreshed the web interface by reloading

### PR DESCRIPTION
**Pull request by imsodin**
### Purpose

As usual with the web UI this wasn't as straight forward than I though, but this time the reason was in the model: Folder summaries are not sent on download progress events, but they do include information from download progress events. So if one wants to account download progress in the web UI, there's no way to know which download progress events are already accounted for in the last folder summary and which are not. Solution: Don't account download progress in folder summary. Anyone who wants the fine grained updates can do that subscribing to folder summaries and download progress events.

And I noticed the syncing status without a percentage at the end of a sync. In my opinion it's better to say that we are syncing at 100% (deleting stuff) than just syncing with no info, as the latter looks like there's still lots of work to do.

### Testing

Manual testing.

### CODE REVIEW

File: gui/default/syncthing/core/syncthingController.js [hunk 1]
```diff
@@ -808,11 +826,17 @@ angular.module('syncthing.core')
             if (typeof $scope.model[folder] === 'undefined') {
                 return 100;
             }
-            if ($scope.model[folder].globalBytes === 0) {
+            var global = $scope.model[folder].globalBytes;
```
Comment (AudriusButkevicius) [inline gui/default/syncthing/core/syncthingController.js]: Global is a keyword

File: lib/model/model.go [hunk 2]
```diff
@@ -809,7 +809,6 @@ func (m *model) NeedSize(folder string) db.Counts {
 			return true
 		})
 	}
-	result.Bytes -= m.progressEmitter.BytesCompleted(folder)
```
Comment (AudriusButkevicius) [inline lib/model/model.go]: Why is this going away?

**Comment by imsodin** [comment]
Yeah, let me condense the PR description to only contain the relevant bits:

Goal: Update sync percentage on download progress events.

Approach: Add download progress to the synced bytes in JS-land.

Problem: API adds download progress to the synced bytes in folder summary, but does not emit new folder summaries on download progress events. Thus JS-land may account download progress twice and has no way of detecting that.

Solution: Do not add download progress in folder summary, thus aligning the information in folder summaries with what triggers them. Info on download progress can still be obtained from download progress events.

Actually, that didn't get any shorter :|

File: lib/model/model.go (hunk 2 above)
Comment (imsodin) [reply lib/model/model.go]: This method is only used in folder summaries, where it is problematic (see https://github.com/syncthing/syncthing/pull/5815#issuecomment-505416623) and per its docstring:

> // NeedSize returns the number and total size of currently needed files.

Comment (AudriusButkevicius) [reply lib/model/model.go]: I think this should stay, as it changes what the API returns for no good reason.

Comment (imsodin) [reply lib/model/model.go]: > no good reason

The reason is to fix #5811 as I explained - I'd expect a bit more of an argument to judge that "no good reason".

The other option I see would be to add another method to the model API: `DownloadedBytes`, which cold then be added to folder summaries, which could then be used in the UI to do the accounting - but that's what I call adding an API method for no good reason...

I will happily consider concrete suggestions.

Comment (AudriusButkevicius) [reply lib/model/model.go]: Right, I was under the assumption this number was not used in the UI, so you are removing this to avoid double deductions?
What happens when a file download is finished, are we guaranteed a new summary event? 
Because files disappear from scope.progress, and percentage drops back down?

Comment (calmh) [reply lib/model/model.go]: I don’t think there are any guarantees, and there are timing aspects. There will likely be a period of time between the download progress deregistering and a folder update. I suggest we accept that the percentage drops back momentarily, or perhaps alter the GUI so that only folder update messages are allowed to reduce the percentage. The latter might be complicated...

Comment (imsodin) [reply lib/model/model.go]: I didn't think of the progress being dropped, thanks for pointing it out. Dropping percentages is ugly indeed, I'd go so far to say that I'd rather not reflect partial file downloads in the progress (like it is today) than having that. Weirdly I tested quite a lot manually and never saw this happening (I saw it stay at 100% for some time rather often though). I'll have a look whether I can get it to work without timing problems (or show that it already works :) ).

**Comment by imsodin** [comment]
DO NOT MERGE

I thought this was a minimal change and thus pushed and then tested -> it crashes.

**Comment by imsodin** [comment]
Now it works and while the change is actually tiny (schedule folder summary on download progress) the diff grew unfortunately - I recommend looking just at the second commit (the first is copy-pasting code into a separate function).

The reason I changed my mind is that there already is batching and backup from folder summaries if they take too much time. So just scheduling folder summaries on download progress is simple and doesn't have any of the discussed problems and doesn't change any API.

File: gui/default/index.html [hunk 3]
```diff
@@ -325,7 +325,7 @@ <h4 class="panel-title">
                   <span ng-switch-when="idle"><span class="hidden-xs" translate>Up to Date</span><span class="visible-xs" aria-label="{{'Up to Date' | translate}}"><i class="fas fa-fw fa-check"></i></span></span>
                   <span ng-switch-when="syncing">
                     <span class="hidden-xs" translate>Syncing</span>
-                    <span ng-show="syncRemaining(folder.id)">({{syncPercentage(folder.id) | percent}}, {{syncRemaining(folder.id) | binary}}B)</span>
```
Comment (calmh) [inline gui/default/index.html]: This is some sort of behavior change, we now always show the span, presumably with "100%, 0 b" in the in sync case?

Comment (calmh) [reply gui/default/index.html]: Or potentially like `undefined %, NaN b` in some other cases :D

Comment (imsodin) [reply gui/default/index.html]: > And I noticed the syncing status without a percentage at the end of a sync. In my opinion it's better to say that we are syncing at 100% (deleting stuff) than just syncing with no info, as the latter looks like there's still lots of work to do.

And is there any chance no folder summary was sent when pulling? That's the only reason needbytes may be undefined

Comment (calmh) [reply gui/default/index.html]: Deleting stuff should be at 95%, I think… I guess the status you’re seeing might be that we’ve got the latest folder summary but not yet the state change?

I guess things could  be undefined when starting up? The existing function checked for it, at least.

Comment (imsodin) [reply gui/default/index.html]: That's one option, the other is that we pulled everything, so nothing is needed anymore, but the puller is still processing deletions, that it does at the end, and thus the state is still syncing

The 95% thing concerns remote devices only.

Sure they could, but when starting folder status is unknown, then scanning and only then possibly pulling. I can't imagine no summary to have been sent at that point. And index.html is full of unchecked references to model

Comment (calmh) [reply gui/default/index.html]: My feeling was that since the undefined condition was handled previously, perhaps it was for a reason. But perhaps that reason is obsolete or a misunderstanding.

Personally I don’t think "Syncing, 100%, 0 b" while we are still working is in any way more informative than just "Syncing", but it’s a minor point 🤷‍♂
