### PR TITLE
lib/syncthing: Prevent hangup on error during startup (fixes #6043)

### LINKED ISSUE #6043: Cannot exit after failed startup
If syncthing encounters a fatal error during startup (for example it cannot listen on the API/GUI port) it should exit. Currently it does not, and also it cannot be made to exit after this point, ignoring Ctrl-C. It requires a hard kill to get rid of the process.

### PR DESCRIPTION
**Pull request by imsodin**
There was already some discussion in IRC, for context:

> 15:32:21 - imsodin: The current mechanism is built around the idea of the whole thing as being a "one-shot" operation. I.e. you start it and then wait for an error, therefore no cleaning up is being done and onces used. And that's mostly due to racyness, as e.g. the api can call `Stop` before `startup` returns. However's first at stopping/producing an error gets to do that. My approach at fixing it would have been to close `stopped` at creation, and re-create it after successful startup.
> 15:45:11 - calmh: we can think about it. i first thought it was an emergency, but it's at least a bit cornercasey so no panic to fix
> 15:47:56 - calmh: however i'm thinking that API wise i'm not super excited about things that start routines in the background and may or may not have done its thing when it returns
> 15:48:22 - calmh: i'd probably rather have seen a synchronous Run() method that blocks (essentially ending in a mainSupervisor.Serve() call)
> 15:48:39 - calmh: and then being able to call Stop() on that thing to make Run() return
> 15:49:16 - calmh: with an API promise that we call Run() and Stop() exactly once each
> 15:49:31 - calmh: obviating the need for sync.Once stuff etc

I then wrote a test to reproduce it and while at it some other behaviour. Besides fixing issues found by the test (error reporting), I added
 - the proposed promise that `Start` and `Run` should be called once only to the api, removing the need for `startOnce`. 
 - an error return value to `Start`.
 - removed a useless check in the `stopOnce`, which is always true (default value is `ExitSuccess` and `a.exitStatus` is only changed within the condition).

I believe `stopOnce` is still required, because even if `syncthing.App.Stop` is promised to be called once only, the app can still be closed from the rest api (and potentially in the future internal failure) - which needs to be race-protected.

And in `cmd/syncthing` I still use a `Start`/`Wait` combi instead of `Run`, as we need to know when the API is running before starting the browser.

### CODE REVIEW

File: cmd/syncthing/main.go [hunk 1]
```diff
@@ -647,7 +647,9 @@ func syncthingMain(runtimeOptions RuntimeOptions) {
 		}
 	}
 
-	app.Start()
+	if err := app.Start(); err != nil {
+		os.Exit(syncthing.ExitError)
```
Comment (golangcibot) [inline cmd/syncthing/main.go]: cannot use syncthing.ExitError (constant 1 of type syncthing.ExitStatus) as int value in argument to os.Exit (from `typecheck`)

File: lib/syncthing/syncthing.go [hunk 2]
```diff
@@ -358,6 +360,8 @@ func (a *App) startup() error {
 }
 
 func (a *App) run() {
+	a.stopped = make(chan struct{})
```
Comment (calmh) [inline lib/syncthing/syncthing.go]: This is a race, it happens concurrently with Wait()

**Comment by imsodin** [comment]
Completely forgot about this PR - should have gone into the RC. This is ready from my side.

File: lib/syncthing/syncthing.go [hunk 3]
```diff
@@ -89,25 +88,29 @@ func New(cfg config.Wrapper, ll *db.Lowlevel, evLogger events.Logger, cert tls.C
...
 	}
+	close(a.stopped) // Hasn't been started, so shouldn't block on Wait.
+	return a
 }
 
-// Run does the same as start, but then does not return until the app stops. It
+// Run does the same as Start, but then does not return until the app stops. It
 // is equivalent to calling Start and then Wait.
+// Either Run or Start may be called once only.
 func (a *App) Run() ExitStatus {
```
Comment (calmh) [inline lib/syncthing/syncthing.go]: Run() is unused, apart from a test that just checks that it does roughly what it says on the tin. I think we could do without it?
