### PR TITLE
fix(config): remove discontinued primary STUN server (fixes #10008)

### LINKED ISSUE #10008: Unresolvable stun.syncthing.net domain is still used by default
### What happened?

As seen in [stun.syncthing.net doesn’t resolve anymore](https://forum.syncthing.net/t/stun-syncthing-net-doesnt-resolve-anymore/24075/2?u=marbens) on the forums, stun.syncthing.net has been shut down, so I don't think it should still be referred to by default.

### Syncthing version

v1.29.3

### Platform & operating system

Arch Linux (64-bit AMD)

### Browser version

_No response_

### Relevant log output

```shell
2025-03-30 05:51:32 Enabled debug data for "stun"
2025-03-30 05:51:47 Starting stun for Stun@udp://[::]:22000
2025-03-30 05:51:47 Running stun for Stun@udp://[::]:22000 via stun.syncthing.net:3478
2025-03-30 05:51:47 Stun@udp://[::]:22000 stun addr resolution on stun.syncthing.net:3478: lookup stun.syncthing.net: no such host
2025-03-30 05:56:47 Starting stun for Stun@udp://[::]:22000
2025-03-30 05:56:47 Running stun for Stun@udp://[::]:22000 via stun.syncthing.net:3478
2025-03-30 05:56:47 Stun@udp://[::]:22000 stun addr resolution on stun.syncthing.net:3478: lookup stun.syncthing.net: no such host
2025-03-30 06:01:47 Starting stun for Stun@udp://[::]:22000
2025-03-30 06:01:47 Running stun for Stun@udp://[::]:22000 via stun.syncthing.net:3478
2025-03-30 06:01:47 Stun@udp://[::]:22000 stun addr resolution on stun.syncthing.net:3478: lookup stun.syncthing.net: no such host
2025-03-30 06:06:47 Starting stun for Stun@udp://[::]:22000
2025-03-30 06:06:47 Running stun for Stun@udp://[::]:22000 via stun.syncthing.net:3478
2025-03-30 06:06:47 Stun@udp://[::]:22000 stun addr resolution on stun.syncthing.net:3478: lookup stun.syncthing.net: no such host
```

### PR DESCRIPTION
**Pull request by marbens-arch**
The mechanism for primary STUN servers, is still intact, in case this gets retried with a different domain.

### Purpose

As seen in [stun.syncthing.net doesn’t resolve anymore](https://forum.syncthing.net/t/stun-syncthing-net-doesnt-resolve-anymore/24075/2?u=marbens) on the forums, stun.syncthing.net has been shut down, so I think it's probably a good idea to remove it.

### Testing

1. Have two or more devices
2. Disable Relaying
3. Have no Internet ports open on either end for incoming connections trigger STUN)
4. Enable the `stun` debugging facility in the Actions -> Logs -> Debugging Facilities
5. Verify that it doesn't output something like this within a few seconds:
```
2025-03-30 05:51:32 Enabled debug data for "stun"
2025-03-30 05:51:47 Starting stun for Stun@udp://[::]:22000
2025-03-30 05:51:47 Running stun for Stun@udp://[::]:22000 via stun.syncthing.net:3478
2025-03-30 05:51:47 Stun@udp://[::]:22000 stun addr resolution on stun.syncthing.net:3478: lookup stun.syncthing.net: no such host
```

### CODE REVIEW

File: lib/config/config.go [hunk 1]
```diff
@@ -71,7 +71,8 @@ var (
 
 	// DefaultPrimaryStunServers are servers provided by us (to avoid causing the public servers burden)
 	DefaultPrimaryStunServers = []string{
-		"stun.syncthing.net:3478",
+		// Discontinued because of misuse. See https://forum.syncthing.net/t/stun-server-misuse/23319?u=marbens
```
Comment (calmh) [inline lib/config/config.go:74]:
```suggestion
		// Discontinued because of misuse. See https://forum.syncthing.net/t/stun-server-misuse/23319
```

**Comment by calmh** [comment]
FWIW many of our secondaries also seem to be offline at the moment

**Review by calmh — APPROVED** [review]
I'm OK with this. We may want to revisit the set of servers used, but that can be a separate thing.
