### PR TITLE
lib/dialer: Try dialing without reuse in parallel (fixes #6892)

### LINKED ISSUE #6892: Syncthing 1.8.0 trying to connect via wrong network route
Related forum thread with details: https://forum.syncthing.net/t/syncthing-trying-to-connect-via-wrong-network-route/15476

Affected: Syncthing 1.8.0

Summary:
Syncthing explicitly specifies the source-IP when connecting to a remote device which ignores the routes configured in the operating system and can lead to problems connecting. Syncthing v.1.7.1 works fine in the same configuration.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Reusing the listen address influences the routing decision, which is not what we want in some cases.

### CODE REVIEW

File: lib/dialer/public.go [hunk 1]
```diff
@@ -125,19 +125,52 @@ func DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
...
+	var reuseConn, nonReuseConn net.Conn
+	var reuseErr, nonReuseErr error
+	reuseDone := make(chan struct{})
+	nonReuseDone := make(chan struct{})
+	go func() {
+		dialer := &net.Dialer{
+			Control:   ReusePortControl,
+			LocalAddr: laddr,
+		}
+		reuseConn, reuseErr = dialContextWithFallback(ctx, dialer, network, addr)
```
Comment (imsodin) [inline lib/dialer/public.go:157]: Earlier you checked the proxy env var already, so this will be a direct dial so might as well do that directly.

**Comment by calmh** [comment]
This is not super pretty imho as it triggers a weird warning (though INFO level) on every connection...

```
[MRIW7] 10:28:57 INFO: Listen (BEP/tcp): TLS handshake: EOF
[MRIW7] 10:28:57 INFO: Established secure connection to ...etc
```

**Comment by AudriusButkevicius** [comment]
wut, it shouldn't

**Comment by calmh** [comment]
I'm sure it does, but on the receiving side it's two connections, one of which gets dropped during the TLS handshake...

**Comment by AudriusButkevicius** [comment]
Right, I guess we could do it sequentially, rather than in parallel, but we'd potentially double the timeout.

**Comment by imsodin** [comment]
> Alternatively, we could not log failed TLS handshakes (as it might as well be a port scan etc), but it's sometimes useful to observe when firewall gets in the way.

Wouldn't the connection not even get through to the listener when a firewall gets in the way, i.e. it never comes to the tls handshake?

**Comment by AudriusButkevicius** [comment]
I've seen cases where the tcp handshake passes, then the firewall notices it's TLS by checking the first few bytes, and blocks it, because potentially it can't eavesdrop as it's configured.

File: lib/dialer/public.go [hunk 2]
```diff
@@ -125,19 +103,63 @@ func DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
...
+	var firstConn, secondConn net.Conn
+	var firstErr, secondErr error
+	firstDone := make(chan struct{})
+	secondDone := make(chan struct{})
+	go func() {
+		firstConn, firstErr = first(ctx, network, address)
+		l.Debugf("Dialing %s result %s %s: %v %v", firstName, network, address, firstConn, firstErr)
+		close(firstDone)
+	}()
+	go func() {
```
Comment (calmh) [inline lib/dialer/public.go:148]: Could we add a small delay here, like 1/3 the timeout or such, in the hope that in the normal case we never even get to the point of doing the second dial?

Comment (AudriusButkevicius) [reply lib/dialer/public.go:148]: It will be a bit ugly having to reach into the context to get the deadline, but sure.

Comment (calmh) [reply lib/dialer/public.go:148]: Well I mean a hardcoded 500ms would go a long way as well I think

File: lib/dialer/public.go [hunk 3]
```diff
@@ -125,19 +103,73 @@ func DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
...
+		time.Sleep(sleep)
+		secondConn, secondErr = second(ctx, network, address)
```
Comment (calmh) [inline lib/dialer/public.go:159]: Are we relying on that `first` succeeding will cause return and context cancellation and `second` then aborting early here? Otherwise I'd expect the sleep to be a select on `ctx`, `firstDone`, `time.After` so that we don't enter `second` if `first` succeeds

Comment (AudriusButkevicius) [reply lib/dialer/public.go:159]: firstDone can also be closed if it fails, so selecting on that doesn't really tell us if we should proceed or not.

Trying to come up with logic that covers this, but it's pretty hairy.

File: lib/dialer/public.go [hunk 4]
```diff
@@ -125,19 +103,85 @@ func DialContext(ctx context.Context, network, addr string) (net.Conn, error) {
...
+		firstConn, firstErr = first(ctx, network, address)
+		l.Debugf("Dialing %s result %s %s: %v %v", firstName, network, address, firstConn, firstErr)
+		close(firstDone)
+	}()
+	go func() {
+		select {
+		case <-firstDone:
+			if firstErr == nil {
+				// First succeeded, no point doing anything in second
+				close(secondDone)
```
Comment (calmh) [inline lib/dialer/public.go:162]: Should we set `secondErr = errors.New("didn't dial")` or something just in case? Otherwise LGTM
