### PR TITLE
gui: Fix favicon status (fixes #9149)

### LINKED ISSUE #9149: Favicon is stuck in notify state
As discussed in the forum: https://forum.syncthing.net/t/favicon-notification-breakdown-sticky-black-exclamation-mark-across-browsers/20882/7

https://github.com/syncthing/syncthing/pull/8918 removed the connection entry for the device itself:

https://github.com/syncthing/syncthing/blob/4f6b86a1c09b99aeb239d49c92ea7036f7a24e9e/lib/model/model.go#L745-L747

But this entry is required for the UI to properly determine the status of the device itself:

https://github.com/syncthing/syncthing/blob/4f6b86a1c09b99aeb239d49c92ea7036f7a24e9e/gui/default/syncthing/core/syncthingController.js#L1076-L1078

### PR DESCRIPTION
**Pull request by bt90**
### Purpose

Fixes #9149

### Testing

Live edit in Chrome.

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

File: gui/default/syncthing/core/syncthingController.js [hunk 1]
```diff
@@ -1176,8 +1179,8 @@ angular.module('syncthing.core')
                 return 'notify';
             }
 
-            // all used devices are paused except (this) one
-            if (pauseCount === deviceCount - 1) {
+            // all used devices are paused
+            if (pauseCount === deviceCount) {
```
Comment (otbutz) [inline gui/default/syncthing/core/syncthingController.js:1183]: I'd argue that we might change this one to `deviceCount > 0 && pauseCount === deviceCount`.

**Review by calmh — APPROVED** [review]
