### PR TITLE
lib/model: More precise deletion detection (fixes #2571, fixes #4573)

### LINKED ISSUE #2571: Replacing a directory with a symlink or vice versa is buggy
I found a curious behaviour when deleting directories and creating symbolic links.

Consider two machines One and Two. In One I make a directory A with a file a and a directory B with the same file a and another file b:

> ## 1
> 
>  One:~$ mkdir A B; touch A/a; cp A/a B; touch B/b; ls -R
> A:
> a
> B:
> a b

I wait until both machines are synchronized. Later I remove directory A and replace it by a symbolic link to B

> ## 2
> 
>  One:~$ rm -r A; ln -s B A; ls -R 
>   A:
>   a b
>   B:
>   a b

Synchronization fails at Two when it tries to delete A because the directory is not empty.

> ## 3
> 
> Two:~$ ls -R 
> A:
> a
> B:
> a b

To allow synchronization to complete, I remove the directory A

> ## 4
> 
> Two:~$ rm -r A; ls B
> a b

After synchronization completes A becomes a symbolic link in machine Two, as expected, but with the undesired consequence that in the process file a disappeared from directory B in both machines, whereas it was deleted from directory A in machine Two where it was not linked to directory B.

> ## 5
> 
> One:~$ ls -R
> A:
> b
> B:
> b
> 
> Two:~$ ls -R
> A:
> b
> B:
> b

If I wait after deleting A in machine One in step ##2 above, allowing synchronization to occur, and afterwards make the symbollic link, synchronization doesn't fail and I do not loose any file

> ## 2bis
> 
>  One:~$ rm -r A; sleep 120; ln -s B A; ls -R 
>   A:
>   a b
>   B:
>   a b
> ## 3bis
> 
> Two:~$ ls -R 
> A:
> a b
> B:
> a b

I am scanning my directories every minute. So it seems that syncthing gets confused when I perform the two operations, delete a directory and immediately substitute it by a symbolic link, before the first change is detected and synched.

### LINKED ISSUE #4573: Inaccessible files during scan are marked as deleted
Repro:

1. Create `dir/file` and make sure they are synced between devices A and B.
2. Change ownership/permission for `dir` on device A such that the user syncthing is running as is no longer able to access `dir` (e.g. `sudo chown root:root dir && sudo chmod 700 dir`).
3. Hit the rescan button on device A and wait for "changes" to propagate to B.

Result: `dir/file` gets deleted from device B.

Expected: Some kind of error or at least "nothing" (see #4480), but certainly not deletion of the file on the remote.

Origin of bug:  
Lstat returning any error is considered equal to file having been deleted: https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1989

Possible solutions:  
Maybe this can be handled with stricter checking of the error returned by Lstat. If we do this, I believe we need to add `IsNotExist(err) bool` to the filesystem interface to make sure all filesystem implementations are compatible with this check.  
The following idea doesn't actually work (we also detect "ordinary" deletes this way).<strike>It might be both more consistent and performant to drop these lstat checks and replace them by comparing the new file info with the one it has replaced. Thus cases like replacing a dir with a file can still be detected and handled, while the case described here wont result in data loss.</strike>  
Another possibility would be to implement #4480 and skip the current lstat tests on paths that failed to be scanned.

### PR DESCRIPTION
**Pull request by imsodin**
This fixes the same issues as #4584 but without the combined db/fs scan. The basic idea is to only mark files as deleted, if we really are sure they are deleted. I.e. only if the lstat error is `IsNotExist` or a parent is a link/file.

### CODE REVIEW

File: lib/model/model.go [hunk 1]
```diff
@@ -2066,6 +2064,14 @@ func (m *Model) internalScanFolderSubdirs(ctx context.Context, folder string, su
 						Deleted:    true,
 						Version:    f.Version.Update(m.shortID),
 					}
+					// We do not want to override the global version
```
Comment (calmh) [inline lib/model/model.go]: Move the comment inside the if, I was super confused about why we would not want to override the global file until I read on and realized it was for a corner case.

It's also confusing that we are inside an `!f.IsInvalid()` case and yet it may be invalid, but I guess that's Ok...

Comment (imsodin) [reply lib/model/model.go]: I dropped the if entirely from this PR. That is the change of behaviour introduced in #4750 and thus should be done there (didn't realize it when splitting this PR from the other one).

**Comment by imsodin** [comment]
I just run this PR together with the send-only metadata PR on my system and it ran smoothly.

Is this (still) good to go?
