### PR TITLE
fix(fs): store `getExpireAdd` mutex in `caseCache` (fixes #9836)

### LINKED ISSUE #9836: Memory leak in v1.28.0
### What happened?

After upgrading to v1.28.0, i am observing a rapid memory leak once Syncthing is started. It takes only a few minutes to fill all my 16GB of RAM. The issue also occurs on [v1.28.1-rc.2](https://github.com/syncthing/syncthing/releases/tag/v1.28.1-rc.2). The issue does not occur on v1.27.12, that version only uses around 700MB of memory (RES).

I did not see any useful log messages.

Interestingly enough, the OOM killer on this Debian system does not trigger, and the system just stays unresponsive forever (or at least for 12+ hours).

Stats (rounded):
Files: 900,000
Folders: 100,00
Size: 4.00 TiB 

I am not much into Go, is there an easy way to debug memory usage, or where allocations are made?

### Syncthing version

v1.28.0

### Platform & operating system

Linux amd64

### Browser version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by marbens-arch**
In #9701 there was a change that put the mutex used for `getExpireAdd` directly in `defaultRealCaser`, which is erroneous because multiple filesystems can share the same `caseCache`.

### Purpose

Fixes #9836 and [Slow sync sending files from Android](https://forum.syncthing.net/t/slow-sync-sending-files-from-android/24208?u=marbens). There may be other issues caused by `getExpireAdd` conflicting with itself, though.

### Testing

Unit tests pass and the case cache and conflict detection _seem_ to behave correctly.

### CODE REVIEW

**Comment by marbens-arch** [comment]
Whoops, accidentally made it cache the whole FS again.

File: lib/fs/casefs.go [hunk 1]
```diff
@@ -397,18 +397,23 @@ func (f *caseFilesystem) checkCaseExisting(name string) error {
 type defaultRealCaser struct {
 	cache *caseCache
 	fs    Filesystem
-	mut   sync.Mutex
 }
 
-type caseCache = lru.TwoQueueCache[string, *caseNode]
+type caseCache struct {
+	*lru.TwoQueueCache[string, *caseNode]
```
Comment (imsodin) [inline lib/fs/casefs.go]: nit: I don't think there's any need for this to be a pointer, we do already handle `caseCache` instances as pointers (and must to avoid copying the mutex). It was a pointer before the referenced change, but I don't see any reason for it to be a pointer there/in history either.

File: lib/fs/casefs.go [hunk 2]
```diff
@@ -445,8 +450,8 @@ func (r *defaultRealCaser) dropCache() {
 // getExpireAdd gets an entry for the given key. If no entry exists, or it is
 // expired a new one is created and added to the cache.
 func (r *defaultRealCaser) getExpireAdd(key string) *caseNode {
-	r.mut.Lock()
-	defer r.mut.Unlock()
+	r.cache.mut.Lock()
+	defer r.cache.mut.Unlock()
```
Comment (imsodin) [inline lib/fs/casefs.go]: optional, nit: Now that the lock is part of the cache again, might be more readable for this to be a method on `caseCache`  (revert to state before the referenced change) passing the filesystem as a parameter.

**Review by imsodin — COMMENTED** [review]
Nice catch. Lgtm, just two minor/optional suggestions inline.

Probably this doesn't have any impact in practice, as we don't use the same filesystem concurrently. At least not for operations where case matters (scanning, syncing). Of course still wrong and can happen e.g. if one adds more than one folder at the same path.

File: lib/fs/casefs.go (hunk 1 above)
Comment (marbens-arch) [reply lib/fs/casefs.go]: How do I properly get the `TwoQueueCache` and store it without putting a pointer in there? Current way of obtaining the `TwoQueueCache` is through `New2Q`, which returns a pointer.

Comment (imsodin) [reply lib/fs/casefs.go]: You can dereference the pointer when assigning it to `TwoQueueCache` by preceding it with `*`.

Comment (marbens-arch) [reply lib/fs/casefs.go]: govet [complains](https://github.com/syncthing/syncthing/actions/runs/18606737199/job/53057596680), and the upstream golang-lru developers didn't say they support copying the struct like that AFAIK.
```
copylocks: literal copies lock value from *cache: github.com/hashicorp/golang-lru/v2.TwoQueueCache[string, *github.com/syncthing/syncthing/lib/fs.caseNode] contains sync.RWMutex (govet)
```

**Comment by marbens-arch** [comment]
> Probably this doesn't have any impact in practice, as we don't use the same filesystem concurrently.

@imsodin You're correct that we don't use the same filesystem concurrently when syncing, and that's why this change **does** have a practical impact.

Syncthing creates a new "request handler filesystem" on every incoming request.

https://github.com/syncthing/syncthing/blob/20d2406a0eb93290820c30ba5eadf62cc27bd9e1/lib/model/model.go#L2032

Every request handler filesystem for a given folder has the same URI and options, and therefore the same fskeys, so the `caseCache` will be shared, but the mutex won't because it is (without this change) stored in the `defaultRealCaser`, and those are unique to the filesystem.

Requests are handled concurrently, so multiple request handler filesystems for the same folder might be accessed at the same time (this is way more likely on slow filesystems, like Android).

https://github.com/syncthing/syncthing/blob/20d2406a0eb93290820c30ba5eadf62cc27bd9e1/lib/protocol/protocol.go#L488

**Comment by marbens-arch** [comment]
Might fix #9836. I haven't had that issue personally but nonfunctional-most-of-the-time mutexes could cause multiple calls to `newCaseNode` (which calls `DirNames`) concurrently, which is higher than the memory usage of the one-at-a-time calls when mutexes are fully functional.

**Comment by imsodin** [comment]
> @imsodin You're correct that we don't use the same filesystem concurrently when syncing, and that's why this change **does** have a practical impact.

Yeah no I am wrong, you just charitably interpreted my statement :D  
I meant "same" as in equivalent filesystem, that results in using the same case cache. I just didn't remember that for requests we do create a new filesystem instance every time. Thanks for explaining this/correcting me!

File: lib/fs/casefs.go (hunk 1 above)
Comment (imsodin) [reply lib/fs/casefs.go]: Yep. As we only copy once, it likely isn't an issue, but still unnecessary just to avoid that pointer. Sorry to make you go back and forth on bad advice here.

**Comment by imsodin** [comment]
> Might fix https://github.com/syncthing/syncthing/issues/9836.

I am considering explicitly calling this fixed, and reopening if not. The heap profile there does indeed fit the problem fixed here very well, as the memory usage isn't in the cache itself but `os.File.readdir`. I'll wait with merging a bit to see if there's any opinions on this, otherwise I'll adjust to close/fix that issue on merge.

**Comment by marbens-arch** [comment]
Update: I deliberately tried to reproduce #9836 and succeeded.

I was able to consistently get high memory usage from a build without this change and was not able to with this change. Heap profiles show that it is caused by `os.(*File).readdir`, similarly to the profile mentioned in that issue.
