### PR TITLE
fix(model): check if remote folder state before pulling files (fixes #9686)

### LINKED ISSUE #9686: Sync status stays at 'Syncing xx%" when remote device pauses the folder.
### What happened?

Example: Just 2 syncthing devices sharing a single large folder.

Hi all,

Been seeing an issue recently whereby if, with large folders (5000+ files), syncthing is in the process of syncing the folder and then the folder is paused on the remote device, the local device will continue trying to pull the out of sync files and stay in "Syncing xx%" status instead of going to "Out of Sync". It does eventually get there, but on lower powered devices it takes a very long time.

I've worked around this in:
https://github.com/hireworksltd/syncthing/tree/remotefolderpaused-test
but I'm not completely familiar with the codebase and this seems like it could be a pretty expensive check to make if there are a lot of devices connected.

Any advice welcome!

Thanks so much,
Jon

### Syncthing version

v.1.27.9

### Platform & operating system

Linux amd64

### Browser version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hireworksltd**
### Purpose

As discussed in #9686 
Syncthing currently does not check folderstate on remote device before pulling. If no devices have a valid folderstate (i.e all devices have the folder paused) it will still attempt to pull. On large folders this will cause a hanging "Syncing" status.

This checks whether at least one connected device has the file available and has a valid folderstate.

### Testing
Tested locally on multiple devices.
We're new to Go (all our stuff is Python) so please bear with!
Interested if there may be a better place to slot this in.

Thanks,
Jon

### CODE REVIEW

File: lib/model/folder_sendrecv.go [hunk 1]
```diff
@@ -1092,6 +1092,20 @@ func (f *sendReceiveFolder) renameFile(cur, source, target protocol.FileInfo, sn
 // handleFile queues the copies and pulls as necessary for a single new or
 // changed file.
 func (f *sendReceiveFolder) handleFile(file protocol.FileInfo, snap *db.Snapshot, copyChan chan<- copyBlocksState) {
+	
+	available := false
+   	for _, dev := range snap.Availability(file.Name) {
```
Comment (tomasz1986) [inline lib/model/folder_sendrecv.go:1097]: Just cosmetics, but please fix the current mixture of spaces and tabs that you've got here. All lines in this file are affected. The spaces should be changed into tabs.

Comment (hireworksltd) [reply lib/model/folder_sendrecv.go]: Thanks Tomasz, no idea how I managed that!

File: lib/model/model.go [hunk 2]
```diff
@@ -110,6 +110,7 @@ type Model interface {
 	FolderStatistics() (map[string]stats.FolderStatistics, error)
 	UsageReportingStats(report *contract.Report, version int, preview bool)
 	ConnectedTo(remoteID protocol.DeviceID) bool
+	IsFolderPausedOnDevice(folder string, device protocol.DeviceID) bool
```
Comment (calmh) [inline lib/model/model.go:113]: This is the cause of all the build failures; no need to add it to the interface since it's not used outside the package.

File: lib/model/model.go [hunk 3]
```diff
@@ -2195,6 +2196,20 @@ func (m *model) ConnectedTo(deviceID protocol.DeviceID) bool {
 	return ok
 }
 
+// Check if folderstate is valid for a particular device (i.e not paused)
+func (m *model) IsFolderPausedOnDevice(folder string, device protocol.DeviceID) bool {
```
Comment (calmh) [inline lib/model/model.go:2200]: Since it's not used outside the package, `isFolderPausedOnDevice`

File: lib/model/folder_sendrecv.go [hunk 4]
```diff
@@ -1092,6 +1092,20 @@ func (f *sendReceiveFolder) renameFile(cur, source, target protocol.FileInfo, sn
 // handleFile queues the copies and pulls as necessary for a single new or
 // changed file.
 func (f *sendReceiveFolder) handleFile(file protocol.FileInfo, snap *db.Snapshot, copyChan chan<- copyBlocksState) {
+	
+	available := false
+	for _, dev := range snap.Availability(file.Name) {
+		if !f.model.IsFolderPausedOnDevice(f.folderID, dev) {
+		available = true
+		break
+		}
```
Comment (AudriusButkevicius) [inline lib/model/folder_sendrecv.go:1101]: funky indent

File: lib/model/folder_sendrecv.go [hunk 5]
```diff
@@ -1092,6 +1092,20 @@ func (f *sendReceiveFolder) renameFile(cur, source, target protocol.FileInfo, sn
 // handleFile queues the copies and pulls as necessary for a single new or
 // changed file.
 func (f *sendReceiveFolder) handleFile(file protocol.FileInfo, snap *db.Snapshot, copyChan chan<- copyBlocksState) {
+	
+	available := false
+	for _, dev := range snap.Availability(file.Name) {
+		if !f.model.IsFolderPausedOnDevice(f.folderID, dev) {
+		available = true
```
Comment (imsodin) [inline lib/model/folder_sendrecv.go:1099]: Where `handleFile` is called there's already a check for availability - would make sense to add the pause check there.

File: lib/model/model.go (hunk 2 above)
Comment (hireworksltd) [reply lib/model/model.go]: Thanks! have removed from model and simplified into processNeeded availability check.

File: lib/model/folder_sendrecv.go (hunk 4 above)
Comment (hireworksltd) [reply lib/model/folder_sendrecv.go]: Thanks, have removed in new commit.

File: lib/model/model.go [hunk 6]
```diff
@@ -2195,6 +2196,20 @@ func (m *model) ConnectedTo(deviceID protocol.DeviceID) bool {
...
+	m.mut.RLock()
+	defer m.mut.RUnlock()
+
+	if states, ok := m.remoteFolderStates[device]; ok {
+		if state, ok := states[folder]; ok {
+			return state != remoteFolderValid
```
[the remark this answers is not in the document]
Comment (hireworksltd) [reply lib/model/model.go]: Hi Simon,

I vaguely recall this being added (or extended) in the last couple of years to show remoteFolderPaused so I assume that older versions of Syncthing will return valid regardless of paused state as long as the folder is shared?

folderstate.go
```
func (s remoteFolderState) String() string {
	switch s {
	case remoteFolderUnknown:
		return "unknown"
	case remoteFolderNotSharing:
		return "notSharing"
	case remoteFolderPaused:
		return "paused"
	case remoteFolderValid:
		return "valid"
	default:
		return "unknown"
	}
}

```

[the remark this answers is not in the document]
Comment (imsodin) [reply lib/model/model.go]: Not entirely sure and no time right now to investigate. Generally there's no need to avoid a solution that doesn't work for very old clients. So as long as you default to "assume available" on unclear/missing states, that should be all good.

[the remark this answers is not in the document]
Comment (hireworksltd) [reply lib/model/model.go]: Thanks, I'll check and make sure that's the case.

File: lib/model/folder_sendrecv.go [hunk 7]
```diff
@@ -508,15 +508,20 @@ nextFile:
 		devices := snap.Availability(fileName)
 		for _, dev := range devices {
 			if f.model.ConnectedTo(dev) {
-				// Handle the file normally, by copying and pulling, etc.
-				f.handleFile(fi, snap, copyChan)
-				continue nextFile
+				// Check if the remote folder state is valid on connected device (i.e. not paused)
+				if state, ok := f.model.remoteFolderStates[dev][f.folderID]; ok {
```
Comment (imsodin) [inline lib/model/folder_sendrecv.go:512]: You cannot access `remoteFolderStates` without holding a read lock on the mutex in model. And it feels a bit messy to do that from here. I'd create a utility function in model for this. Respectively it looks like it almost already exists `model.availabilityInSnapshotRLocked` - just that it's for a block instead of the entire file. You could split that into two functions, one for the part with the snapshot, one with the devicedownloads. Then use the snapshot function here. Ok that explanations sounds unintelligible on re-reading, maybe some pseudo-code is clearer:

Split functions in model, and new "wrapper" function (also need to adapt callers to the split functions, leaving that out):

```
func (m *model) availabilityInSnapshot(cfg config.FolderConfiguration, snap *db.Snapshot, file protocol.FileInfo) []Availability {
	m.mut.RLock()
	defer m.mut.RUnlock()
	return m.availabilityInSnapshotRLocked(...)
}

func (m *model) availabilityInSnapshotRLocked(cfg config.FolderConfiguration, snap *db.Snapshot, file protocol.FileInfo) []Availability {
	var availabilities []Availability
	for _, device := range snap.Availability(file.Name) {
...
	return availabilities
}

func (m *model) availabilityFromTemporaryRLocked(cfg config.FolderConfiguration, file protocol.FileInfo, block protocol.BlockInfo) []Availability {
	var availabilities []Availability
	for _, device := range cfg.Devices {
...
	return availabilities
}
```

And then here just:

```
if devices := f.model.availabilityInSnapshot(...); len(devices) > 0 {
f.handleFile(...)
}
```

Does that make any sense?

Comment (hireworksltd) [reply lib/model/folder_sendrecv.go:512]: Yup, Sounds good!
will look at this tomorrow.

File: lib/model/model.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (acolomb) [reply lib/model/model.go]: `remoteFolderValid` is an enumeration constant which was introduced in #8201 and #8283, replacing the previous `Accepted` boolean flag on `type FolderCompletion` and the `model.remotePausedFolders` set (now `model.remoteFolderStates`).

I don't think there's any chance of incompatibility here, as that didn't change the protocol.  It just changed the way the detected remote folder state is stored in the model.

File: lib/model/folder_sendrecv.go (hunk 7 above)
Comment (imsodin) [reply lib/model/folder_sendrecv.go:512]: Hi again @hireworksltd. This PR just came up because of a potentially related support request, thus reminded me of it - forgot about it before. No pressure or anything, just a reminder in case it's been forgotten in the hopes to be helpful (at least to me it usually is :) ).

Comment (hireworksltd) [reply lib/model/folder_sendrecv.go:512]: Hi Simon,

Sorry been a bit mad here last few weeks! Will try set aside some time over the next few days.

Best,
Jon

Comment (imsodin) [reply lib/model/folder_sendrecv.go:512]: Thanks for the update - all good, no pressure. Also the original offer still stands, that I could do/finish the change if you'd rather spend your time on something else. (I hope that doesn't come across as passive-aggressiv or push, really just an offer :) )

Comment (imsodin) [reply lib/model/folder_sendrecv.go:512]: Yes that looks good, thanks. There's a few things that look off, but they are small, the general approach holds up. If you push those changes to the branch here (or create a new PR), I can point those things out with comments inline - simpler than trying to describe them.

Comment (hireworksltd) [reply lib/model/folder_sendrecv.go]: Many thanks!

File: lib/model/model.go [hunk 8]
```diff
@@ -2882,16 +2882,30 @@ func (m *model) Availability(folder string, file protocol.FileInfo, block protoc
...
+}
+
+func (m *model) availabilityFromTemporaryRLocked(cfg config.FolderConfiguration, file protocol.FileInfo, block protocol.BlockInfo) []Availability {
+	var availabilities []Availability
+	for _, device := range cfg.Devices {
+		if m.deviceDownloads[device.DeviceID].Has(cfg.ID, file.Name, file.Version, int(block.Offset/int64(file.BlockSize()))) {
+			availabilities = append(availabilities, Availability{ID: device.DeviceID, FromTemporary: true})
+		}
+	}
+	return availabilities
```
Comment (imsodin) [inline lib/model/model.go:2905]: optinal suggestion: If you move this function below `availabilityInSnapshotRLocked` the diff might be smaller and also the order matches the reading order in `Availability`.

File: lib/model/model.go [hunk 9]
```diff
@@ -2882,16 +2882,30 @@ func (m *model) Availability(folder string, file protocol.FileInfo, block protoc
 	}
 	defer snap.Release()
 
-	return m.availabilityInSnapshotRLocked(cfg, snap, file, block), nil
+	if devices := m.availabilityInSnapshot(cfg, snap, file); len(devices) > 0 {
+		return devices, nil
+	}
+
+	return m.availabilityFromTemporaryRLocked(cfg, file, block), nil
```
Comment (imsodin) [inline lib/model/model.go:2889]: You don't actually hold the read lock here. You likely want to acquire it before calling both `availability` functions, and call the `...RLocked` variant of those in both cases.

File: lib/model/folder_sendrecv.go [hunk 10]
```diff
@@ -1547,7 +1544,7 @@ func (f *sendReceiveFolder) pullBlock(state pullBlockState, snap *db.Snapshot, o
 	}
 
 	var lastError error
-	candidates := f.model.availabilityInSnapshot(f.FolderConfiguration, snap, state.file, state.block)
+	candidates := f.model.availabilityInSnapshot(f.FolderConfiguration, snap, state.file)
```
Comment (imsodin) [inline lib/model/folder_sendrecv.go:1547]: Here we still need candidates from both the snapshot or downloads. Either you call both new methods here, or likely cleaner/simpler you create another internal function e.g. lower-case `availability` which does that, and then also use that function in `Availability`.

File: lib/model/model.go [hunk 11]
```diff
@@ -2882,16 +2882,30 @@ func (m *model) Availability(folder string, file protocol.FileInfo, block protoc
 	}
 	defer snap.Release()
 
-	return m.availabilityInSnapshotRLocked(cfg, snap, file, block), nil
+	if devices := m.availabilityInSnapshot(cfg, snap, file); len(devices) > 0 {
+		return devices, nil
```
Comment (imsodin) [inline lib/model/model.go:2886]: Previous behaviour wasn't to abort/return here, but to continue with temporary downloads and append any devices found there.

**Comment by hireworksltd** [comment]
Thanks! Have made/testing the changes, hopefully this makes more sense.

File: lib/model/folder_sendrecv.go (hunk 10 above)
Comment (imsodin) [reply lib/model/folder_sendrecv.go:1547]: Still applies - you need to call `m.availability(...` here.

**Comment by imsodin** [comment]
> Thanks! Have made/tested the changes, hopefully this makes more sense.

There are still a few issues around locking. Rereading my last round of comments it clearly wasn't complete - turns out to be quite hard to give correct and complete feedback and suggestions here. Especially because the locking behaviour/requirements/naming-conventions in model are a bit convoluted (to put it mildly).

Would you mind if instead of pointing out a new set of issues and suggestions, and likely failing to do that complete again, I did the remaining adjustments to code as I'd expect them and send you a diff, such that you can incorporate that into your branch/PR (and amend if desired of course)?

**Comment by hireworksltd** [comment]
By all means! Thanks.

was a bit confused with the locking.. would Availability not hold mutex for availability (and InSnapshotRLocked/FromTemporaryRLocked)?

**Comment by imsodin** [comment]
> was a bit confused with the locking.. would Availability not hold mutex for availability (and InSnapshotRLocked/FromTemporaryRLocked)?

It does - I think I was wrong/confused in that one comment. So yeah, we can add to my comments not being complete, also wrong (at least partially) - sorry about that.

Here is my proposed change. However please do check it, I am also prone to make mistakes when coding, not just commenting :)  
https://github.com/syncthing/syncthing/compare/main...imsodin:syncthing:remotefolderpaused  
I kinda hoped I messed up more in comments, and I can get rid of some of the methods. However I double checked and they are all needed, as in used twice or used from the folder code (while we could, I don't want to do model locking there - that complexity shouldn't proliferate). All these boilerplate methods don't seem nice at all, but I still think it's the least bad way to go, at least I don't see a better atm. Also the names annoyed me so much (meaningless), that I couldn't resist renaming them - of course feel free to not adopt that if the new names don't seem like an improvement to you.

**Comment by hireworksltd** [comment]
> > was a bit confused with the locking.. would Availability not hold mutex for availability (and InSnapshotRLocked/FromTemporaryRLocked)?
> 
> It does - I think I was wrong/confused in that one comment. So yeah, we can add to my comments not being complete, also wrong (at least partially) - sorry about that.
> 
> Here is my proposed change. However please do check it, I am also prone to make mistakes when coding, not just commenting :) [main...imsodin:syncthing:remotefolderpaused](https://github.com/syncthing/syncthing/compare/main...imsodin:syncthing:remotefolderpaused) I kinda hoped I messed up more in comments, and I can get rid of some of the methods. However I double checked and they are all needed, as in used twice or used from the folder code (while we could, I don't want to do model locking there - that complexity shouldn't proliferate). All these boilerplate methods don't seem nice at all, but I still think it's the least bad way to go, at least I don't see a better atm. Also the names annoyed me so much (meaningless), that I couldn't resist renaming them - of course feel free to not adopt that if the new names don't seem like an improvement to you.

I think the naming change absolutely makes sense and makes things clearer and see what you mean now re: missing lock! Thanks for this.

**Review by imsodin — APPROVED** [review]
Nice. Thanks again for finding this issue and providing a fix!

This looks good now from my pov, but given the last amendments are mine I'll leave the PR unmerged for a while, such that others have an opportunity to have a look over it.
