### PR TITLE
lib/versioner: Improve error messages (fixes #7354)

### LINKED ISSUE #7354: Error message when external versioning fails is ambiguous
If external versioning fails to move a file, we get the following error.

The problem is that the error message, i.e. `exit status 255` means nothing to the user. It would be better to have something specifically saying that the file could not be versioned or such.

Tested with Syncthing v1.13.1.

### PR DESCRIPTION
**Pull request by imsodin**
Attaches stderr (shortened if long) to the error when external versioner fails and adds a `*type* versioner: *operation*:` prefix to all errors returned for context (e.g. `simple versioner: get versions: permission denied`). 

All the change outside of `lib/versioner` is just noop boilerplate to use `errors.Is` in one test instead of fragile string testing.

### CODE REVIEW

**Comment by calmh** [comment]
Keeping in mind that even if this is probably fine, the gui by default cuts at the last colon and only shows that part...

**Review by calmh — DISMISSED** [review]

**Comment by tomasz1986** [comment]
I have compiled and tested the PR, and this is how the GUI looks right now.

image

The relevant log entry:

```
[7ZL7H] DEBUG: sendreceive/su9ww-gwwzx@0xc000028380 Deleting file  %&()
[7ZL7H] DEBUG: sendreceive/su9ww-gwwzx@0xc000028380 new error for  %&(): delete file: external versioner: archive: exit status 255
[7ZL7H] DEBUG: sendreceive/su9ww-gwwzx@0xc000028380 changed 1 on try 3
[7ZL7H] INFO: Puller (folder "test1" (su9ww-gwwzx), item " %&()"): syncing: delete file: external versioner: archive: exit status 255
```

File: lib/model/model.go [hunk 1]
```diff
@@ -2637,11 +2637,11 @@ func (m *model) RestoreFolderVersions(folder string, versions map[string]time.Ti
 		return nil, errNoVersioner
 	}
 
-	restoreErrors := make(map[string]string)
+	restoreErrors := make(map[string]error)
 
 	for file, version := range versions {
 		if err := ver.Restore(file, version); err != nil {
-			restoreErrors[file] = err.Error()
+			restoreErrors[file] = err
```
Comment (AudriusButkevicius) [inline lib/model/model.go:2644]: What happens when you pass errors to json serialiser?
I assume this now might become an object and break the UIs expectations?

**Review by AudriusButkevicius — DISMISSED** [review]

**Review by AudriusButkevicius — APPROVED** [review]
