### PR TITLE
lib/versioner: expand tildes in version directory (fixes #9241)

### LINKED ISSUE #9241: Versions path does not honor tilde (~) shortcut
Hi,

It seems the folder path honors the ~ shortcut, but the versions path does not. This results in rather unexpected behavior. Should the ~ logic not be hooked on both places?

## Situation
Vanilla Syncthing running in a docker container.

## Folder config
Folder path: `~/myfolder/data`
Versions path: `~/myfolder/versions`

## Expected behavior:
- Synced data in `/var/syncthing/myfolder/data`
- Remote deleted data in `/var/syncthing/myfolder/versions`

## Observed behavior:
- Synced data in `/var/syncthing/myfolder/data`
- Remote deleted data in `/var/syncthing/myfolder/data/~/myfolder/versions`

## Additional information
- Syncthing version: v1.26.1 `Gold Grasshopper` (latest as of writing this ticket)
 - OS context: New Linux kernel + [official docker image](https://hub.docker.com/r/syncthing/syncthing/)

### PR DESCRIPTION
**Pull request by nf**
### Purpose

Fix #9241 by expanding tildes in version paths.

When creating the versioner file system, first try to expand any leading tildes to the user's home directory before handling relative paths. This makes a version path `"~/p"` expand to `"$HOME/p"` instead of `"/folder/~/p"`.

### Testing

Added a test to lib/versioner that exercises this code path. Also manually tested with local syncthing instances.

### CODE REVIEW

**Review by calmh — APPROVED** [review]

File: lib/versioner/simple_test.go [hunk 1]
```diff
@@ -93,3 +95,63 @@ func TestSimpleVersioningVersionCount(t *testing.T) {
...
 	}
 }
+
+func TestPathTildes(t *testing.T) {
+	// Test that folder and version paths with leading tildes are expanded
+	// to the user's home directory. (issue #9241)
+	home := t.TempDir()
+	t.Setenv("HOME", home)
+	t.Setenv("USERPROFILE", home)
+	os.Mkdir(filepath.Join(home, "folder"), 0755)
```
Comment (calmh) [inline lib/versioner/simple_test.go:105]: This fails on the Windows runner, probably because our legacy HOMEDRIVE/HOMEPATH check takes precedence over USERPROFILE.

**Review by calmh — COMMENTED** [review]
Thanks, and welcome, and thanks for Go and all :)

File: lib/versioner/simple_test.go (hunk 1 above)
Comment (nf) [reply lib/versioner/simple_test.go]: Ah gotcha, fixed.

Comment (nf) [reply lib/versioner/simple_test.go]: Hmm, not fixed.
```
\\?\C:\C:\Users\RUNNER~1\AppData\Local\Temp\TestPathTildes1447117282\001\folder\test: The filename, directory name, or volume label syntax is incorrect.
```

Not sure where the extra `C:\` is coming from. Will take another look later today.

**Comment by nf** [comment]
Thanks for the fix! ❤️
