### PR TITLE
lib/fs: Add invalid UTF-8 guards to Matcher and Watcher (fixes #9369)

### LINKED ISSUE #9369: panic upon start - slice bounds out of range
### Does your log mention database corruption?
No

### Include required information
**Version**: Breaks on `1.27.2` and the current git `main` branch (`45beb28f`)

Hello devs, thanks for all the hard work. I hadn't updated syncthing in a while and I started seeing a panic in my logs after doing a system update. The panic seems to happen after syncthing finishes scanning all my folders.

I am unfortunately not sure how to reproduce the problem at this time. The earliest error log is of version `1.27.2`. Perhaps something to do with the file that syncthing didn't have read permissions on? I attached the logs with personal info removed.
[panic-20240126-012105.reported.log](https://github.com/syncthing/syncthing/files/14058310/panic-20240126-012105.reported.log)

### PR DESCRIPTION
**Pull request by kylosus**
### Purpose

Add invalid UTF-8 guards to fix #9369. Probably not a permanent fix, but putting it up here in case someone else encounters the same panic.

### Testing

All tests pass. I was going to add a test to `basicfs_watch` but there doesn't seem to be a straightforward way to test for unexpected events.

### CODE REVIEW

File: lib/ignore/ignore.go [hunk 1]
```diff
@@ -214,6 +214,9 @@ func (m *Matcher) parseLocked(r io.Reader, file string) error {
 // Match matches the patterns plus temporary and internal files.
 func (m *Matcher) Match(file string) (result ignoreresult.R) {
 	switch {
+	case !utf8.ValidString(file):
```
Comment (imsodin) [inline lib/ignore/ignore.go:217]: Lets not do this here - except for `lib/fs` that you are also fixing, the input will always be valid utf-8.

File: lib/fs/basicfs_watch.go [hunk 2]
```diff
@@ -38,10 +39,16 @@ func (f *BasicFilesystem) Watch(name string, ignore Matcher, ctx context.Context
 	}
 
 	absShouldIgnore := func(absPath string) bool {
+		if !utf8.ValidString(absPath) {
```
Comment (imsodin) [inline lib/fs/basicfs_watch.go:42]: We also need this check on L93/100. I am not 100% sure, but I think even if notify is working perfectly it's not guaranteed that the filter is applied: It might only be applied to watches that are set up, i.e. parent directories - the event of a file inside that directory might still be invalid. And even if that's not the case, I wouldn't trust it fully.

File: lib/fs/basicfs_watch.go [hunk 3]
```diff
@@ -38,10 +39,16 @@ func (f *BasicFilesystem) Watch(name string, ignore Matcher, ctx context.Context
...
+			return true
+		}
+
 		rel, err := f.unrootedChecked(absPath, roots)
+
```
Comment (imsodin) [inline lib/fs/basicfs_watch.go:47]: Lets not separate the error check from the line that creates the error.

**Comment by bt90** [comment]
Do we log these files somewhere?

File: lib/fs/basicfs_watch.go (hunk 2 above)
Comment (kylosus) [reply lib/fs/basicfs_watch.go:42]: Maybe it's best to do all these in ignore.go instead then to have one place where files are filtered out? Could repurpose Match() to be a universal filter (check file type/name + ignore patterns, etc.) instead of sanitizing separately in several places. It can return a Result instead of a bool.

Comment (imsodin) [reply lib/fs/basicfs_watch.go:42]: > Maybe it's best to do all these in ignore.go instead then to have one place where files are filtered out? Could repurpose Match() to be a universal filter (check file type/name + ignore patterns, etc.) instead of sanitizing separately in several places. It can return a Result instead of a bool.

I can see how always checking in `ignore` is attractively simple/general/failure proof. And `Match()` already does return a result type (since a very short time), so that doesn't even need to change (just a new value to be added).

My gut feeling is still to designate `ignore` as requiring valid utf-8 input like most of the code, and filtering non-utf-8 strings in lib/fs when using `Matcher`. However that's a weakly held opinion based on the conflicting arguments I try to explain below - I am very ready/likely to be convinced otherwise. Or maybe to not protract this too much, just get a third opinion as a tie-breaker - as in of course feel free to not engage in this discussion further if you don't feel like it:

I see how it's magic/non-obvious that `lib/scanner` acts as an utf-8-validness-barrier for code sitting behind or in front of it. And the magic is that if "one knows", then it's clear that `lib/fs` and related code is in front, while everything else (famously descriptive "model", i.e. all of database, syncing, protocol) is behind it. At the same time it's also nice to be able to just postulate that everything is valid utf-8 and not need to think about it in that code.

I was initially hesitant performance wise as it will be redundant in most places, however I subsequently tried to make a good argument and couldn't. Respectively only for the scanner, and there we already do that check which we could now skip. Then again it's also not overly nice to do/hide utf-8 validation in `ignore.Matcher` - seems to violate the "least surprise" principle to me, and I like that one. Then again we drop internal files on `ignore.Match` - not entirely obvious from the name either.

**Comment by imsodin** [comment]
> Do we log these files somewhere?

In the scanner: https://github.com/syncthing/syncthing/blob/main/lib/scanner/walk.go#L280  
Ignoring in the watcher makes sense - seems sufficient to trigger an error/log on periodic scans for this only, not by watching.

File: lib/ignore/ignore.go (hunk 1 above)
Comment (kylosus) [reply lib/ignore/ignore.go:217]: It seems not, reverting this commit leads to the same panic originating from `watchLoop` when files are added/removed:
https://github.com/syncthing/syncthing/blob/45beb28fa5b051d14a10f102a05ec46d36ecaa75/lib/fs/basicfs_watch.go#L93
I'll push another commit to address it

File: lib/fs/basicfs_watch.go [hunk 4]
```diff
@@ -78,7 +83,14 @@ func (f *BasicFilesystem) watchLoop(ctx context.Context, name string, roots []st
 
 		select {
 		case ev := <-backendChan:
-			relPath, err := f.unrootedChecked(ev.Path(), roots)
+			evPath := ev.Path()
+
+			if !utf8.ValidString(evPath) {
+				l.Debugln(f.Type(), f.URI(), "Watch: Ignoring invalid UTF-8")
+				return
```
Comment (imsodin) [inline lib/fs/basicfs_watch.go:90]: This should be a continue - it's not fatal to get an event for a file with invalid utf-8.

File: lib/fs/basicfs_watch.go (hunk 2 above)
Comment (kylosus) [reply lib/fs/basicfs_watch.go:42]: Honestly you know the code better than me, so I'll concede on it. My best argument is that it feels more correct to have all the validation and checks in one place so unexpected panics like this don't happen in the future because some part of the code forgot to do a check or the are at least easier to track down.

File: lib/fs/basicfs_watch.go (hunk 4 above)
Comment (kylosus) [reply lib/fs/basicfs_watch.go]: Sorry about that

Comment (imsodin) [reply lib/fs/basicfs_watch.go]: No need to be sorry ;)

File: lib/fs/basicfs_watch.go (hunk 2 above)
Comment (imsodin) [reply lib/fs/basicfs_watch.go:42]: > Honestly you know the code better than me [...]

That's a double edge sword - it also makes me subsceptible to conservatism/favouring the status quo :)

**Review by imsodin — APPROVED** [review]
