### PR TITLE
lib/model: Clean up index handler life cycle (fixes #9021)

### LINKED ISSUE #9021: panic: bug: ClusterConfig called on closed or nonexistent connection
While some builds are [succeeding](https://github.com/syncthing/syncthing/actions/workflows/build-syncthing.yaml), three recent builds:

https://github.com/syncthing/syncthing/actions/runs/5777466439/job/15660650363#step:7:1738 (Go 1.19, but not 1.20)
https://github.com/syncthing/syncthing/actions/runs/5778159436/job/15659077804#step:7:1798 (Go 1.19, but not 1.20)
https://github.com/syncthing/syncthing/actions/runs/5780780108/job/15664908391#step:7:1742 (**Go 1.20, but not 1.19**)

all panicked with
```
panic: bug: ClusterConfig called on closed or nonexistent connection
```
This panic is emitted at [lib/model/model.go:1176](https://github.com/syncthing/syncthing/blob/e09146ee0326e22bc967f7bdf33bfe988f79effa/lib/model/model.go#L1176).

It may be related to https://github.com/syncthing/syncthing/pull/9007 which touched the code [near](https://github.com/syncthing/syncthing/commit/9d21b91124d6465e77542768317e2b0a764fffa5#diff-e882cd3f44253874ec7412e2e30f7ba0fa7e42e74a964a33e3658bef5ee6f833) this panic call.

### PR DESCRIPTION
**Pull request by calmh**
This is an alternative to #9035. There's a certain amount of overengineering here, possibly, but hear me out...

- There's a new thing called a `serviceMap`. This is essentially a map of key -> service plus key -> Suture-token and some management to make sure that adding and removing things from the map does the right things for the services in question. This reduces boilerplate since we have this pattern in a couple of places. The serviceMap is itself a Service that runs the children.
- The index handler registry now uses one of these to manage the index handlers
- The model now uses one of these to manage the index handler registries
- I think it all works out quite nicely, stopping one thing stops all the children, and we now remove (stop) the index handler registry for a device when we close the connection.

We can also use this serviceMap for the folder runners, but that's a large refactor-only diff that we can save for later...

### CODE REVIEW

File: lib/model/model.go [hunk 1]
```diff
@@ -1792,7 +1793,7 @@ func (m *model) Closed(conn protocol.Connection, err error) {
 	delete(m.remoteFolderStates, device)
 	closed := m.closed[device]
 	delete(m.closed, device)
-	delete(m.indexHandlers, device)
+	m.indexHandlers.RemoveAndWait(device, 0)
```
Comment (calmh) [inline lib/model/model.go:1796]: I believe this is the relevant point that fixes #9021, as per my understanding of #9035...

File: lib/model/service_map.go [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+	}
+	m.supervisor = suture.New(m.String(), svcutil.SpecWithDebugLogger(l))
+	return m
+}
+
+// Add adds a service to the map, starting it on the supervisor. If there is
+// already a service at the given key, it is removed first.
+func (s *serviceMap[K, S]) Add(k K, v S) {
+	if tok, ok := s.tokens[k]; ok {
+		// There is already a service at this key, remove it first.
```
Comment (calmh) [inline lib/model/service_map.go:41]: Alternatively, we could call this incorrect usage and panic, since it's likely to be caused by a missing Remove at some point...

Comment (imsodin) [reply lib/model/service_map.go:41]: Or a middle ground: Panic if it's an RC, send a failure event (and thus report) otherwise.

**Comment by imsodin** [comment]
At first glance the service map has more `lib/svcutil` vibes than model vibes (haven't actually reviewed yet, so maybe it obviously isn't).

File: lib/model/service_map.go [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+		found = true
+		s.supervisor.RemoveAndWait(tok, timeout)
+	}
+	delete(s.services, k)
+	delete(s.tokens, k)
+	return found
+}
+
+// Each calls the given function for each service in the map.
+func (s *serviceMap[K, S]) Each(fn func(K, S)) {
```
Comment (imsodin) [inline lib/model/service_map.go:82]: We do this over exposing the map and just looping over that at the caller, to prevent the caller from messing with the map?

(Also I want `range` over functions: https://github.com/golang/go/issues/61405)

Comment (calmh) [reply lib/model/service_map.go:82]: Indeed. I considered returning a copy of the map, but this seemed fine as well...

**Comment by calmh** [comment]
(lib/svcutil) Agreed, if and when it's used outside of the one package at least...

File: lib/model/model.go (hunk 1 above)
Comment (imsodin) [reply lib/model/model.go:1796]: Also my understanding :)

One potentialy small downside of the map-and-service-construct: Can't move the waiting part outside of the lock anymore - worst case it's still writing an index update received just before the conn was closed to db and thus we block pmut for a while longer than necessary. Doesn't seem very relevant though, if db is that slow that it matters operation wont be smooth anyway.

**Review by imsodin — COMMENTED** [review]
just some nits, lgtm otherwise

File: lib/model/indexhandler.go [hunk 4]
```diff
@@ -389,48 +385,35 @@ type indexHandlerFolderState struct {
...
+	// handler children.
+	return r.indexHandlers.Serve(ctx)
 }
 
 func (r *indexHandlerRegistry) startLocked(folder config.FolderConfiguration, fset *db.FileSet, runner service, startInfo *clusterConfigDeviceInfo) {
-	if is, ok := r.indexHandlers[folder.ID]; ok {
-		r.sup.RemoveAndWait(is.token, 0)
-		delete(r.indexHandlers, folder.ID)
-	}
+	r.indexHandlers.Remove(folder.ID)
```
[the remark this answers is not in the document]
Comment (calmh) [reply lib/model/indexhandler.go:412]: My bug, we did ...AndWait before and should do so now as well 👍

File: lib/model/service_map.go [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+	}
+	s.services[k] = v
+	s.tokens[k] = s.supervisor.Add(v)
+}
+
+// Get returns the service at the given key, or the empty value and false if
+// there is no service at that key.
+func (s *serviceMap[K, S]) Get(k K) (v S, ok bool) {
+	v, ok = s.services[k]
+	return
```
[the remark this answers is not in the document]
Comment (calmh) [reply lib/model/service_map.go:53]: I think I thought of it as documentation on what the bool is (though that's hardly necessary as it's a super common pattern) and the method body becomes a few characters shorter, possibly it evolved this was from an earlier iteration without the OK bool...

**Comment by calmh** [comment]
This doesn't fix #9021, are you sure your attempt does?

```
--- FAIL: TestAutoAcceptEnc (0.00s)
panic: bug: ClusterConfig called on closed or nonexistent connection [recovered]
	panic: bug: ClusterConfig called on closed or nonexistent connection

goroutine 2639 [running]:
testing.tRunner.func1.2({0xf78000, 0x1254330})
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1529 +0x39f
panic({0xf78000, 0x1254330})
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/runtime/panic.go:884 +0x213
github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0xc00088dba0, {0x1268188?, 0xc000453800?}, {{0xc005db1900?, 0x0?, 0x0?}})
	D:/a/syncthing/syncthing/lib/model/model.go:1177 +0x100a
github.com/syncthing/syncthing/lib/model.TestAutoAcceptEnc.func2({0x2, 0x23, 0xe5, 0xbf, 0x3f, 0x57, 0x1f, 0x39, 0xd2, 0xf0, ...}, ...)
	D:/a/syncthing/syncthing/lib/model/model_test.go:1341 +0x125
github.com/syncthing/syncthing/lib/model.TestAutoAcceptEnc(0xc00088d040)
	D:/a/syncthing/syncthing/lib/model/model_test.go:1398 +0x168a
testing.tRunner(0xc00088d040, 0x11418f8)
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/syncthing/syncthing/lib/model	2.348s
?   	github.com/syncthing/syncthing/lib/model/mocks	[no test files]
```

(latest build run on Windows)

**Comment by calmh** [comment]
Frankly the test seems kinda odd and even has a comment related to this panic, which it tries to work around by adding a new connection for the same device ID for every test iteration it does... I think this change (and yours) is sound, but I think the test does something else unrealistic/wrong for different reasons.

**Comment by imsodin** [comment]
I am sure it makes it less likely at least - I get that panic within a few runs on main and not at all on my PR with ` go test  -count 1000 -failfast -run AutoAcceptEnc ./lib/model/`. I now also checked your PR out, and indeed it fails too - I don't understand yet why.

File: lib/model/service_map.go [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+	m.supervisor = suture.New(m.String(), svcutil.SpecWithDebugLogger(l))
+	return m
+}
+
+// Add adds a service to the map, starting it on the supervisor. If there is
+// already a service at the given key, it is removed first.
+func (s *serviceMap[K, S]) Add(k K, v S) {
+	if tok, ok := s.tokens[k]; ok {
+		// There is already a service at this key, remove it first.
+		s.supervisor.Remove(tok)
```
Comment (imsodin) [inline lib/model/service_map.go:46]: The similar scenario in index registyr was a `RemoveAndWait`, but this shouldn't ever be called so hardly matters.

File: lib/model/model.go [hunk 7]
```diff
@@ -2251,11 +2252,11 @@ func (m *model) AddConnection(conn protocol.Connection, hello protocol.Hello) {
 	closed := make(chan struct{})
 	m.closed[deviceID] = closed
 	m.deviceDownloads[deviceID] = newDeviceDownloadState()
-	indexRegistry := newIndexHandlerRegistry(conn, m.deviceDownloads[deviceID], closed, m.Supervisor, m.evLogger)
+	indexRegistry := newIndexHandlerRegistry(conn, m.deviceDownloads[deviceID], m.evLogger)
 	for id, fcfg := range m.folderCfgs {
 		indexRegistry.RegisterFolderState(fcfg, m.folderFiles[id], m.folderRunners[id])
 	}
-	m.indexHandlers[deviceID] = indexRegistry
+	m.indexHandlers.Add(deviceID, indexRegistry)
```
Comment (imsodin) [inline lib/model/model.go:2259]: Not saying this is problematic or wrong, just noting a change to how it worked before (fixing it doesn't fix the test failure): Previously calling `newIndexHandlerRegistry` would also start the registry before looping folders, now it happens after.

**Comment by imsodin** [comment]
Can't say I understand why, but waiting for the index handler to stop outside of the `pmut` lock makes the test no longer/fail panic for me. Patch doing that on top of your PR: https://github.com/imsodin/syncthing/commit/50dc429439c67325df2150e5b5d1a0a0d8e473e8

**Comment by calmh** [comment]
That's bizarre. I would like to understand why that has any effect...

**Comment by calmh** [comment]
FWIW, this also "fixes" it for me;

```diff
diff --git a/lib/model/model.go b/lib/model/model.go
index 0fafd0d03..aad3a45da 100644
--- a/lib/model/model.go
+++ b/lib/model/model.go
@@ -1795,6 +1795,7 @@ func (m *model) Closed(conn protocol.Connection, err error) {
        delete(m.closed, device)
        m.indexHandlers.RemoveAndWait(device, 0)
        m.pmut.Unlock()
+       runtime.Gosched()

        m.progressEmitter.temporaryIndexUnsubscribe(conn)
        m.deviceDidClose(device, time.Since(conn.EstablishedAt()))
```

I'll see if I can figure this out later on, something seems to be async that shouldn't...

**Comment by imsodin** [comment]
I tried to figure out the sequence of events leading to the panic, but I can't say I really have a clear picture. However it definitely involves late effects of the previous test-case (config changes). And I am now more or less convinced that this test is a sufficiently messy to show that while the condition that leads to the panic holds most of the time, there's actually no guarantee it does: A connection might be closed right after a cluster-config is received, thus the model methods handling the two events can race on the pmut lock such that the connection gets closed/removed before the cluster-config. I think we should just return an error in that case, same as with the next condition that checks the configuration. That will still fail this test, but that's clearly a case of a deficient test (probably should be a bunch of separate sub-tests that either get their own state or properly clean up after themselves).

**Comment by calmh** [comment]
There, I fixed it, I believe. My interpretation is that this was a test-only failure. The thing is, we may under some circumstances try to close a connection more than once, from CommitConfiguration (device is now paused) and AddConnection (we're adding a new connection for the same device) or something. This happens because *starting* a close is just calling `conn.Close()`, and the actual cleanup happens when the connection calls back into `(*Model).Closed()`. Now, `(*Model).Closed()` must only be called once per connection because it (currently, pre-my-other-PR) just works per device and assumes any connection present for the device is the one it's closing. Our protocol code does this correctly -- it only closes once, because there's a `sync.Once` for the whole thing. The `fakeConnection` wasn't as precise about this and would happily call the closed callback more than once. Normally this wouldn't be a problem but the `TestAutoAcceptEnc` effectively races AddConnection against Close all the time while causing Close() to be called multiple times, so sometimes closing connection A would remove the structures for connection B.

Adding the Gosched or channel stuff or a wait gave things to close before adding the next connection.

**Review by imsodin — APPROVED** [review]
