### PR TITLE
lib/model, lib/protocol: Track closing connections (fixes #5828)

### LINKED ISSUE #5828: panic: Index update for not running folder
```
Stacktrace (most recent call first):

  File "C:/BuildAgent/work/174e136266f8a219/lib/model/model.go", line 997, in handleIndex
    panic(fmt.Sprintf("%v for not running folder %q", op, folder))
  File "C:/BuildAgent/work/174e136266f8a219/lib/model/model.go", line 964, in IndexUpdate
    m.handleIndex(deviceID, folder, fs, true)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/nativemodel_windows.go", line 25, in IndexUpdate
    m.Model.IndexUpdate(deviceID, folder, files)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/protocol.go", line 567, in handleIndexUpdate
    c.receiver.IndexUpdate(c.id, im.Folder, im.Files)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/protocol.go", line 429, in dispatcherLoop
    c.handleIndexUpdate(*msg)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/protocol.go", line 255, in func1
    err := c.dispatcherLoop()

panic: Index update for not running folder "qkqer-stxet"
```
https://crash.syncthing.net/report/66/c9/66c93e0353714dea390830d3caa769bf3424832f41673c10bb74d251f1611229  
Sentry Issue: [SYNCTHING-1H](https://sentry.syncthing.net/syncthing/syncthing/issues/65/?referrer=github_integration)

I believe this is due to a race: We close the connection when stopping a folder, but do not wait for the connection to actually be closed before removing the folder elements from the model. So there is a small window where incoming indexes (or other things) can go through after that point. PR incoming.

### PR DESCRIPTION
**Pull request by imsodin**
### Purpose

This change has a few connected elements:

1. Stopping a folder now waits on the closed connections to stop before removing the folder elements from the model (this is the actual fix of #5828).
2. The utility function closing connections now returns the closed channels of these connections, such that the caller can wait on them if required (convenience and doing both things (closing and getting closed channels) under the same lock).
3. Speed up calls to `protocol.Close` and sending close messages in the protocol:  
Close now spawns a goroutine for both sending the close message and closing, while before it spawned the goroutine just for closing after sending the message. Thus the caller can quicker go on with whatever else it needs to do and if it needs to wait, it already now has to wait for receiving the `Closed` callback.  
The second element is a mechanism to stop sending messages on close: Right now the close message competes with any other message to get sent. With the additional `sendStop` chan all messages waiting to be sent abort when a close message is to be sent.

### Testing

None specific to this issue, just spun up the test system and restarted a folder. I don't have an idea how to unit test this race consistently.

### CODE REVIEW

File: lib/protocol/protocol.go [hunk 1]
```diff
@@ -867,26 +870,29 @@ func (c *rawConnection) shouldCompressMessage(msg message) bool {
...
+		c.sendCloseOnce.Do(func() {
+			close(c.sendStop)
+			done := make(chan struct{})
 			select {
-			case <-done:
+			case c.closeBox <- asyncMessage{&Close{err.Error()}, done}:
+				select {
+				case <-done:
+				case <-timeout.C:
+				case <-c.closed:
```
Comment (AudriusButkevicius) [inline lib/protocol/protocol.go]: This is confusing. We await for something but there are no calls after this, why do we care on waiting for this subselect?

Comment (imsodin) [reply lib/protocol/protocol.go]: We are waiting for `done`/the send to go through (or timeout or connection being closed under our feat) before calling `c.internalClose` further down. While it doesn't make a difference we could also return on the `c.closed` cases (`c.internalClose` is a noop if `c.closed` is closed).

File: lib/model/model.go [hunk 2]
```diff
@@ -1434,23 +1432,36 @@ func (m *model) Closed(conn protocol.Connection, err error) {
...
 		if conn, ok := m.conn[dev]; ok {
 			conns = append(conns, conn)
+			closed = append(closed, m.closed[dev])
 		}
 	}
 	m.pmut.Unlock()
 	for _, conn := range conns {
 		conn.Close(err)
 	}
+	return closed
```
Comment (AudriusButkevicius) [inline lib/model/model.go]: Not a fan of this []chan approach. We always wait for all of them, perhaps return a Waiter() or a wait group?

Comment (imsodin) [reply lib/model/model.go]: Went with a `Waiter`, definitely neater that way, thanks.

**Comment by imsodin** [comment]
Not closing connections for reconfiguration would indeed be quite nice, but it would introduce similar timing issues, where you'd have to make sure after re-sending the cluster config that no more calls regarding this folder come in before removing the folder from the model.

**Comment by calmh** [comment]
Didn't read this yet, just noting that

> Stopping a folder now waits on the closed connections to stop before removing the folder elements from the model

this can take minutes, unless there are deadlines wired to it, given block transfers in progress etc. I already noticed in a different context that pausing a device does not immediately disconnect a device nowadays, it can take a while and the device shows as "paused" while still connected... Not sure if related, really, or I'm just talking shit but I'm carefully skeptical about more "wait for x before y" things when the wait might be long and appear to the user like stuff hung or nothing's happening in the meantime.

**Comment by imsodin** [comment]
Closing the connection waits on two things: Sending a close msg, capped at 10s, and the "dispatcher" loop to terminate. The latter calls methods on the model, and that's exactly whats needed to prevent the panic. Calls in that loop that may take a moment are index updates and requests, both of which should take about the same time as what we are already waiting on: Folder to stop (pulling in progress can mean waiting for multiple outstanding requests). So in the end the worst case is a 10s wait.

An alternative is to just silently drop calls to methods for a non-existing folder. That may be fine, but it would be a clear deviation from current principles.

File: lib/protocol/protocol.go [hunk 3]
```diff
@@ -867,26 +870,29 @@ func (c *rawConnection) shouldCompressMessage(msg message) bool {
...
 // argument specifies the reason for closing the connection.
 func (c *rawConnection) Close(err error) {
-	c.sendCloseOnce.Do(func() {
-		done := make(chan struct{})
-		timeout := time.NewTimer(CloseTimeout)
-		select {
-		case c.closeBox <- asyncMessage{&Close{err.Error()}, done}:
+	// Close might be called from a method that is called from within
+	// dispatcherLoop, resulting in a deadlock.
+	// The sending above must happen before spawning the routine, to prevent
```
Comment (calmh) [inline lib/protocol/protocol.go]: I don't understand this comment. Which sending above?

File: lib/protocol/protocol.go [hunk 4]
```diff
@@ -662,12 +664,13 @@ func (c *rawConnection) send(msg message, done chan struct{}) bool {
 	select {
 	case c.outbox <- asyncMessage{msg, done}:
 		return true
+	case <-c.sendStop:
```
Comment (calmh) [inline lib/protocol/protocol.go]: Slightly confusing naming - we're not sending a stop, we're stopping the sender? `preventSends`? I dunno. Maybe leave as is.

File: lib/protocol/protocol.go (hunk 3 above)
Comment (imsodin) [reply lib/protocol/protocol.go]: Thanks so much - I just didn't read that comment at all and it is explaining why I can't do what I did in this PR before. It's nice that I write comments (often after some nudging), but I really also need to read them...
