### PR TITLE
fix(gui): show restarting modal during upgrade restart (fixes #1248)

### LINKED ISSUE #1248: Better restart message during auto-upgrade
Just a small issue. When Syncthing is upgraded we see a message that network or syncthing is unavailable (cannot remember the exact wording). To prevent confusion it would be better, if we see a message which states something like this: Syncthing is restarting and will be available in a few seconds.

### PR DESCRIPTION
**Pull request by steadytao**
### Purpose

This change improves the GUI messaging during an upgrade-triggered restart.

Currently, when Syncthing restarts itself after completing a self/automatic upgrade, the GUI briefly shows the generic **“Connection Error / Syncthing seems to be down”** modal. This disconnect is expected, but the message is misleading ([#1248](https://github.com/syncthing/syncthing/issues/1248)).

This patch introduces a small, time-bounded mechanism to distinguish an **expected upgrade restart** from a real network failure, and shows the **“Restarting”** modal only when appropriate.

---

### Changes Made

- Emit a new `UpgradeRestartScheduled` event when an upgrade completes and a restart is scheduled.
- In the GUI, record an *expected restart window* based on the scheduled delay.
- When the GUI disconnects:
  - If the disconnect occurs within the expected restart window, show the **Restarting** modal.
  - Otherwise, preserve the existing **Connection Error** behaviour.
- Clear the restart expectation on successful reconnect to avoid stale state.

This approach avoids showing the restarting modal early (e.g. during the full delay before restart) and only switches messaging at the moment the process actually goes offline.

---

### Previous PR Referenced

A prior pull request ([#10511](https://github.com/syncthing/syncthing/pull/10511)) attempted to show the restarting dialog as soon as the upgrade event fired, which resulted in incorrect UI state for up to a minute before the actual restart.

This implementation instead waits for the **actual disconnect** and only changes the UI if that disconnect occurs within a bounded, expected restart window.

Manual upgrade behaviour is unchanged; this only affects the upgrade-triggered restart path.

---

### Testing

Manual testing performed:
- Enabled self/automatic upgrade with an update available.
- Verified the GUI remains normal during the delay before restart.
- When the process restarts and the GUI disconnects, the **Restarting** modal is shown instead of the generic connection error.
- Verified that an unrelated network disconnect still shows the generic **Connection Error** modal.

### CODE REVIEW

File: cmd/syncthing/main.go [hunk 1]
```diff
@@ -748,8 +748,13 @@ func autoUpgrade(cfg config.Wrapper, app *syncthing.App, evLogger events.Logger)
 			continue
 		}
 		sub.Unsubscribe()
+		restartDelay := time.Minute
+		evLogger.Log(events.UpgradeRestartScheduled, map[string]interface{}{
```
Comment (calmh) [inline cmd/syncthing/main.go]:
```suggestion
		evLogger.Log(events.UpgradeRestartScheduled, map[string]any{
```
