### PR TITLE
Correctly set and clear errors for missing folders (fixes #1937)

### LINKED ISSUE #1937: After missing folder is found again, the error message stays:
syncthing v0.11.8 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC

unbenannt

How to reproduce:

 - Unmount shared folder
 - Scan
 - Mount again
 - Scan

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

File: internal/model/folderstate.go [hunk 1]
```diff
@@ -111,3 +110,26 @@ func (s *stateTracker) setError(err error) {
...
 }
+
+// clearError sets the folder state to FolderIdle and clears the error
+func (s *stateTracker) clearError() {
+	s.mut.Lock()
+	if s.current == FolderError {
+		eventData := map[string]interface{}{
+			"folder": s.folder,
+			"to":     s.current.String(),
+			"from":   FolderIdle.String(),
```
Comment (calmh) [inline internal/model/folderstate.go]: I think these are the wrong way around

**Comment by calmh** [comment]
Otherwise :100:
