### PR TITLE
lib/model: Don't panic on failed chmod-back on directory (fixes #5836)

### LINKED ISSUE #5836: panic: chmod ...: operation not permitted
```
syncthing v1.1.4 "Erbium Earthworm" (go1.12.5 linux-amd64) teamcity@build.syncthing.net 2019-05-12 19:17:55 UTC

goroutine 1000714 [running]:
github.com/syncthing/syncthing/lib/osutil.InWritableDir.func1(0xf2f5c0, 0xc0046400f0, 0xc005d32dc0, 0x19, 0xf28f00, 0xc002e475d0, 0xc0004a8c30)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/osutil/osutil.go:107 +0xb4
github.com/syncthing/syncthing/lib/osutil.InWritableDir(0xc0004a8d68, 0xf2f5c0, 0xc0046400f0, 0xc005d32dc0, 0x4b, 0xf10ec0, 0xc002e77d10)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/osutil/osutil.go:113 +0x13b
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).deleteFile(0xc0001c0840, 0xc005d32dc0, 0x4b, 0x0, 0x0, 0x0, 0x5b26c0bf, 0x29d0c913, 0xa6a9c1e3243bbb5c, 0x1, ...)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:856 +0x89b
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).processDeletions(0xc0001c0840, 0xc002e76a20, 0x0, 0x0, 0x0, 0xc0027798c0, 0xc0027796e0)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:509 +0x294
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration(0xc0001c0840, 0xc0027796e0, 0xc002779600)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:283 +0x6a2
github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pull(0xc0001c0840, 0x4063c0898b700)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder_sendrecv.go:195 +0x70b
github.com/syncthing/syncthing/lib/model.(*folder).Serve.func2()
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder.go:137 +0x8c
github.com/syncthing/syncthing/lib/model.(*folder).Serve(0xc0001c0840)
	/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/folder.go:163 +0x4db
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc0002b1a40, 0xc00000000d, 0x7fade8522550, 0xc0001c0840)
	/opt/tcagent/syncthing-1-work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:600 +0x47
created by github.com/thejerf/suture.(*Supervisor).runService
	/opt/tcagent/syncthing-1-work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:588 +0x5b
```

https://github.com/syncthing/syncthing/blob/e4956358fbab0d78e975d474acba2a0d098e4adc/lib/osutil/osutil.go#L103-L108

Comment says it's bizarre and I agree (I probably wrote it), nonetheless here we are. A panic isn't super appropriate here.

### PR DESCRIPTION
**Pull request by calmh**
This makes the "in writable dir"-wrapper log chmod-back errors instead
of panicking. To do that we need a logger so the function moved into the
model package which is also the only place it's used. The tests came
along.

(The test also exercised osutil.RenameOrCopy like some sort of
piggybacking. I removed that.)

### CODE REVIEW

File: lib/model/utils_test.go [hunk 1]
```diff
@@ -0,0 +1,205 @@
...
+	if err == nil {
+		t.Error("testdata/nonexistent/foo returned nil error")
+	}
+	err = inWritableDir(create, fs, "testdata/file/foo")
+	if err == nil {
+		t.Error("testdata/file/foo returned nil error")
+	}
+}
+
+func TestinWritableDirWindowsRemove(t *testing.T) {
```
Comment (golangcibot) [inline lib/model/utils_test.go]: tests: TestinWritableDirWindowsRemove has malformed name: first letter after 'Test' must not be lowercase (from `govet`)

File: lib/model/utils_test.go [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+
+	for _, path := range []string{"testdata/windows/ro/readonly", "testdata/windows/ro", "testdata/windows"} {
+		err := inWritableDir(os.Remove, fs, path)
+		if err != nil {
+			t.Errorf("Unexpected error %s: %s", path, err)
+		}
+	}
+}
+
+func TestinWritableDirWindowsRemoveAll(t *testing.T) {
```
Comment (golangcibot) [inline lib/model/utils_test.go]: tests: TestinWritableDirWindowsRemoveAll has malformed name: first letter after 'Test' must not be lowercase (from `govet`)

File: lib/model/utils_test.go [hunk 3]
```diff
@@ -0,0 +1,205 @@
...
+	os.Mkdir("testdata/windows/ro", 0500)
+	create("testdata/windows/ro/readonly")
+	os.Chmod("testdata/windows/ro/readonly", 0500)
+
+	if err := os.RemoveAll("testdata/windows"); err != nil {
+		t.Errorf("Unexpected error: %s", err)
+	}
+}
+
+func TestinWritableDirWindowsRename(t *testing.T) {
```
Comment (golangcibot) [inline lib/model/utils_test.go]: tests: TestinWritableDirWindowsRename has malformed name: first letter after 'Test' must not be lowercase (from `govet`)

File: lib/model/folder_sendrecv.go [hunk 4]
```diff
@@ -1078,7 +1078,7 @@ func (f *sendReceiveFolder) handleFile(file protocol.FileInfo, copyChan chan<- c
 			// Otherwise, discard the file ourselves in order for the
 			// sharedpuller not to panic when it fails to exclusively create a
 			// file which already exists
-			osutil.InWritableDir(f.fs.Remove, f.fs, tempName)
+			inWritableDir(f.fs.Remove, f.fs, tempName)
```
Comment (golangcibot) [inline lib/model/folder_sendrecv.go]: Error return value of `inWritableDir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 5]
```diff
@@ -0,0 +1,205 @@
...
+func TestInWriteableDir(t *testing.T) {
+	err := os.RemoveAll("testdata")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.RemoveAll("testdata")
+
+	fs := fs.NewFilesystem(fs.FilesystemTypeBasic, ".")
+
+	os.Mkdir("testdata", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `os.Mkdir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 6]
```diff
@@ -0,0 +1,205 @@
...
+	os.Mkdir("testdata/rw", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `os.Mkdir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 7]
```diff
@@ -0,0 +1,205 @@
...
+	os.Mkdir("testdata/ro", 0500)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `os.Mkdir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 8]
```diff
@@ -0,0 +1,205 @@
...
+	if runtime.GOOS != "windows" {
+		t.Skipf("Tests not required")
+		return
+	}
+
+	err := os.RemoveAll("testdata")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.Chmod("testdata/windows/ro/readonlynew", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `os.Chmod` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 9]
```diff
@@ -0,0 +1,205 @@
...
+		}
+		fd.Close()
+		return nil
+	}
+
+	os.Mkdir("testdata", 0700)
+
+	os.Mkdir("testdata/windows", 0500)
+	os.Mkdir("testdata/windows/ro", 0500)
+	create("testdata/windows/ro/readonly")
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `create` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 10]
```diff
@@ -0,0 +1,205 @@
...
+	os.Chmod("testdata/windows/ro/readonly", 0500)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `os.Chmod` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 11]
```diff
@@ -0,0 +1,205 @@
...
+	if runtime.GOOS != "windows" {
+		t.Skipf("Tests not required")
+		return
+	}
+
+	err := os.RemoveAll("testdata")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.Chmod("testdata/windows/ro/readonlynew", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `os.Chmod` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 12]
```diff
@@ -0,0 +1,205 @@
...
+		}
+		fd.Close()
+		return nil
+	}
+
+	os.Mkdir("testdata", 0700)
+
+	os.Mkdir("testdata/windows", 0500)
+	os.Mkdir("testdata/windows/ro", 0500)
+	create("testdata/windows/ro/readonly")
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `create` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 13]
```diff
@@ -0,0 +1,205 @@
...
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `create` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 14]
```diff
@@ -0,0 +1,212 @@
...
+	dir, err := ioutil.TempDir("", "")
+	if err != nil {
+		t.Skip(err)
+	}
+
+	defer os.RemoveAll(dir)
+
+	fs := fs.NewFilesystem(fs.FilesystemTypeBasic, dir)
+
+	fs.Mkdir("testdata", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `fs.Mkdir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 15]
```diff
@@ -0,0 +1,212 @@
...
+	fs.Mkdir("testdata/rw", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `fs.Mkdir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 16]
```diff
@@ -0,0 +1,212 @@
...
+	fs.Mkdir("testdata/ro", 0500)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `fs.Mkdir` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 17]
```diff
@@ -0,0 +1,212 @@
...
+
+	dir, err := ioutil.TempDir("", "")
+	if err != nil {
+		t.Skip(err)
+	}
+
+	defer os.RemoveAll(dir)
+
+	fs := fs.NewFilesystem(fs.FilesystemTypeBasic, dir)
+	defer fs.Chmod("testdata/windows/ro/readonlynew", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `fs.Chmod` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 18]
```diff
@@ -0,0 +1,212 @@
...
+		fd.Close()
+		return nil
+	}
+
+	fs.Mkdir("testdata", 0700)
+
+	fs.Mkdir("testdata/windows", 0500)
+	fs.Mkdir("testdata/windows/ro", 0500)
+	create("testdata/windows/ro/readonly")
+	fs.Chmod("testdata/windows/ro/readonly", 0500)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `fs.Chmod` is not checked (from `errcheck`)

File: lib/model/utils_test.go [hunk 19]
```diff
@@ -0,0 +1,212 @@
...
+
+	dir, err := ioutil.TempDir("", "")
+	if err != nil {
+		t.Skip(err)
+	}
+
+	defer os.RemoveAll(dir)
+
+	fs := fs.NewFilesystem(fs.FilesystemTypeBasic, dir)
+	defer fs.Chmod("testdata/windows/ro/readonlynew", 0700)
```
Comment (golangcibot) [inline lib/model/utils_test.go]: Error return value of `fs.Chmod` is not checked (from `errcheck`)

**Comment by calmh** [comment]
Also fixed shady tests to use `fs` instead of `os` and a real temp dir instead of stomping on `model/testdata`

File: lib/model/util.go [hunk 20]
```diff
@@ -59,3 +63,35 @@ func (d *deadlockDetector) Watch(name string, mut sync.Locker) {
...
+		// file or directory inside it.
+		if err := fs.Chmod(dir, 0755); err == nil {
+			// Chmod succeeded, we should change the permissions back on the way
+			// out. If we fail we log the error as we have irrevocably messed up
+			// at this point. :( (The operation we were called to wrap has
+			// succeeded or failed on its own so returning an error to the
+			// caller is inappropriate.)
+			defer func() {
+				if err := fs.Chmod(dir, info.Mode()); err != nil {
+					l.Warnln("Failed to restore directory permissions after gaining write access:", err)
```
Comment (imsodin) [inline lib/model/util.go]: A few of the reported panics were that the directory didn't exist anymore. I'd check for that to prevent warning over nothing.

Comment (calmh) [reply lib/model/util.go]: Good point

File: lib/model/utils_test.go [hunk 21]
```diff
@@ -0,0 +1,212 @@
...
+	"io/ioutil"
+	"os"
+	"runtime"
+	"testing"
+
+	"github.com/syncthing/syncthing/lib/fs"
+)
+
+func TestInWriteableDir(t *testing.T) {
+	dir, err := ioutil.TempDir("", "")
```
Comment (imsodin) [inline lib/model/utils_test.go]: High nitpick, ignore at your leisure: I started to put a prefix before temporary dirs such that if any of them are left behind (ctrl-c) they are easily identifiable as syncthing testing stuff in /tmp (`createTmpDir` exists for that purpose).

**Comment by calmh** [comment]
I see my laptop was misconfigured to push branches to the main repo and I didn't notice, sorry about that

File: lib/model/utils_test.go [hunk 22]
```diff
@@ -0,0 +1,195 @@
...
+		if err != nil {
+			return err
+		}
+		fd.Close()
+		return nil
+	}
+
+	// These should succeed
+
+	err = inWritableDir(create, fs, "testdata/file")
```
Comment (golangcibot) [inline lib/model/utils_test.go]: undeclared name: `err` (from `typecheck`)
