### PR TITLE
lib/fs: use file clone ioctl wrappers and types from golang.org/x/sys/unix

### LINKED ISSUE #6898: tests in TestCopyRange fail on ppc64le with "inappropriate ioctl for device"
From an attempted 1.8.0 build on fedora rawhide (with go 1.15, but using `-tags noquic` where necessary):

```
go test -buildmode pie -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\''' github.com/syncthing/syncthing/lib/fs
--- FAIL: TestCopyRange (1.28s)
    --- FAIL: TestCopyRange/tmp (1.28s)
        --- FAIL: TestCopyRange/tmp/ioctl (0.22s)
            --- FAIL: TestCopyRange/tmp/ioctl/append_to_end (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/append_to_end_offsets_at_start (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/overwrite_part_of_destination_region (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/overwrite_all_of_destination (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/overwrite_part_of_destination (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/destination_gets_expanded_as_it_is_being_written_to (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/unaligned_source_offset_unaligned_size (0.01s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/unaligned_source_offset_aligned_size (0.01s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/unaligned_destination_offset_unaligned_size (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/unaligned_destination_offset_aligned_size (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/aligned_offsets_unaligned_size (0.02s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/last_block (0.01s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/whole_file_copy_block_aligned (0.01s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
            --- FAIL: TestCopyRange/tmp/ioctl/whole_file_copy_not_block_aligned (0.01s)
                filesystem_copy_range_test.go:332: inappropriate ioctl for device
FAIL
FAIL	github.com/syncthing/syncthing/lib/fs	1.604s
FAIL
```

Looks like the ioctl that's used for the new copyRange functionality is not available on ppc64le / POWER.
The build succeeds on all other architectures supported by fedora (x86_64, i686, armv7hl / armhfp, aarch64, s390x / System Z).

### PR DESCRIPTION
**Pull request by tklauser**
### Purpose

Use the `IoctlFileClone` and `IoctlFileCloneRange` ioctl wrappers and the
`FileCloneRange` type provided by `golang.org/x/sys/unix` instead of
locally implementing them. This also allows to re-enable the code for
ppc/ppc64/ppc64le again (see commit 758a1a6a3729 ("lib/fs: Disable ioctl
on ppc (fixes #6898) (#6901)")) since `golang.org/x/sys/unix` internally
uses the correct `FICLONE` and `FICLONERANGE` values depending on `$GOARCH`.

This PR also bumps the version of `golang.org/x/sys` 

### Testing

Ran unit tests in `lib/fs` using `go test -v ./lib/fs`

### CODE REVIEW

**Review by calmh — DISMISSED** [review]

**Comment by AudriusButkevicius** [comment]
I'll have a look this evening

File: lib/fs/basicfs_copy_range_ioctl.go [hunk 1]
```diff
@@ -56,38 +36,38 @@ func copyRangeIoctl(src, dst basicFile, srcOffset, dstOffset, size int64) error
...
 		return 0, nil
 	})
 	// Failure in withFileDescriptors
 	if err != nil {
 		return err
 	}
-	if errNo != 0 {
-		return errNo
+	if innerErr != nil {
+		return innerErr
```
Comment (AudriusButkevicius) [inline lib/fs/basicfs_copy_range_ioctl.go:70]: I think the innerErr magic can go now.

The reason is was there is because we used syscall.Errno which is always not nil, even if the errno is 0. 
We lose the sycall.Errno type as we return from withFileDescriptors, so we did the external variable magic to capture that.

The unix library now handles it for us, so we can just `return 0, errorFromUnixPackage` and then just return whatever was returned from withFileDescriptors straight back out.

Comment (tklauser) [reply lib/fs/basicfs_copy_range_ioctl.go]: Done, thanks for the review.

File: lib/fs/basicfs_copy_range_ioctl.go [hunk 2]
```diff
@@ -56,38 +36,28 @@ func copyRangeIoctl(src, dst basicFile, srcOffset, dstOffset, size int64) error
...
-		var errNo syscall.Errno
 		_, err := withFileDescriptors(src, dst, func(srcFd, dstFd uintptr) (int, error) {
-			_, _, errNo = syscall.Syscall(syscall.SYS_IOCTL, dstFd, FICLONE, srcFd)
-			return 0, nil
+			return 0, unix.IoctlFileClone(int(dstFd), int(srcFd))
 		})
 		// Failure in withFileDescriptors
 		if err != nil {
 			return err
 		}
```
Comment (AudriusButkevicius) [inline lib/fs/basicfs_copy_range_ioctl.go:45]: No need for this if anymore, just return err straight through

Comment (tklauser) [reply lib/fs/basicfs_copy_range_ioctl.go:45]: Good point, done.

**Review by AudriusButkevicius — APPROVED** [review]
