### PR TITLE
Automatically fix file name normalization errors (fixes #430)

### LINKED ISSUE #430: Syncthing should offer fixing UTF-8 encoding issues/conflicts
I got the error 

> File "..." contains non-NFC UTF-8 sequences and cannot be synced. Consider renaming.

many times on many files.

1. I don't know what non-NFC means.  Message should be more clear.
2. Syncthing should sync all files regardless of their names.  These are both Windows 7 machines, so there's no compatibility problem between the OSes.  If there is a problem, like Linux using ":" in filenames and syncing with Windows, it should sync the files anyway and sanitize the names for each OS.

### PR DESCRIPTION
**Pull request by calmh**
When the folder config `AutoNormalize` is on (which is the default), we automatically fix normalization errors in file names. Most users will never notice. The ones that care about this kind of stuff should be pleased that we fix their inconsistencies.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I guess this is just normalizing values which are valid on all OSes?

**Comment by calmh** [comment]
Yeah, this is just about how to encode the `¨` above the `a` in `ä` and so on. We enforce the local convention, or the best guess of one where there isn't one (i.e. NFC). Basically this is what we already do, but now we fix the file names instead of just refusing to sync the files.

**Comment by calmh** [comment]
@st-jenkins run integration tests please

**Comment by calmh** [comment]
@st-jenkins run integration tests please

File: internal/scanner/walk.go [hunk 1]
```diff
@@ -149,11 +153,63 @@ func (w *Walker) walkAndHashFiles(fchan chan protocol.FileInfo) filepath.WalkFun
...
+		if rn != normalizedRn {
+			// The file name was not normalized.
+
+			if !w.AutoNormalize {
+				// We're not authorized to do anything about it, so complain and skip.
+
+				l.Warnf("File name %q is not in the correct UTF8 normalization form; skipping.", rn)
+				if info.IsDir() {
+					return filepath.SkipDir
+				}
```
Comment (AudriusButkevicius) [inline internal/scanner/walk.go]: so I'd do this if before the whole thing, set the resulting value to rval and use that reducing loc

**Comment by calmh** [comment]
@AudriusButkevicius Thanks for thinking...
