### PR TITLE
all: add comment to ensure correct atomics alignment (closes #5813)

### LINKED ISSUE #5813: Potential bugs on old cores: using 64-bit functions sync/atomic
### Bug Report
I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running syncthing on these old cores.

Usage Position: (There may be more)
        File:lib/protocol/counting.go
	Line:24,25
	File:cmd/strelaysrv/status.go
	Line:52,53
	File:cmd/strelaysrv/session.go atomic.LoadInt64 atomic.AddInt64
	Line:254

### Version Information

Syncthing Version: master. 
Latest commit: bf744ded311cdeac6234bce95a8a4871baaefcc0

### LINKED ISSUE #5828: panic: Index update for not running folder
```
Stacktrace (most recent call first):

  File "C:/BuildAgent/work/174e136266f8a219/lib/model/model.go", line 997, in handleIndex
    panic(fmt.Sprintf("%v for not running folder %q", op, folder))
  File "C:/BuildAgent/work/174e136266f8a219/lib/model/model.go", line 964, in IndexUpdate
    m.handleIndex(deviceID, folder, fs, true)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/nativemodel_windows.go", line 25, in IndexUpdate
    m.Model.IndexUpdate(deviceID, folder, files)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/protocol.go", line 567, in handleIndexUpdate
    c.receiver.IndexUpdate(c.id, im.Folder, im.Files)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/protocol.go", line 429, in dispatcherLoop
    c.handleIndexUpdate(*msg)
  File "C:/BuildAgent/work/174e136266f8a219/lib/protocol/protocol.go", line 255, in func1
    err := c.dispatcherLoop()

panic: Index update for not running folder "qkqer-stxet"
```
https://crash.syncthing.net/report/66/c9/66c93e0353714dea390830d3caa769bf3424832f41673c10bb74d251f1611229  
Sentry Issue: [SYNCTHING-1H](https://sentry.syncthing.net/syncthing/syncthing/issues/65/?referrer=github_integration)

I believe this is due to a race: We close the connection when stopping a folder, but do not wait for the connection to actually be closed before removing the folder elements from the model. So there is a small window where incoming indexes (or other things) can go through after that point. PR incoming.

### PR DESCRIPTION
**Pull request by arl**
### Purpose

There was really nothing to fix, as I checked the entire code base and **all** atomically accessed 64-bit variables (via sync/atomic) **are** actually 64-bit aligned.

This is the commit message:

Per the [`sync/atomic` bug note](https://golang.org/pkg/sync/atomic/#pkg-note-BUG):

> On ARM, x86-32, and 32-bit MIPS, it is the caller's
> responsibility to arrange for 64-bit alignment of 64-bit words
> accessed atomically. The first word in a variable or in an
> allocated struct, array, or slice can be relied upon to be
> 64-bit aligned.

All atomic accesses of 64-bit variables in syncthing code base are
currently ok (i.e they are all 64-bit aligned).

Generally, the bug is triggered because of incorrect alignement
of struct fields. Free variables (declared in a function) are
guaranteed to be 64-bit aligned by the Go compiler.

To ensure the code remains correct upon further addition/removal
of fields, which would change the currently correct alignment, I
added the following comment where required:

     // atomic, must remain 64-bit aligned

### Testing

I ran the tests on an arm v6 platform. 
No tests have been added as the only code modifications are added comments.

closes #5813

### CODE REVIEW

File: lib/protocol/counting.go [hunk 1]
```diff
@@ -10,8 +10,8 @@ import (
 
 type countingReader struct {
 	io.Reader
-	tot  int64 // bytes
-	last int64 // unix nanos
+	tot  int64 // bytes (atomic, must remain 64-bit aligned)
+	last int64 // unix nanos (atomic, must remain 64-bit aligned)
 }
```
Comment (AudriusButkevicius) [inline lib/protocol/counting.go]: I wonder if we need to move the interface below

Comment (arl) [reply lib/protocol/counting.go]: As stated in the commit description, this is not required.

The size of an interface is 2 machine-word long, for all platforms, on a 32-bit architecture such as arm sizeof(interface) = 64-bit, implying that `tot` and `last` offset are, respectively, 64 and 128 bits from the top of the struct.

All those values are guaranteed with the standard Go compiler: [go/types/sizes.go](https://golang.org/src/go/types/sizes.go?s=4090:4130)
