### PR TITLE
api, gui: Prevent connection issues due to unsupported-upgrade (fixes #8569) 

### LINKED ISSUE #8569: Periodic connection losses to webui because docker image doesn't support upgrade
### Environment
I am using the official syncthing/syncthing docker image in the latest version (v1.21.0).

### Problem
Every now and then the webui displays for a short moment <1s that the connection to the server is lost.

The reason is known. It is because the webui fails to call:
https://mybaseurl/rest/system/upgrade

This endpoint responds http status code 500 and the following text:
`upgrade unsupported`
(which is normal for the docker image)

The webui doesn't seem to understand the response and interprets it as server failure.

### Proposed changes
- Change the responded http status code to "501 Not Implemented"
- Accept code 501 as valid response for the call to the upgrade-check endpoint so that the webui doesn't display connection errors.

### PR DESCRIPTION
**Pull request by er-pa**
There are some situations where an upgrade wouldn't be supported, even though the noUpgrade bool isn't set. So when handling the errors that are caused by this, when attempting an upgrade, it shouldn't lead to some sort of offline-message/restart/warning/etc...

I added some checks on specific errors related to this and return a 501 (Not Implemented) response instead, in case of an "UpgradeUnsupported"-error. Additionally, on the GUI-side, the 501-response is now not to be considered an error to act upon.

### Testing

Run it in Docker and use the related /rest/system/upgrade-call to see what it returns and verify whether the GUI stays silent / does something we don't want it to do. Used extra logging on 'upgrade' to pinpoint the causing lines and to see if it still results in a, potential, problem.

### CODE REVIEW

File: lib/api/api.go [hunk 1]
```diff
@@ -1424,12 +1424,16 @@ func (s *service) getEventSub(mask events.EventType) events.BufferedSubscription
...
 func (s *service) getSystemUpgrade(w http.ResponseWriter, _ *http.Request) {
 	if s.noUpgrade {
-		http.Error(w, upgrade.ErrUpgradeUnsupported.Error(), http.StatusServiceUnavailable)
+		http.Error(w, upgrade.ErrUpgradeUnsupported.Error(), http.StatusNotImplemented)
 		return
 	}
 	opts := s.cfg.Options()
 	rel, err := upgrade.LatestRelease(opts.ReleasesURL, build.Version, opts.UpgradeToPreReleases)
 	if err != nil {
+		if err == upgrade.ErrUpgradeUnsupported {
```
Comment (calmh) [inline lib/api/api.go:1433]: errors.Is for these, in case the error is wrapped

File: lib/api/api.go [hunk 2]
```diff
@@ -1472,6 +1476,10 @@ func (s *service) postSystemUpgrade(w http.ResponseWriter, _ *http.Request) {
...
+			http.Error(w, upgrade.ErrUpgradeUnsupported.Error(), http.StatusNotImplemented)
+			return
+		}
 		l.Warnln("getting latest release:", err)
 		http.Error(w, err.Error(), 500)
```
Comment (calmh) [inline lib/api/api.go:1484]: Maybe break this whole thing into a `func httpError(w, err)` that does the right thing and can be reused below, plus take the opportunity to make the `500` literal `http.StatusInternalServerError`

**Review by calmh — COMMENTED** [review]
👍

**Review by calmh — APPROVED** [review]
